; DarkBasic Professional RC2PBIncludes Ver 1.1 File - COMMANDS INITIALIZING
; By Frederic Cordier - 07.02.13
;
Procedure.l CheckCore()
  SUCCESS.l = 1
  If OpenLibrary( 1, "DBProCore.dll")
    DB_Core\PrintR= AIsFunction( 1 , "?PrintR@@YAX_J@Z" ) ; 1 PRINT Print Statements
    DB_Core\PrintO= AIsFunction( 1 , "?PrintO@@YAXN@Z" ) ; 2 PRINT Print Statements
    DB_Core\CeilFF= AIsFunction( 1 , "?CeilFF@@YAKM@Z" ) ; 3 CEIL Value
    DB_Core\FloorFF= AIsFunction( 1 , "?FloorFF@@YAKM@Z" ) ; 4 FLOOR Value
    DB_Core\PrintS= AIsFunction( 1 , "?PrintS@@YAXPAD@Z" ) ; 5 PRINT Print Statements
    DB_Core\Print0= AIsFunction( 1 , "?Print0@@YAXXZ" ) ; 6 PRINT 
    DB_Core\PrintCR= AIsFunction( 1 , "?PrintCR@@YAX_J@Z" ) ; 7 PRINTC Print Statements
    DB_Core\PrintCO= AIsFunction( 1 , "?PrintCO@@YAXN@Z" ) ; 8 PRINTC Print Statements
    DB_Core\PrintCS= AIsFunction( 1 , "?PrintCS@@YAXPAD@Z" ) ; 9 PRINTC Print Statements
    DB_Core\Cls= AIsFunction( 1 , "?Cls@@YAXXZ" ) ; 10 CLS 
    DB_Core\SetCursor= AIsFunction( 1 , "?SetCursor@@YAXHH@Z" ) ; 11 SET CURSOR X,Y
    DB_Core\InputR= AIsFunction( 1 , "?InputR@@YA_JXZ" ) ; 12 INPUT Variable
    DB_Core\InputO= AIsFunction( 1 , "?InputO@@YANXZ" ) ; 13 INPUT Variable
    DB_Core\InputS= AIsFunction( 1 , "?InputS@@YAKK@Z" ) ; 14 INPUT Variable
    DB_Core\RndLL= AIsFunction( 1 , "?RndLL@@YAHH@Z" ) ; 16 RND Range Value
    DB_Core\GetDXVer= AIsFunction( 1 , "?GetDXVer$@@YAKK@Z" ) ; 17 GET DX VERSION$ 
    DB_Core\TimerL= AIsFunction( 1 , "?TimerL@@YAHXZ" ) ; 18 TIMER 
    DB_Core\CosFF= AIsFunction( 1 , "?CosFF@@YAKM@Z" ) ; 19 COS Value
    DB_Core\InkeyS= AIsFunction( 1 , "?InkeyS@@YAKK@Z" ) ; 21 INKEY$ 
    DB_Core\SyncSleep= AIsFunction( 1 , "?SyncSleep@@YAXH@Z" ) ; 22 SYNC SLEEP Flag Processor Friendly
    DB_Core\SyncOn= AIsFunction( 1 , "?SyncOn@@YAXXZ" ) ; 23 SYNC ON 
    DB_Core\SyncOff= AIsFunction( 1 , "?SyncOff@@YAXXZ" ) ; 24 SYNC OFF 
    DB_Core\Sync= AIsFunction( 1 , "?Sync@@YAXXZ" ) ; 25 SYNC 
    DB_Core\SyncRate= AIsFunction( 1 , "?SyncRate@@YAXH@Z" ) ; 26 SYNC RATE Rate
    DB_Core\SyncMask= AIsFunction( 1 , "?SyncMask@@YAXK@Z" ) ; 48 SYNC MASK Ignore Camera Mask
    DB_Core\ReadR= AIsFunction( 1 , "?ReadR@@YA_JXZ" ) ; 60 READ Varable
    DB_Core\ReadO= AIsFunction( 1 , "?ReadO@@YANXZ" ) ; 61 READ Varable
    DB_Core\ReadS= AIsFunction( 1 , "?ReadS@@YAKK@Z" ) ; 62 READ Varable
    DB_Core\AcosFF= AIsFunction( 1 , "?AcosFF@@YAKM@Z" ) ; 64 ACOS Value
    DB_Core\AsinFF= AIsFunction( 1 , "?AsinFF@@YAKM@Z" ) ; 65 ASIN Value
    DB_Core\AtanFF= AIsFunction( 1 , "?AtanFF@@YAKM@Z" ) ; 66 ATAN Value
    DB_Core\Atan2FFF= AIsFunction( 1 , "?Atan2FFF@@YAKMM@Z" ) ; 67 ATANFULL Distance X, Distance Y
    DB_Core\SinFF= AIsFunction( 1 , "?SinFF@@YAKM@Z" ) ; 68 SIN Value
    DB_Core\TanFF= AIsFunction( 1 , "?TanFF@@YAKM@Z" ) ; 69 TAN Value
    DB_Core\HcosFF= AIsFunction( 1 , "?HcosFF@@YAKM@Z" ) ; 70 HCOS Value
    DB_Core\HsinFF= AIsFunction( 1 , "?HsinFF@@YAKM@Z" ) ; 71 HSIN Value
    DB_Core\HtanFF= AIsFunction( 1 , "?HtanFF@@YAKM@Z" ) ; 72 HTAN Value
    DB_Core\SqrtFF= AIsFunction( 1 , "?SqrtFF@@YAKM@Z" ) ; 73 SQRT Value
    DB_Core\Randomize= AIsFunction( 1 , "?Randomize@@YAXH@Z" ) ; 74 RANDOMIZE Seed Value
    DB_Core\AbsFF= AIsFunction( 1 , "?AbsFF@@YAKM@Z" ) ; 75 ABS Value
    DB_Core\Cl= AIsFunction( 1 , "?Cl$@@YAKK@Z" ) ; 76 CL$ 
    DB_Core\GetDate= AIsFunction( 1 , "?GetDate$@@YAKK@Z" ) ; 77 GET DATE$ 
    DB_Core\GetTime= AIsFunction( 1 , "?GetTime$@@YAKK@Z" ) ; 78 GET TIME$ 
    DB_Core\IntLF= AIsFunction( 1 , "?IntLF@@YAKM@Z" ) ; 79 INT Value
    DB_Core\SleepL= AIsFunction( 1 , "?SleepL@@YAXH@Z" ) ; 80 SLEEP Number
    DB_Core\WaitForKey= AIsFunction( 1 , "?WaitForKey@@YAXXZ" ) ; 81 WAIT KEY 
    DB_Core\WaitForKey1= AIsFunction( 1 , "?WaitForKey@@YAXXZ" ) ; 82 SUSPEND FOR KEY 
    DB_Core\WaitForMouse= AIsFunction( 1 , "?WaitForMouse@@YAXXZ" ) ; 83 WAIT MOUSE 
    DB_Core\WaitForMouse1= AIsFunction( 1 , "?WaitForMouse@@YAXXZ" ) ; 84 SUSPEND FOR MOUSE 
    DB_Core\SleepL1= AIsFunction( 1 , "?SleepL@@YAXH@Z" ) ; 85 WAIT 
    DB_Core\ExpFF= AIsFunction( 1 , "?ExpFF@@YAKM@Z" ) ; 87 EXP Value
    DB_Core\SaveArray= AIsFunction( 1 , "?SaveArray@@YAXPADK@Z" ) ; 90 SAVE ARRAY Filename, Array Name(0)
    DB_Core\LoadArray= AIsFunction( 1 , "?LoadArray@@YAXPADK@Z" ) ; 91 LOAD ARRAY Filename, Array Name(0)
    DB_Core\ReadL= AIsFunction( 1 , "?ReadL@@YAKXZ" ) ; 93 READ Value
    DB_Core\ReadF= AIsFunction( 1 , "?ReadF@@YAKXZ" ) ; 94 READ Value
    DB_Core\ReadB= AIsFunction( 1 , "?ReadB@@YAEXZ" ) ; 95 READ Value
    DB_Core\ReadB1= AIsFunction( 1 , "?ReadB@@YAEXZ" ) ; 96 READ Variable
    DB_Core\ReadW= AIsFunction( 1 , "?ReadW@@YAGXZ" ) ; 97 READ Variable
    DB_Core\ReadD= AIsFunction( 1 , "?ReadD@@YAKXZ" ) ; 98 READ Variable
    DB_Core\FastSync= AIsFunction( 1 , "?FastSync@@YAXXZ" ) ; 99 FASTSYNC 
    DB_Core\PrintR1= AIsFunction( 1 , "?PrintR@@YAX_J@Z" ) ; 100 PRINT 
    DB_Core\PrintCR1= AIsFunction( 1 , "?PrintCR@@YAX_J@Z" ) ; 101 PRINTC 
    DB_Core\CurveValueFFFF= AIsFunction( 1 , "?CurveValueFFFF@@YAKMMM@Z" ) ; 102 CURVEVALUE Destination Value, Current Value, Speed Value
    DB_Core\WrapValueFF= AIsFunction( 1 , "?WrapValueFF@@YAKM@Z" ) ; 103 WRAPVALUE Angle Value
    DB_Core\NewXValueFFFF= AIsFunction( 1 , "?NewXValueFFFF@@YAKMMM@Z" ) ; 104 NEWXVALUE Current X Value, Angle Value, Step Value
    DB_Core\NewYValueFFFF= AIsFunction( 1 , "?NewYValueFFFF@@YAKMMM@Z" ) ; 105 NEWYVALUE Current Y Value, Angle Value, Step Value
    DB_Core\NewZValueFFFF= AIsFunction( 1 , "?NewZValueFFFF@@YAKMMM@Z" ) ; 106 NEWZVALUE Current Z Value, Angle Value, Step Value
    DB_Core\CurveAngleFFFF= AIsFunction( 1 , "?CurveAngleFFFF@@YAKMMM@Z" ) ; 107 CURVEANGLE Destination Value, Current Value, Speed Value
    DB_Core\ArrayIndexToBottom= AIsFunction( 1 , "?ArrayIndexToBottom@@YAXK@Z" ) ; 109 ARRAY INDEX TO BOTTOM Array Name(0)
    DB_Core\ArrayIndexToTop= AIsFunction( 1 , "?ArrayIndexToTop@@YAXK@Z" ) ; 110 ARRAY INDEX TO TOP Array Name(0)
    DB_Core\ArrayIndexValid= AIsFunction( 1 , "?ArrayIndexValid@@YAKK@Z" ) ; 111 ARRAY INDEX VALID Array Name(0)
    DB_Core\NextArrayIndex= AIsFunction( 1 , "?NextArrayIndex@@YAXK@Z" ) ; 112 NEXT ARRAY INDEX Array Name(0)
    DB_Core\PreviousArrayIndex= AIsFunction( 1 , "?PreviousArrayIndex@@YAXK@Z" ) ; 113 PREVIOUS ARRAY INDEX Array Name(0)
    DB_Core\ArrayCount= AIsFunction( 1 , "?ArrayCount@@YAKK@Z" ) ; 114 ARRAY COUNT Array Name(0)
    DB_Core\ArrayInsertAtBottom= AIsFunction( 1 , "?ArrayInsertAtBottom@@YAKK@Z" ) ; 115 ARRAY INSERT AT BOTTOM Array Name(0)
    DB_Core\ArrayInsertAtBottom1= AIsFunction( 1 , "?ArrayInsertAtBottom@@YAKKH@Z" ) ; 116 ARRAY INSERT AT BOTTOM Array Name(0), Index
    DB_Core\ArrayInsertAtTop= AIsFunction( 1 , "?ArrayInsertAtTop@@YAKK@Z" ) ; 117 ARRAY INSERT AT TOP Array Name(0)
    DB_Core\ArrayInsertAtTop1= AIsFunction( 1 , "?ArrayInsertAtTop@@YAKKH@Z" ) ; 118 ARRAY INSERT AT TOP Array Name(0), Index
    DB_Core\ArrayInsertAtElement= AIsFunction( 1 , "?ArrayInsertAtElement@@YAKKH@Z" ) ; 119 ARRAY INSERT AT ELEMENT Array Name(0), Index
    DB_Core\ArrayDeleteElement= AIsFunction( 1 , "?ArrayDeleteElement@@YAXK@Z" ) ; 120 ARRAY DELETE ELEMENT Array Name(0)
    DB_Core\ArrayDeleteElement1= AIsFunction( 1 , "?ArrayDeleteElement@@YAXKH@Z" ) ; 121 ARRAY DELETE ELEMENT Array Name(0), Index
    DB_Core\EmptyArray= AIsFunction( 1 , "?EmptyArray@@YAXK@Z" ) ; 122 EMPTY ARRAY Array Name(0)
    DB_Core\AddToQueue= AIsFunction( 1 , "?AddToQueue@@YAKK@Z" ) ; 123 ADD TO QUEUE Array Name(0)
    DB_Core\RemoveFromQueue= AIsFunction( 1 , "?RemoveFromQueue@@YAXK@Z" ) ; 124 REMOVE FROM QUEUE Array Name(0)
    DB_Core\PushToStack= AIsFunction( 1 , "?PushToStack@@YAKK@Z" ) ; 125 ADD TO STACK Array Name(0)
    DB_Core\PopFromStack= AIsFunction( 1 , "?PopFromStack@@YAXK@Z" ) ; 126 REMOVE FROM STACK Array Name(0)
    DB_Core\ArrayIndexToQueue= AIsFunction( 1 , "?ArrayIndexToQueue@@YAXK@Z" ) ; 127 ARRAY INDEX TO QUEUE Array Name(0)
    DB_Core\ArrayIndexToStack= AIsFunction( 1 , "?ArrayIndexToStack@@YAXK@Z" ) ; 128 ARRAY INDEX TO STACK Array Name(0)
    DB_Core\DrawToBack= AIsFunction( 1 , "?DrawToBack@@YAXXZ" ) ; 129 DRAW TO BACK 
    DB_Core\DrawToFront= AIsFunction( 1 , "?DrawToFront@@YAXXZ" ) ; 130 DRAW TO FRONT 
    DB_Core\DrawSpritesFirst= AIsFunction( 1 , "?DrawSpritesFirst@@YAXXZ" ) ; 131 DRAW SPRITES FIRST 
    DB_Core\DrawSpritesLast= AIsFunction( 1 , "?DrawSpritesLast@@YAXXZ" ) ; 132 DRAW SPRITES LAST 
    DB_Core\FillByteMemory= AIsFunction( 1 , "?FillByteMemory@@YAXKHH@Z" ) ; 133 FILL MEMORY Memory Address, FillByte, Size In Bytes
    DB_Core\CopyByteMemory= AIsFunction( 1 , "?CopyByteMemory@@YAXKKH@Z" ) ; 134 COPY MEMORY Memory Destination, Memory Source, Size In Bytes
    DB_Core\MakeByteMemory= AIsFunction( 1 , "?MakeByteMemory@@YAKH@Z" ) ; 135 MAKE MEMORY Size In Bytes
    DB_Core\DeleteByteMemory= AIsFunction( 1 , "?DeleteByteMemory@@YAXK@Z" ) ; 136 DELETE MEMORY Memory Address
    DB_Core\Break= AIsFunction( 1 , "?Break@@YAXXZ" ) ; 137 BREAK 
    DB_Core\BreakS= AIsFunction( 1 , "?BreakS@@YAXK@Z" ) ; 138 BREAK Debug String
    DB_Core\Restore= AIsFunction( 1 , "?Restore@@YAXXZ" ) ; 139 RESTORE 
    DB_Core\FreeStringSS= AIsFunction( 1 , "?FreeStringSS@@YAKK@Z" ) ; 140 FREE STRING 
    DB_Core\AlwaysActiveOn= AIsFunction( 1 , "?AlwaysActiveOn@@YAXXZ" ) ; 141 ALWAYS ACTIVE ON 
    DB_Core\AlwaysActiveOff= AIsFunction( 1 , "?AlwaysActiveOff@@YAXXZ" ) ; 142 ALWAYS ACTIVE OFF 
    DB_Core\PerformanceTimer= AIsFunction( 1 , "?PerformanceTimer@@YA_JXZ" ) ; 143 PERFTIMER 
    CloseLibrary( 1 )
   Else
    SUCCESS.l = 0
   Endif
  ProcedureReturn SUCCESS
 EndProcedure

; IDE Options = PureBasic 4.10 Beta 2 (Windows - x86)
; CursorPosition = 108
; FirstLine = 66
; Folding = -