; DarkBasic Professional RC2PBIncludes Ver 1.1 File - COMMANDS INITIALIZING
; By Frederic Cordier - 07.02.13
;
Procedure.l CheckBasic3D()
  SUCCESS.l = 1
  If OpenLibrary( 1, "DBProBasic3DDebug.dll")
    DB_Basic3D\Load= AIsFunction( 1 , "?Load@@YAXKH@Z" ) ; 1 LOAD OBJECT Filename, Object Number
    DB_Basic3D\Rotate= AIsFunction( 1 , "?Rotate@@YAXHMMM@Z" ) ; 2 ROTATE OBJECT Object Number, XAngle, YAngle, ZAngle
    DB_Basic3D\Loop= AIsFunction( 1 , "?Loop@@YAXH@Z" ) ; 3 LOOP OBJECT Object Number
    DB_Basic3D\AddLimb= AIsFunction( 1 , "?AddLimb@@YAXHHH@Z" ) ; 4 ADD LIMB Object Number, Limb Number, Mesh Number
    DB_Basic3D\Append= AIsFunction( 1 , "?Append@@YAXKHH@Z" ) ; 5 APPEND OBJECT Filename, Object Number, Start Frame
    DB_Basic3D\AppendAnimation= AIsFunction( 1 , "?AppendAnimation@@YAXHK@Z" ) ; 6 APPEND OBJECT ANIMATION Object Number, Filename
    DB_Basic3D\LoadEffectEx= AIsFunction( 1 , "?LoadEffectEx@@YAXKHHH@Z" ) ; 7 LOAD EFFECT Filename, Effect Number, Texture Flag, DoNotGenerateExtraData
    DB_Basic3D\ChangeMesh= AIsFunction( 1 , "?ChangeMesh@@YAXHHH@Z" ) ; 8 CHANGE MESH Object Number, Limb Number, Mesh Number
    DB_Basic3D\ClearAllKeyFrames= AIsFunction( 1 , "?ClearAllKeyFrames@@YAXH@Z" ) ; 9 CLEAR ALL OBJECT KEYFRAMES Object Number
    DB_Basic3D\ClearKeyFrame= AIsFunction( 1 , "?ClearKeyFrame@@YAXHH@Z" ) ; 10 CLEAR OBJECT KEYFRAME Object Number, Keyframe
    DB_Basic3D\CalculateObjectBounds= AIsFunction( 1 , "?CalculateObjectBounds@@YAXH@Z" ) ; 11 CALCULATE OBJECT BOUNDS 
    DB_Basic3D\Color= AIsFunction( 1 , "?Color@@YAXHK@Z" ) ; 12 COLOR OBJECT Object Number, Color Value
    DB_Basic3D\ColorLimb= AIsFunction( 1 , "?ColorLimb@@YAXHHK@Z" ) ; 13 COLOR LIMB Object Number, Limb Number, Color Value
    DB_Basic3D\DeleteCollisionBox= AIsFunction( 1 , "?DeleteCollisionBox@@YAXH@Z" ) ; 14 DELETE OBJECT COLLISION BOX Object Number
    DB_Basic3D\DeleteEx= AIsFunction( 1 , "?DeleteEx@@YAXH@Z" ) ; 15 DELETE OBJECT Object Number
    DB_Basic3D\DeleteMesh= AIsFunction( 1 , "?DeleteMesh@@YAXH@Z" ) ; 16 DELETE MESH Mesh Number
    DB_Basic3D\SetMask= AIsFunction( 1 , "?SetMask@@YAXHH@Z" ) ; 17 SET OBJECT MASK Object Number, Camera Mask Bits
    DB_Basic3D\DisableZDepth= AIsFunction( 1 , "?DisableZDepth@@YAXH@Z" ) ; 19 DISABLE OBJECT ZDEPTH Object Number
    DB_Basic3D\EnableZDepth= AIsFunction( 1 , "?EnableZDepth@@YAXH@Z" ) ; 21 ENABLE OBJECT ZDEPTH Object Number
    DB_Basic3D\Fade= AIsFunction( 1 , "?Fade@@YAXHM@Z" ) ; 22 FADE OBJECT Object Number, Fade Value
    DB_Basic3D\FixPivot= AIsFunction( 1 , "?FixPivot@@YAXH@Z" ) ; 23 FIX OBJECT PIVOT Object Number
    DB_Basic3D\SetToObjectOrientation= AIsFunction( 1 , "?SetToObjectOrientation@@YAXHHH@Z" ) ; 24 SET OBJECT TO OBJECT ORIENTATION Object Number, Second Object, Flag
    DB_Basic3D\GetAlphaBlending= AIsFunction( 1 , "?GetAlphaBlending@@YAHXZ" ) ; 25 ALPHABLENDING AVAILABLE 
    DB_Basic3D\GetNumberOfFrames= AIsFunction( 1 , "?GetNumberOfFrames@@YAHH@Z" ) ; 26 TOTAL OBJECT FRAMES Object Number
    DB_Basic3D\GetBlending= AIsFunction( 1 , "?GetBlending@@YAHXZ" ) ; 27 FILTERING AVAILABLE 
    DB_Basic3D\GetCollision= AIsFunction( 1 , "?GetCollision@@YAHHH@Z" ) ; 28 OBJECT COLLISION ObjectA Number, ObjectB Number
    DB_Basic3D\GetCollisionX= AIsFunction( 1 , "?GetCollisionX@@YAKXZ" ) ; 29 GET OBJECT COLLISION X 
    DB_Basic3D\GetCollisionY= AIsFunction( 1 , "?GetCollisionY@@YAKXZ" ) ; 30 GET OBJECT COLLISION Y 
    DB_Basic3D\GetCollisionZ= AIsFunction( 1 , "?GetCollisionZ@@YAKXZ" ) ; 31 GET OBJECT COLLISION Z 
    DB_Basic3D\GetExist= AIsFunction( 1 , "?GetExist@@YAHH@Z" ) ; 32 OBJECT EXIST Object Number
    DB_Basic3D\GetFog= AIsFunction( 1 , "?GetFog@@YAHXZ" ) ; 33 FOG AVAILABLE 
    DB_Basic3D\GetFrame= AIsFunction( 1 , "?GetFrame@@YAKH@Z" ) ; 34 OBJECT FRAME Object Number
    DB_Basic3D\GetHit= AIsFunction( 1 , "?GetHit@@YAHHH@Z" ) ; 35 OBJECT HIT ObjectA Number, ObjectB Number
    DB_Basic3D\GetInScreen= AIsFunction( 1 , "?GetInScreen@@YAHH@Z" ) ; 36 OBJECT IN SCREEN Object Number
    DB_Basic3D\GetInterpolation= AIsFunction( 1 , "?GetInterpolation@@YAKH@Z" ) ; 37 OBJECT INTERPOLATION Object Number
    DB_Basic3D\GetLimbAngleX= AIsFunction( 1 , "?GetLimbAngleX@@YAKHH@Z" ) ; 38 LIMB ANGLE X Object Number, Limb Number
    DB_Basic3D\GetLimbAngleY= AIsFunction( 1 , "?GetLimbAngleY@@YAKHH@Z" ) ; 39 LIMB ANGLE Y Object Number, Limb Number
    DB_Basic3D\GetLimbAngleZ= AIsFunction( 1 , "?GetLimbAngleZ@@YAKHH@Z" ) ; 40 LIMB ANGLE Z Object Number, Limb Number
    DB_Basic3D\GetLimbExist= AIsFunction( 1 , "?GetLimbExist@@YAHHH@Z" ) ; 41 LIMB EXIST Object Number, Limb Number
    DB_Basic3D\GetLimbName= AIsFunction( 1 , "?GetLimbName@@YAKKHH@Z" ) ; 42 LIMB NAME$ Object Number, Limb Number
    DB_Basic3D\GetLimbOffsetX= AIsFunction( 1 , "?GetLimbOffsetX@@YAKHH@Z" ) ; 43 LIMB OFFSET X Object Number, Limb Number
    DB_Basic3D\GetLimbOffsetY= AIsFunction( 1 , "?GetLimbOffsetY@@YAKHH@Z" ) ; 44 LIMB OFFSET Y Object Number, Limb Number
    DB_Basic3D\GetLimbOffsetZ= AIsFunction( 1 , "?GetLimbOffsetZ@@YAKHH@Z" ) ; 45 LIMB OFFSET Z Object Number, Limb Number
    DB_Basic3D\GetLimbScaleX= AIsFunction( 1 , "?GetLimbScaleX@@YAKHH@Z" ) ; 46 LIMB SCALE X Object Number, Limb Number
    DB_Basic3D\GetLimbScaleY= AIsFunction( 1 , "?GetLimbScaleY@@YAKHH@Z" ) ; 47 LIMB SCALE Y Object Number, Limb Number
    DB_Basic3D\GetLimbScaleZ= AIsFunction( 1 , "?GetLimbScaleZ@@YAKHH@Z" ) ; 48 LIMB SCALE Z Object Number, Limb Number
    DB_Basic3D\GetLimbTextureName= AIsFunction( 1 , "?GetLimbTextureName@@YAKKHH@Z" ) ; 49 LIMB TEXTURE NAME Object Number, Limb Number
    DB_Basic3D\GetLimbTexture= AIsFunction( 1 , "?GetLimbTexture@@YAHHH@Z" ) ; 50 LIMB TEXTURE Object Number, Limb Number
    DB_Basic3D\GetLimbVisible= AIsFunction( 1 , "?GetLimbVisible@@YAHHH@Z" ) ; 51 LIMB VISIBLE Object Number, Limb Number
    DB_Basic3D\GetLimbXDirection= AIsFunction( 1 , "?GetLimbXDirection@@YAKHH@Z" ) ; 52 LIMB DIRECTION X Object Number, Limb Number
    DB_Basic3D\GetLimbYDirection= AIsFunction( 1 , "?GetLimbYDirection@@YAKHH@Z" ) ; 53 LIMB DIRECTION Y Object Number, Limb Number
    DB_Basic3D\GetLimbZDirection= AIsFunction( 1 , "?GetLimbZDirection@@YAKHH@Z" ) ; 54 LIMB DIRECTION Z Object Number, Limb Number
    DB_Basic3D\GetLimbXPosition= AIsFunction( 1 , "?GetLimbXPosition@@YAKHH@Z" ) ; 55 LIMB POSITION X Object Number, Limb Number
    DB_Basic3D\GetLimbYPosition= AIsFunction( 1 , "?GetLimbYPosition@@YAKHH@Z" ) ; 56 LIMB POSITION Y Object Number, Limb Number
    DB_Basic3D\GetLimbZPosition= AIsFunction( 1 , "?GetLimbZPosition@@YAKHH@Z" ) ; 57 LIMB POSITION Z Object Number, Limb Number
    DB_Basic3D\GetLooping= AIsFunction( 1 , "?GetLooping@@YAHH@Z" ) ; 58 OBJECT LOOPING Object Number
    DB_Basic3D\GetMeshExist= AIsFunction( 1 , "?GetMeshExist@@YAHH@Z" ) ; 59 MESH EXIST Mesh Number
    DB_Basic3D\GetPlaying= AIsFunction( 1 , "?GetPlaying@@YAHH@Z" ) ; 60 OBJECT PLAYING Object Number
    DB_Basic3D\GetScreenX= AIsFunction( 1 , "?GetScreenX@@YAHH@Z" ) ; 61 OBJECT SCREEN X Object Number
    DB_Basic3D\GetScreenY= AIsFunction( 1 , "?GetScreenY@@YAHH@Z" ) ; 62 OBJECT SCREEN Y Object Number
    DB_Basic3D\GetSize= AIsFunction( 1 , "?GetSize@@YAKH@Z" ) ; 63 OBJECT SIZE Object Number
    DB_Basic3D\GetSpeed= AIsFunction( 1 , "?GetSpeed@@YAKH@Z" ) ; 64 OBJECT SPEED Object Number
    DB_Basic3D\GetStaticLineOfSightX= AIsFunction( 1 , "?GetStaticLineOfSightX@@YAKXZ" ) ; 65 STATIC LINE OF SIGHT X 
    DB_Basic3D\GetStaticLineOfSightY= AIsFunction( 1 , "?GetStaticLineOfSightY@@YAKXZ" ) ; 66 STATIC LINE OF SIGHT Y 
    DB_Basic3D\GetStaticLineOfSightZ= AIsFunction( 1 , "?GetStaticLineOfSightZ@@YAKXZ" ) ; 67 STATIC LINE OF SIGHT Z 
    DB_Basic3D\GetVisible= AIsFunction( 1 , "?GetVisible@@YAHH@Z" ) ; 68 OBJECT VISIBLE Object Number
    DB_Basic3D\GetXPositionEx= AIsFunction( 1 , "?GetXPositionEx@@YAKH@Z" ) ; 69 OBJECT POSITION X Object Number
    DB_Basic3D\GetYPositionEx= AIsFunction( 1 , "?GetYPositionEx@@YAKH@Z" ) ; 70 OBJECT POSITION Y Object Number
    DB_Basic3D\GetZPositionEx= AIsFunction( 1 , "?GetZPositionEx@@YAKH@Z" ) ; 71 OBJECT POSITION Z Object Number
    DB_Basic3D\GetXSize= AIsFunction( 1 , "?GetXSize@@YAKH@Z" ) ; 72 OBJECT SIZE X Object Number
    DB_Basic3D\GetYSize= AIsFunction( 1 , "?GetYSize@@YAKH@Z" ) ; 73 OBJECT SIZE Y Object Number
    DB_Basic3D\GetZSize= AIsFunction( 1 , "?GetZSize@@YAKH@Z" ) ; 74 OBJECT SIZE Z Object Number
    DB_Basic3D\GetXRotationEx= AIsFunction( 1 , "?GetXRotationEx@@YAKH@Z" ) ; 75 OBJECT ANGLE X Object Number
    DB_Basic3D\GetYRotationEx= AIsFunction( 1 , "?GetYRotationEx@@YAKH@Z" ) ; 76 OBJECT ANGLE Y Object Number
    DB_Basic3D\GetZRotationEx= AIsFunction( 1 , "?GetZRotationEx@@YAKH@Z" ) ; 77 OBJECT ANGLE Z Object Number
    DB_Basic3D\GhostOff= AIsFunction( 1 , "?GhostOff@@YAXH@Z" ) ; 78 GHOST OBJECT OFF Object Number
    DB_Basic3D\GhostOn= AIsFunction( 1 , "?GhostOn@@YAXH@Z" ) ; 79 GHOST OBJECT ON Object Number
    DB_Basic3D\GhostOn1= AIsFunction( 1 , "?GhostOn@@YAXHH@Z" ) ; 80 GHOST OBJECT ON Object Number, Ghost Effect
    DB_Basic3D\GlueToLimb= AIsFunction( 1 , "?GlueToLimb@@YAXHHH@Z" ) ; 81 GLUE OBJECT TO LIMB Object Number, Second Object, Limb Number
    DB_Basic3D\Hide= AIsFunction( 1 , "?Hide@@YAXH@Z" ) ; 82 HIDE OBJECT Object Number
    DB_Basic3D\HideLimb= AIsFunction( 1 , "?HideLimb@@YAXHH@Z" ) ; 83 HIDE LIMB Object Number, Limb Number
    DB_Basic3D\LinkLimb= AIsFunction( 1 , "?LinkLimb@@YAXHHH@Z" ) ; 84 LINK LIMB Object Number, Limb Parent, Limb Child
    DB_Basic3D\LoadMesh= AIsFunction( 1 , "?LoadMesh@@YAXKH@Z" ) ; 85 LOAD MESH Filename, Mesh Number
    DB_Basic3D\LockOff= AIsFunction( 1 , "?LockOff@@YAXH@Z" ) ; 87 LOCK OBJECT OFF Object Number
    DB_Basic3D\LockOn= AIsFunction( 1 , "?LockOn@@YAXH@Z" ) ; 88 LOCK OBJECT ON Object Number
    DB_Basic3D\Loop1= AIsFunction( 1 , "?Loop@@YAXHH@Z" ) ; 89 LOOP OBJECT Object Number, Start Frame
    DB_Basic3D\Loop2= AIsFunction( 1 , "?Loop@@YAXHHH@Z" ) ; 90 LOOP OBJECT Object Number, Start Frame, End Frame
    DB_Basic3D\MakeBox= AIsFunction( 1 , "?MakeBox@@YAXHMMM@Z" ) ; 91 MAKE OBJECT BOX Object Number, Width, Height, Depth
    DB_Basic3D\MakeCollisionBox= AIsFunction( 1 , "?MakeCollisionBox@@YAXHMMMMMMH@Z" ) ; 92 MAKE OBJECT COLLISION BOX Object Number, X1, Y1, Z1, X2, Y2, Z2, Collision Flag
    DB_Basic3D\MakeCone= AIsFunction( 1 , "?MakeCone@@YAXHM@Z" ) ; 93 MAKE OBJECT CONE Object Number, Size
    DB_Basic3D\MakeCube= AIsFunction( 1 , "?MakeCube@@YAXHM@Z" ) ; 94 MAKE OBJECT CUBE Object Number, Size
    DB_Basic3D\MakeCylinder= AIsFunction( 1 , "?MakeCylinder@@YAXHM@Z" ) ; 95 MAKE OBJECT CYLINDER Object Number, Size
    DB_Basic3D\MakeMeshFromObject= AIsFunction( 1 , "?MakeMeshFromObject@@YAXHH@Z" ) ; 96 MAKE MESH FROM OBJECT Mesh Number, Object Number
    DB_Basic3D\MakeObjectFromLimb= AIsFunction( 1 , "?MakeObjectFromLimb@@YAXHHH@Z" ) ; 98 MAKE OBJECT FROM LIMB Object Number, Second Object, Limb Number
    DB_Basic3D\MakePlane= AIsFunction( 1 , "?MakePlane@@YAXHMM@Z" ) ; 99 MAKE OBJECT PLAIN Object Number, Width, Height
    DB_Basic3D\MakeSphere= AIsFunction( 1 , "?MakeSphere@@YAXHM@Z" ) ; 100 MAKE OBJECT SPHERE Object Number, Size
    DB_Basic3D\MakeTriangle= AIsFunction( 1 , "?MakeTriangle@@YAXHMMMMMMMMM@Z" ) ; 101 MAKE OBJECT TRIANGLE Object Number, X1, Y1, Z1, X2, Y2, Z2, X3, Y3, Z3
    DB_Basic3D\Move= AIsFunction( 1 , "?Move@@YAXHM@Z" ) ; 102 MOVE OBJECT Object Number, Speed
    DB_Basic3D\OffsetLimb= AIsFunction( 1 , "?OffsetLimb@@YAXHHMMM@Z" ) ; 103 OFFSET LIMB Object Number, Limb Number, X, Y, Z
    DB_Basic3D\PerformCheckListForLimbs= AIsFunction( 1 , "?PerformCheckListForLimbs@@YAXH@Z" ) ; 104 PERFORM CHECKLIST FOR OBJECT LIMBS Object Number
    DB_Basic3D\PitchDown= AIsFunction( 1 , "?PitchDown@@YAXHM@Z" ) ; 105 PITCH OBJECT DOWN Object Number, Value
    DB_Basic3D\PitchUp= AIsFunction( 1 , "?PitchUp@@YAXHM@Z" ) ; 106 PITCH OBJECT UP Object Number, Value
    DB_Basic3D\Play= AIsFunction( 1 , "?Play@@YAXH@Z" ) ; 107 PLAY OBJECT Object Number
    DB_Basic3D\Play1= AIsFunction( 1 , "?Play@@YAXHH@Z" ) ; 108 PLAY OBJECT Object Number, Start Frame
    DB_Basic3D\Play2= AIsFunction( 1 , "?Play@@YAXHHH@Z" ) ; 109 PLAY OBJECT Object Number, Start Frame, End Frame
    DB_Basic3D\Point= AIsFunction( 1 , "?Point@@YAXHMMM@Z" ) ; 110 POINT OBJECT Object Number, X, Y, Z
    DB_Basic3D\Position= AIsFunction( 1 , "?Position@@YAXHMMM@Z" ) ; 111 POSITION OBJECT Object Number, X, Y, Z
    DB_Basic3D\RollLeft= AIsFunction( 1 , "?RollLeft@@YAXHM@Z" ) ; 112 ROLL OBJECT LEFT Object Number, Value
    DB_Basic3D\RollRight= AIsFunction( 1 , "?RollRight@@YAXHM@Z" ) ; 113 ROLL OBJECT RIGHT Object Number, Value
    DB_Basic3D\MakePlane1= AIsFunction( 1 , "?MakePlane@@YAXHMMH@Z" ) ; 114 MAKE OBJECT PLAIN Object Number, Width, Height
    DB_Basic3D\RotateLimb= AIsFunction( 1 , "?RotateLimb@@YAXHHMMM@Z" ) ; 115 ROTATE LIMB Object Number, Limb Number, XAngle, YAngle, ZAngle
    DB_Basic3D\SaveAnimation= AIsFunction( 1 , "?SaveAnimation@@YAXHK@Z" ) ; 116 SAVE OBJECT ANIMATION Object Number, Filename
    DB_Basic3D\Scale= AIsFunction( 1 , "?Scale@@YAXHMMM@Z" ) ; 118 SCALE OBJECT Object Number, XSize, YSize, ZSize
    DB_Basic3D\ScaleLimb= AIsFunction( 1 , "?ScaleLimb@@YAXHHMMM@Z" ) ; 119 SCALE LIMB Object Number, Limb Number, XSize, YSize, ZSize
    DB_Basic3D\ScaleLimbTexture= AIsFunction( 1 , "?ScaleLimbTexture@@YAXHHMM@Z" ) ; 120 SCALE LIMB TEXTURE Object Number, Limb Number, UScale, VScale
    DB_Basic3D\ScaleTexture= AIsFunction( 1 , "?ScaleTexture@@YAXHMM@Z" ) ; 121 SCALE OBJECT TEXTURE Object Number, UScale, VScale
    DB_Basic3D\ScrollLimbTexture= AIsFunction( 1 , "?ScrollLimbTexture@@YAXHHMM@Z" ) ; 122 SCROLL LIMB TEXTURE Object Number, Limb Number, X, Y
    DB_Basic3D\ScrollTexture= AIsFunction( 1 , "?ScrollTexture@@YAXHMM@Z" ) ; 123 SCROLL OBJECT TEXTURE Object Number, X, Y
    DB_Basic3D\Set= AIsFunction( 1 , "?Set@@YAXHHHH@Z" ) ; 124 SET OBJECT Object Number, Wire, Transparent, Cull
    DB_Basic3D\Set1= AIsFunction( 1 , "?Set@@YAXHHHHH@Z" ) ; 125 SET OBJECT Object Number, Wire, Transparent, Cull, Filter
    DB_Basic3D\Set2= AIsFunction( 1 , "?Set@@YAXHHHHHH@Z" ) ; 126 SET OBJECT Object Number, Wire, Transparent, Cull, Filter, Light
    DB_Basic3D\Set3= AIsFunction( 1 , "?Set@@YAXHHHHHHH@Z" ) ; 127 SET OBJECT Object Number, Wire, Transparent, Cull, Filter, Light, Fog
    DB_Basic3D\Set4= AIsFunction( 1 , "?Set@@YAXHHHHHHHH@Z" ) ; 128 SET OBJECT Object Number, Wire, Transparent, Cull, Filter, Light, Fog, Ambient
    DB_Basic3D\SetCollisionOff= AIsFunction( 1 , "?SetCollisionOff@@YAXH@Z" ) ; 129 SET OBJECT COLLISION OFF Object Number
    DB_Basic3D\SetCollisionOn= AIsFunction( 1 , "?SetCollisionOn@@YAXH@Z" ) ; 130 SET OBJECT COLLISION ON Object Number
    DB_Basic3D\SetCollisionToBoxes= AIsFunction( 1 , "?SetCollisionToBoxes@@YAXH@Z" ) ; 131 SET OBJECT COLLISION TO BOXES Object Number
    DB_Basic3D\SetCollisionToPolygons= AIsFunction( 1 , "?SetCollisionToPolygons@@YAXH@Z" ) ; 132 SET OBJECT COLLISION TO POLYGONS Object Number
    DB_Basic3D\SetCollisionToSpheres= AIsFunction( 1 , "?SetCollisionToSpheres@@YAXH@Z" ) ; 133 SET OBJECT COLLISION TO SPHERES Object Number
    DB_Basic3D\SetFrameEx= AIsFunction( 1 , "?SetFrameEx@@YAXHM@Z" ) ; 134 SET OBJECT FRAME Object Number, Frame
    DB_Basic3D\SetGlobalCollisionOff= AIsFunction( 1 , "?SetGlobalCollisionOff@@YAXXZ" ) ; 135 SET GLOBAL COLLISION OFF 
    DB_Basic3D\SetGlobalCollisionOn= AIsFunction( 1 , "?SetGlobalCollisionOn@@YAXXZ" ) ; 136 SET GLOBAL COLLISION ON 
    DB_Basic3D\SetInterpolation= AIsFunction( 1 , "?SetInterpolation@@YAXHH@Z" ) ; 137 SET OBJECT INTERPOLATION Object Number, Interpolation
    DB_Basic3D\SetKeyFrame= AIsFunction( 1 , "?SetKeyFrame@@YAXHH@Z" ) ; 138 SET OBJECT KEYFRAME Object Number, Keyframe
    DB_Basic3D\SetMipmapMode= AIsFunction( 1 , "?SetMipmapMode@@YAXH@Z" ) ; 139 SET MIPMAP MODE Mipmap Mode
    DB_Basic3D\SetRotationXYZ= AIsFunction( 1 , "?SetRotationXYZ@@YAXH@Z" ) ; 141 SET OBJECT ROTATION XYZ Object Number
    DB_Basic3D\SetRotationZYX= AIsFunction( 1 , "?SetRotationZYX@@YAXH@Z" ) ; 142 SET OBJECT ROTATION ZYX Object Number
    DB_Basic3D\SetSpeed= AIsFunction( 1 , "?SetSpeed@@YAXHH@Z" ) ; 143 SET OBJECT SPEED Object Number, Speed
    DB_Basic3D\SetTexture= AIsFunction( 1 , "?SetTexture@@YAXHH@Z" ) ; 144 TEXTURE OBJECT Object Number, Image Number
    DB_Basic3D\SetTextureMode= AIsFunction( 1 , "?SetTextureMode@@YAXHHH@Z" ) ; 145 SET OBJECT TEXTURE Object Number, Texturing Mode, Mipmap Flag
    DB_Basic3D\SetToCameraOrientation= AIsFunction( 1 , "?SetToCameraOrientation@@YAXH@Z" ) ; 146 SET OBJECT TO CAMERA ORIENTATION Object Number
    DB_Basic3D\SetToObjectOrientation1= AIsFunction( 1 , "?SetToObjectOrientation@@YAXHH@Z" ) ; 147 SET OBJECT TO OBJECT ORIENTATION Object Number, Second Object
    DB_Basic3D\Show= AIsFunction( 1 , "?Show@@YAXH@Z" ) ; 148 SHOW OBJECT Object Number
    DB_Basic3D\ShowLimb= AIsFunction( 1 , "?ShowLimb@@YAXHH@Z" ) ; 149 SHOW LIMB Object Number, Limb Number
    DB_Basic3D\Stop= AIsFunction( 1 , "?Stop@@YAXH@Z" ) ; 150 STOP OBJECT Object Number
    DB_Basic3D\TextureLimb= AIsFunction( 1 , "?TextureLimb@@YAXHHH@Z" ) ; 151 TEXTURE LIMB Object Number, Limb Number, Image Number
    DB_Basic3D\TurnLeft= AIsFunction( 1 , "?TurnLeft@@YAXHM@Z" ) ; 152 TURN OBJECT LEFT Object Number, Value
    DB_Basic3D\TurnRight= AIsFunction( 1 , "?TurnRight@@YAXHM@Z" ) ; 153 TURN OBJECT RIGHT Object Number, Value
    DB_Basic3D\UnGlue= AIsFunction( 1 , "?UnGlue@@YAXH@Z" ) ; 154 UNGLUE OBJECT Object Number
    DB_Basic3D\XRotate= AIsFunction( 1 , "?XRotate@@YAXHM@Z" ) ; 155 XROTATE OBJECT Object Number, XAngle
    DB_Basic3D\YRotate= AIsFunction( 1 , "?YRotate@@YAXHM@Z" ) ; 156 YROTATE OBJECT Object Number, YAngle
    DB_Basic3D\ZRotate= AIsFunction( 1 , "?ZRotate@@YAXHM@Z" ) ; 157 ZROTATE OBJECT Object Number, ZAngle
    DB_Basic3D\MakeObject= AIsFunction( 1 , "?MakeObject@@YAXHHH@Z" ) ; 158 MAKE OBJECT Object Number, Mesh Index, Image Number
    DB_Basic3D\SetBumpMap= AIsFunction( 1 , "?SetBumpMap@@YAXHH@Z" ) ; 166 SET BUMP MAPPING ON Object Number, Image Number
    DB_Basic3D\SetCartoonShadingOn= AIsFunction( 1 , "?SetCartoonShadingOn@@YAXHHH@Z" ) ; 167 SET CARTOON SHADING ON Object Number, Shade Image, Edge Image
    DB_Basic3D\SetSphereMap= AIsFunction( 1 , "?SetSphereMap@@YAXHH@Z" ) ; 168 SET SPHERE MAPPING ON Object Number, Image Number
    DB_Basic3D\GetSizeEx= AIsFunction( 1 , "?GetSizeEx@@YAKHH@Z" ) ; 171 OBJECT SIZE Object Number, Actual Size
    DB_Basic3D\GetLimbLink= AIsFunction( 1 , "?GetLimbLink@@YAHHH@Z" ) ; 172 CHECK LIMB LINK Object Number, Limb Number
    DB_Basic3D\GetObjectCollisionRadius= AIsFunction( 1 , "?GetObjectCollisionRadius@@YAKH@Z" ) ; 173 OBJECT COLLISION RADIUS Object Number
    DB_Basic3D\GetObjectCollisionCenterX= AIsFunction( 1 , "?GetObjectCollisionCenterX@@YAKH@Z" ) ; 174 OBJECT COLLISION CENTER X Object Number
    DB_Basic3D\GetObjectCollisionCenterY= AIsFunction( 1 , "?GetObjectCollisionCenterY@@YAKH@Z" ) ; 175 OBJECT COLLISION CENTER Y Object Number
    DB_Basic3D\GetObjectCollisionCenterZ= AIsFunction( 1 , "?GetObjectCollisionCenterZ@@YAKH@Z" ) ; 176 OBJECT COLLISION CENTER Z Object Number
    DB_Basic3D\Convert3DStoX= AIsFunction( 1 , "?Convert3DStoX@@YAXKK@Z" ) ; 177 3DS2X 3DS Filename, X Filename
    DB_Basic3D\FlushVideoMemory= AIsFunction( 1 , "?FlushVideoMemory@@YAXXZ" ) ; 178 FLUSH VIDEO MEMORY 
    DB_Basic3D\DisableTNL= AIsFunction( 1 , "?DisableTNL@@YAXXZ" ) ; 179 DISABLE TNL 
    DB_Basic3D\EnableTNL= AIsFunction( 1 , "?EnableTNL@@YAXXZ" ) ; 180 ENABLE TNL 
    DB_Basic3D\GetStatistic= AIsFunction( 1 , "?GetStatistic@@YAHH@Z" ) ; 181 STATISTIC Statistic Code
    DB_Basic3D\GetDrawPrimTLVertex= AIsFunction( 1 , "?GetDrawPrimTLVertex@@YAHXZ" ) ; 182 TNL AVAILABLE 
    DB_Basic3D\Clone= AIsFunction( 1 , "?Clone@@YAXHH@Z" ) ; 183 CLONE OBJECT Object Number, Source Object
    DB_Basic3D\CreateVertexShaderFromFile= AIsFunction( 1 , "?CreateVertexShaderFromFile@@YAXHK@Z" ) ; 184 CREATE VERTEX SHADER FROM FILE VertexShader Number, Shader Filename
    DB_Basic3D\MakeSphere1= AIsFunction( 1 , "?MakeSphere@@YAXHMHH@Z" ) ; 185 MAKE OBJECT SPHERE Object Number, Size, Rows, Columns
    DB_Basic3D\MoveDown= AIsFunction( 1 , "?MoveDown@@YAXHM@Z" ) ; 186 MOVE OBJECT DOWN Object Number, Value
    DB_Basic3D\MoveLeft= AIsFunction( 1 , "?MoveLeft@@YAXHM@Z" ) ; 187 MOVE OBJECT LEFT Object Number, Value
    DB_Basic3D\MoveRight= AIsFunction( 1 , "?MoveRight@@YAXHM@Z" ) ; 188 MOVE OBJECT RIGHT Object Number, Value
    DB_Basic3D\MoveUp= AIsFunction( 1 , "?MoveUp@@YAXHM@Z" ) ; 189 MOVE OBJECT UP Object Number, Value
    DB_Basic3D\SetAmbient= AIsFunction( 1 , "?SetAmbient@@YAXHH@Z" ) ; 190 SET OBJECT AMBIENT Object Number, Flag
    DB_Basic3D\SetCull= AIsFunction( 1 , "?SetCull@@YAXHH@Z" ) ; 192 SET OBJECT CULL Object Number, Flag
    DB_Basic3D\SetDetailMap= AIsFunction( 1 , "?SetDetailMap@@YAXHH@Z" ) ; 193 SET DETAIL MAPPING ON Object Number, Image Number
    DB_Basic3D\SetFilter= AIsFunction( 1 , "?SetFilter@@YAXHH@Z" ) ; 194 SET OBJECT FILTER Object Number, Flag
    DB_Basic3D\SetFog= AIsFunction( 1 , "?SetFog@@YAXHH@Z" ) ; 195 SET OBJECT FOG Object Number, Flag
    DB_Basic3D\SetLight= AIsFunction( 1 , "?SetLight@@YAXHH@Z" ) ; 196 SET OBJECT LIGHT Object Number, Flag
    DB_Basic3D\SetLightMap= AIsFunction( 1 , "?SetLightMap@@YAXHH@Z" ) ; 197 SET LIGHT MAPPING ON Object Number, Image Number
    DB_Basic3D\SetSphereRadius= AIsFunction( 1 , "?SetSphereRadius@@YAXHM@Z" ) ; 198 SET OBJECT RADIUS Object Number, Radius
    DB_Basic3D\SetTransparency= AIsFunction( 1 , "?SetTransparency@@YAXHH@Z" ) ; 199 SET OBJECT TRANSPARENCY Object Number, Flag
    DB_Basic3D\SetVertexShaderMatrix= AIsFunction( 1 , "?SetVertexShaderMatrix@@YAXHKHK@Z" ) ; 200 SET VERTEX SHADER MATRIX VertexShader Number, Constant, Matrix4, ConstantCount
    DB_Basic3D\SetVertexShaderOff= AIsFunction( 1 , "?SetVertexShaderOff@@YAXH@Z" ) ; 201 SET VERTEX SHADER OFF Object Number
    DB_Basic3D\SetVertexShaderOn= AIsFunction( 1 , "?SetVertexShaderOn@@YAXHH@Z" ) ; 202 SET VERTEX SHADER ON Object Number, VertexShader Number
    DB_Basic3D\SetVertexShaderStream= AIsFunction( 1 , "?SetVertexShaderStream@@YAXHHHH@Z" ) ; 203 SET VERTEX SHADER STREAM VertexShader Number, Position, Data, Datatype
    DB_Basic3D\SetVertexShaderStreamCount= AIsFunction( 1 , "?SetVertexShaderStreamCount@@YAXHH@Z" ) ; 204 SET VERTEX SHADER STREAMCOUNT VertexShader Number, Count
    DB_Basic3D\SetVertexShaderVector= AIsFunction( 1 , "?SetVertexShaderVector@@YAXHKHK@Z" ) ; 205 SET VERTEX SHADER VECTOR VertexShader Number, Constant, Vector3, ConstantCount
    DB_Basic3D\SetWireframe= AIsFunction( 1 , "?SetWireframe@@YAXHH@Z" ) ; 206 SET OBJECT WIREFRAME Object Number, Flag
    DB_Basic3D\GetAlpha= AIsFunction( 1 , "?GetAlpha@@YAHXZ" ) ; 207 ALPHA AVAILABLE 
    DB_Basic3D\GetAlphaComparision= AIsFunction( 1 , "?GetAlphaComparision@@YAHXZ" ) ; 208 ALPHACOMPARISON AVAILABLE 
    DB_Basic3D\GetAnisotropicFiltering= AIsFunction( 1 , "?GetAnisotropicFiltering@@YAHXZ" ) ; 209 ANISTROPICFILTERING AVAILABLE 
    DB_Basic3D\GetAntiAliasEdges= AIsFunction( 1 , "?GetAntiAliasEdges@@YAHXZ" ) ; 210 ANTIALIAS AVAILABLE 
    DB_Basic3D\GetBlitSysOntoLocal= AIsFunction( 1 , "?GetBlitSysOntoLocal@@YAHXZ" ) ; 211 BLITSYSTOLOCAL AVAILABLE 
    DB_Basic3D\GetCalibrateGamma= AIsFunction( 1 , "?GetCalibrateGamma@@YAHXZ" ) ; 212 CALIBRATEGAMMA AVAILABLE 
    DB_Basic3D\GetClipAndScalePoints= AIsFunction( 1 , "?GetClipAndScalePoints@@YAHXZ" ) ; 213 CLIPANDSCALEPOINTS AVAILABLE 
    DB_Basic3D\GetClipTLVerts= AIsFunction( 1 , "?GetClipTLVerts@@YAHXZ" ) ; 214 CLIPTLVERTS AVAILABLE 
    DB_Basic3D\GetColorPerspective= AIsFunction( 1 , "?GetColorPerspective@@YAHXZ" ) ; 215 COLORPERSPECTIVE AVAILABLE 
    DB_Basic3D\GetColorWriteEnable= AIsFunction( 1 , "?GetColorWriteEnable@@YAHXZ" ) ; 216 COLORWRITEENABLE AVAILABLE 
    DB_Basic3D\GetCubeMap= AIsFunction( 1 , "?GetCubeMap@@YAHXZ" ) ; 217 CUBEMAP AVAILABLE 
    DB_Basic3D\GetCullCCW= AIsFunction( 1 , "?GetCullCCW@@YAHXZ" ) ; 218 CULLCCW AVAILABLE 
    DB_Basic3D\GetCullCW= AIsFunction( 1 , "?GetCullCW@@YAHXZ" ) ; 219 CULLCW AVAILABLE 
    DB_Basic3D\GetDeviceType= AIsFunction( 1 , "?GetDeviceType@@YAHXZ" ) ; 220 GET DEVICE TYPE 
    DB_Basic3D\GetDither= AIsFunction( 1 , "?GetDither@@YAHXZ" ) ; 221 DITHER AVAILABLE 
    DB_Basic3D\GetFogRange= AIsFunction( 1 , "?GetFogRange@@YAHXZ" ) ; 222 FOGRANGE AVAILABLE 
    DB_Basic3D\GetFogTable= AIsFunction( 1 , "?GetFogTable@@YAHXZ" ) ; 223 FOGTABLE AVAILABLE 
    DB_Basic3D\GetFogVertex= AIsFunction( 1 , "?GetFogVertex@@YAHXZ" ) ; 224 FOGVERTEX AVAILABLE 
    DB_Basic3D\GetFullScreenGamma= AIsFunction( 1 , "?GetFullScreenGamma@@YAHXZ" ) ; 225 FULLSCREENGAMMA AVAILABLE 
    DB_Basic3D\GetMaxLights= AIsFunction( 1 , "?GetMaxLights@@YAHXZ" ) ; 226 GET MAXIMUM LIGHTS 
    DB_Basic3D\GetMaxPixelShaderValue= AIsFunction( 1 , "?GetMaxPixelShaderValue@@YAKXZ" ) ; 227 GET MAXIMUM PIXEL SHADER VALUE 
    DB_Basic3D\ScaleTexture1= AIsFunction( 1 , "?ScaleTexture@@YAXHHMM@Z" ) ; 228 SCALE OBJECT TEXTURE Object Number, Stage, UScale, VScale
    DB_Basic3D\GetMaxTextureHeight= AIsFunction( 1 , "?GetMaxTextureHeight@@YAHXZ" ) ; 229 GET MAXIMUM TEXTURE HEIGHT 
    DB_Basic3D\GetMaxTextureWidth= AIsFunction( 1 , "?GetMaxTextureWidth@@YAHXZ" ) ; 230 GET MAXIMUM TEXTURE WIDTH 
    DB_Basic3D\GetMaxVertexShaderConstants= AIsFunction( 1 , "?GetMaxVertexShaderConstants@@YAHXZ" ) ; 231 GET MAXIMUM VERTEX SHADER CONSTANTS 
    DB_Basic3D\GetMaxVolumeExtent= AIsFunction( 1 , "?GetMaxVolumeExtent@@YAHXZ" ) ; 232 GET MAXIMUM VOLUME EXTENT 
    DB_Basic3D\GetMipCubeMap= AIsFunction( 1 , "?GetMipCubeMap@@YAHXZ" ) ; 233 MIPCUBEMAP AVAILABLE 
    DB_Basic3D\GetMipMap= AIsFunction( 1 , "?GetMipMap@@YAHXZ" ) ; 234 MIPMAP AVAILABLE 
    DB_Basic3D\GetMipMapLODBias= AIsFunction( 1 , "?GetMipMapLODBias@@YAHXZ" ) ; 235 MIPMAPLODBIAS AVAILABLE 
    DB_Basic3D\GetMipMapVolume= AIsFunction( 1 , "?GetMipMapVolume@@YAHXZ" ) ; 236 MIPMAPVOLUME AVAILABLE 
    DB_Basic3D\GetNonPowerOf2Textures= AIsFunction( 1 , "?GetNonPowerOf2Textures@@YAHXZ" ) ; 237 NONPOWTEXTURES AVAILABLE 
    DB_Basic3D\GetPerspective= AIsFunction( 1 , "?GetPerspective@@YAHXZ" ) ; 238 PERSPECTIVETEXTURES AVAILABLE 
    DB_Basic3D\GetPixelShaderVersion= AIsFunction( 1 , "?GetPixelShaderVersion@@YAKXZ" ) ; 239 GET MAXIMUM PIXEL SHADER VERSION 
    DB_Basic3D\GetProjected= AIsFunction( 1 , "?GetProjected@@YAHXZ" ) ; 240 PROJECTEDTEXTURES AVAILABLE 
    DB_Basic3D\GetRenderAfterFlip= AIsFunction( 1 , "?GetRenderAfterFlip@@YAHXZ" ) ; 241 RENDERAFTERFLIP AVAILABLE 
    DB_Basic3D\GetRenderWindowed= AIsFunction( 1 , "?GetRenderWindowed@@YAHXZ" ) ; 242 RENDERWINDOWED AVAILABLE 
    DB_Basic3D\GetSeparateTextureMemories= AIsFunction( 1 , "?GetSeparateTextureMemories@@YAHXZ" ) ; 243 SEPERATETEXTUREMEMORIES AVAILABLE 
    DB_Basic3D\GetSquareOnly= AIsFunction( 1 , "?GetSquareOnly@@YAHXZ" ) ; 244 ONLYSQUARETEXTURES AVAILABLE 
    DB_Basic3D\GetTLVertexSystemMemory= AIsFunction( 1 , "?GetTLVertexSystemMemory@@YAHXZ" ) ; 245 TLVERTEXSYSTEMMEMORY AVAILABLE 
    DB_Basic3D\GetTLVertexVideoMemory= AIsFunction( 1 , "?GetTLVertexVideoMemory@@YAHXZ" ) ; 246 TLVERTEXVIDEOMEMORY AVAILABLE 
    DB_Basic3D\GetTextureNonLocalVideoMemory= AIsFunction( 1 , "?GetTextureNonLocalVideoMemory@@YAHXZ" ) ; 247 NONLOCALVIDEOMEMORY AVAILABLE 
    DB_Basic3D\GetTextureSystemMemory= AIsFunction( 1 , "?GetTextureSystemMemory@@YAHXZ" ) ; 248 TEXTURESYSTEMMEMORY AVAILABLE 
    DB_Basic3D\GetTextureVideoMemory= AIsFunction( 1 , "?GetTextureVideoMemory@@YAHXZ" ) ; 249 TEXTUREVIDEOMEMORY AVAILABLE 
    DB_Basic3D\GetVertexShaderVersion= AIsFunction( 1 , "?GetVertexShaderVersion@@YAKXZ" ) ; 250 GET MAXIMUM VERTEX SHADER VERSION 
    DB_Basic3D\GetVolumeMap= AIsFunction( 1 , "?GetVolumeMap@@YAHXZ" ) ; 251 VOLUMEMAP AVAILABLE 
    DB_Basic3D\GetWBuffer= AIsFunction( 1 , "?GetWBuffer@@YAHXZ" ) ; 252 WBUFFER AVAILABLE 
    DB_Basic3D\GetWFog= AIsFunction( 1 , "?GetWFog@@YAHXZ" ) ; 253 WFOG AVAILABLE 
    DB_Basic3D\GetZBuffer= AIsFunction( 1 , "?GetZBuffer@@YAHXZ" ) ; 254 ZBUFFER AVAILABLE 
    DB_Basic3D\GetZFog= AIsFunction( 1 , "?GetZFog@@YAHXZ" ) ; 255 ZFOG AVAILABLE 
    DB_Basic3D\DeleteVertexShader= AIsFunction( 1 , "?DeleteVertexShader@@YAXH@Z" ) ; 256 DELETE VERTEX SHADER VertexShader Number
    DB_Basic3D\VertexShaderExist= AIsFunction( 1 , "?VertexShaderExist@@YAHH@Z" ) ; 257 VERTEX SHADER EXIST VertexShader Number
    DB_Basic3D\SetCubeMap= AIsFunction( 1 , "?SetCubeMap@@YAXHHHHHHH@Z" ) ; 258 SET CUBE MAPPING ON Object Number, Face1, Face2, Face3, Face4, Face5, Face6
    DB_Basic3D\SetBlendMap= AIsFunction( 1 , "?SetBlendMap@@YAXHHH@Z" ) ; 259 SET BLEND MAPPING ON Object Number, Image Number, Blend Mode
    DB_Basic3D\SaveMesh= AIsFunction( 1 , "?SaveMesh@@YAXKH@Z" ) ; 260 SAVE MESH Filename, Mesh Number
    DB_Basic3D\RemoveLimb= AIsFunction( 1 , "?RemoveLimb@@YAXHH@Z" ) ; 261 REMOVE LIMB Object Number, Limb Number
    DB_Basic3D\IntersectObject= AIsFunction( 1 , "?IntersectObject@@YAKHMMMMMM@Z" ) ; 262 INTERSECT OBJECT Object Number, X, Y, Z, ToX, ToY, ToZ
    DB_Basic3D\AutomaticObjectCollision= AIsFunction( 1 , "?AutomaticObjectCollision@@YAXHMH@Z" ) ; 263 AUTOMATIC OBJECT COLLISION Object Number, Radius, Response
    DB_Basic3D\AutomaticCameraCollision= AIsFunction( 1 , "?AutomaticCameraCollision@@YAXHMH@Z" ) ; 264 AUTOMATIC CAMERA COLLISION Camera Number, Radius, Response
    DB_Basic3D\SetRainbowRenderingOn= AIsFunction( 1 , "?SetRainbowRenderingOn@@YAXHH@Z" ) ; 265 SET RAINBOW SHADING ON Object Number, Rainbow Image
    DB_Basic3D\SetShadowOn= AIsFunction( 1 , "?SetShadowOn@@YAXH@Z" ) ; 266 SET SHADOW SHADING ON Object Number
    DB_Basic3D\SetReflectionOn= AIsFunction( 1 , "?SetReflectionOn@@YAXH@Z" ) ; 267 SET REFLECTION SHADING ON Object Number
    DB_Basic3D\CreatePixelShaderFromFile= AIsFunction( 1 , "?CreatePixelShaderFromFile@@YAXHK@Z" ) ; 268 CREATE PIXEL SHADER FROM FILE PixelShader Number, Shader Filename
    DB_Basic3D\SetPixelShaderOn= AIsFunction( 1 , "?SetPixelShaderOn@@YAXHH@Z" ) ; 269 SET PIXEL SHADER ON Object Number, PixelShader Number
    DB_Basic3D\SetPixelShaderOff= AIsFunction( 1 , "?SetPixelShaderOff@@YAXH@Z" ) ; 270 SET PIXEL SHADER OFF Object Number
    DB_Basic3D\DeletePixelShader= AIsFunction( 1 , "?DeletePixelShader@@YAXH@Z" ) ; 271 DELETE PIXEL SHADER PixelShader Number
    DB_Basic3D\SetPixelShaderTexture= AIsFunction( 1 , "?SetPixelShaderTexture@@YAXHHH@Z" ) ; 272 SET PIXEL SHADER TEXTURE PixelShader Number, Slot Number, Image Number
    DB_Basic3D\PixelShaderExist= AIsFunction( 1 , "?PixelShaderExist@@YAHH@Z" ) ; 273 PIXEL SHADER EXIST PixelShader Number
    DB_Basic3D\SetTextureMD3= AIsFunction( 1 , "?SetTextureMD3@@YAXHHHHHHH@Z" ) ; 274 SET TEXTURE MD3 Object Number, H0, H1, L0, L1, L2, U0
    DB_Basic3D\CloneMeshToNewFormat= AIsFunction( 1 , "?CloneMeshToNewFormat@@YAXHK@Z" ) ; 275 CONVERT OBJECT FVF Object Number, FVF Format
    DB_Basic3D\Save= AIsFunction( 1 , "?Save@@YAXKH@Z" ) ; 276 SAVE OBJECT Filename, Object Number
    DB_Basic3D\HideBounds= AIsFunction( 1 , "?HideBounds@@YAXH@Z" ) ; 277 HIDE OBJECT BOUNDS Object Number
    DB_Basic3D\ShowBounds= AIsFunction( 1 , "?ShowBounds@@YAXH@Z" ) ; 278 SHOW OBJECT BOUNDS Object Number
    DB_Basic3D\SetSmoothing= AIsFunction( 1 , "?SetSmoothing@@YAXHM@Z" ) ; 279 SET OBJECT SMOOTHING Object Number, Percentage
    DB_Basic3D\SetLimbSmoothing= AIsFunction( 1 , "?SetLimbSmoothing@@YAXHHM@Z" ) ; 280 SET LIMB SMOOTHING Object Number, Limb Number, Percentage
    DB_Basic3D\GetXSizeEx= AIsFunction( 1 , "?GetXSizeEx@@YAKHH@Z" ) ; 281 OBJECT SIZE X Object Number, Actual Size
    DB_Basic3D\LockVertexDataForLimb= AIsFunction( 1 , "?LockVertexDataForLimb@@YAXHH@Z" ) ; 282 LOCK VERTEXDATA FOR LIMB Object Number, Limb Number
    DB_Basic3D\LockVertexDataForMesh= AIsFunction( 1 , "?LockVertexDataForMesh@@YAXH@Z" ) ; 283 LOCK VERTEXDATA FOR MESH Mesh Number
    DB_Basic3D\UnlockVertexData= AIsFunction( 1 , "?UnlockVertexData@@YAXXZ" ) ; 284 UNLOCK VERTEXDATA 
    DB_Basic3D\SetVertexDataUV= AIsFunction( 1 , "?SetVertexDataUV@@YAXHMM@Z" ) ; 285 SET VERTEXDATA UV Vertex Index, U, V
    DB_Basic3D\SetVertexDataNormals= AIsFunction( 1 , "?SetVertexDataNormals@@YAXHMMM@Z" ) ; 286 SET VERTEXDATA NORMALS Vertex Index, NX, NY, NZ
    DB_Basic3D\SetVertexDataPosition= AIsFunction( 1 , "?SetVertexDataPosition@@YAXHMMM@Z" ) ; 287 SET VERTEXDATA POSITION Vertex Index, X, Y, Z
    DB_Basic3D\SetVertexDataDiffuse= AIsFunction( 1 , "?SetVertexDataDiffuse@@YAXHK@Z" ) ; 288 SET VERTEXDATA DIFFUSE Vertex Index, RGB Value
    DB_Basic3D\AddMeshToVertexData= AIsFunction( 1 , "?AddMeshToVertexData@@YAXH@Z" ) ; 289 ADD MESH TO VERTEXDATA Mesh Number
    DB_Basic3D\DeleteMeshFromVertexData= AIsFunction( 1 , "?DeleteMeshFromVertexData@@YAXHHHH@Z" ) ; 290 DELETE MESH FROM VERTEXDATA Vertex Start, Vertex End, Index Start, Index End
    DB_Basic3D\GetVertexDataVertexCount= AIsFunction( 1 , "?GetVertexDataVertexCount@@YAHXZ" ) ; 291 GET VERTEXDATA VERTEX COUNT 
    DB_Basic3D\GetVertexDataIndexCount= AIsFunction( 1 , "?GetVertexDataIndexCount@@YAHXZ" ) ; 292 GET VERTEXDATA INDEX COUNT 
    DB_Basic3D\GetVertexDataPositionX= AIsFunction( 1 , "?GetVertexDataPositionX@@YAKH@Z" ) ; 293 GET VERTEXDATA POSITION X Vertex Index
    DB_Basic3D\GetVertexDataPositionY= AIsFunction( 1 , "?GetVertexDataPositionY@@YAKH@Z" ) ; 294 GET VERTEXDATA POSITION Y Vertex Index
    DB_Basic3D\GetVertexDataPositionZ= AIsFunction( 1 , "?GetVertexDataPositionZ@@YAKH@Z" ) ; 295 GET VERTEXDATA POSITION Z Vertex Index
    DB_Basic3D\GetVertexDataNormalsX= AIsFunction( 1 , "?GetVertexDataNormalsX@@YAKH@Z" ) ; 296 GET VERTEXDATA NORMALS X Vertex Index
    DB_Basic3D\GetVertexDataNormalsY= AIsFunction( 1 , "?GetVertexDataNormalsY@@YAKH@Z" ) ; 297 GET VERTEXDATA NORMALS Y Vertex Index
    DB_Basic3D\GetVertexDataNormalsZ= AIsFunction( 1 , "?GetVertexDataNormalsZ@@YAKH@Z" ) ; 298 GET VERTEXDATA NORMALS Z Vertex Index
    DB_Basic3D\GetVertexDataU= AIsFunction( 1 , "?GetVertexDataU@@YAKH@Z" ) ; 299 GET VERTEXDATA U Vertex Index
    DB_Basic3D\GetVertexDataV= AIsFunction( 1 , "?GetVertexDataV@@YAKH@Z" ) ; 300 GET VERTEXDATA V Vertex Index
    DB_Basic3D\GetVertexDataDiffuse= AIsFunction( 1 , "?GetVertexDataDiffuse@@YAKH@Z" ) ; 301 GET VERTEXDATA DIFFUSE Vertex Index
    DB_Basic3D\SetAlphaFactor= AIsFunction( 1 , "?SetAlphaFactor@@YAXHM@Z" ) ; 302 SET ALPHA MAPPING ON Object Number, Alpha Percentage
    DB_Basic3D\Instance= AIsFunction( 1 , "?Instance@@YAXHH@Z" ) ; 303 INSTANCE OBJECT Object Number, Source Object
    DB_Basic3D\SetEffectOn= AIsFunction( 1 , "?SetEffectOn@@YAXHKH@Z" ) ; 316 SET EFFECT ON Object Number, Effect Filename, Texture Flag
    DB_Basic3D\SetTextureStage= AIsFunction( 1 , "?SetTextureStage@@YAXHHH@Z" ) ; 317 TEXTURE OBJECT Object Number, Stage Number, Image Number
    DB_Basic3D\EnableZRead= AIsFunction( 1 , "?EnableZRead@@YAXH@Z" ) ; 318 ENABLE OBJECT ZREAD Object Number
    DB_Basic3D\DisableZRead= AIsFunction( 1 , "?DisableZRead@@YAXH@Z" ) ; 319 DISABLE OBJECT ZREAD Object Number
    DB_Basic3D\EnableZWrite= AIsFunction( 1 , "?EnableZWrite@@YAXH@Z" ) ; 320 ENABLE OBJECT ZWRITE Object Number
    DB_Basic3D\DisableZWrite= AIsFunction( 1 , "?DisableZWrite@@YAXH@Z" ) ; 321 DISABLE OBJECT ZWRITE Object Number
    DB_Basic3D\LoadEffect= AIsFunction( 1 , "?LoadEffect@@YAXKHH@Z" ) ; 322 LOAD EFFECT Filename, Effect Number, Texture Flag
    DB_Basic3D\DeleteEffect= AIsFunction( 1 , "?DeleteEffect@@YAXH@Z" ) ; 323 DELETE EFFECT Effect Number
    DB_Basic3D\SetObjectEffect= AIsFunction( 1 , "?SetObjectEffect@@YAXHH@Z" ) ; 324 SET OBJECT EFFECT Object Number, Effect Number
    DB_Basic3D\SetLimbEffect= AIsFunction( 1 , "?SetLimbEffect@@YAXHHH@Z" ) ; 325 SET LIMB EFFECT Object Number, Limb Number, Effect Number
    DB_Basic3D\SetEffectConstantF= AIsFunction( 1 , "?SetEffectConstantF@@YAXHKM@Z" ) ; 326 SET EFFECT CONSTANT FLOAT Effect Number, Constant String, Constant Value
    DB_Basic3D\PerformChecklistForEffectValues= AIsFunction( 1 , "?PerformChecklistForEffectValues@@YAXH@Z" ) ; 327 PERFORM CHECKLIST FOR EFFECT VALUES Effect Number
    DB_Basic3D\SetDiffuseMaterial= AIsFunction( 1 , "?SetDiffuseMaterial@@YAXHK@Z" ) ; 328 SET OBJECT DIFFUSE Object Number, Color Value
    DB_Basic3D\SetAmbienceMaterial= AIsFunction( 1 , "?SetAmbienceMaterial@@YAXHK@Z" ) ; 329 SET OBJECT AMBIENCE Object Number, Color Value
    DB_Basic3D\SetSpecularMaterial= AIsFunction( 1 , "?SetSpecularMaterial@@YAXHK@Z" ) ; 330 SET OBJECT SPECULAR Object Number, Color Value
    DB_Basic3D\SetEmissiveMaterial= AIsFunction( 1 , "?SetEmissiveMaterial@@YAXHK@Z" ) ; 331 SET OBJECT EMISSIVE Object Number, Color Value
    DB_Basic3D\SetSpecularPower= AIsFunction( 1 , "?SetSpecularPower@@YAXHM@Z" ) ; 332 SET OBJECT SPECULAR POWER Object Number, Power
    DB_Basic3D\TextureLimbStage= AIsFunction( 1 , "?TextureLimbStage@@YAXHHHH@Z" ) ; 333 TEXTURE LIMB Object Number, Limb Number, Stage Number, Image Number
    DB_Basic3D\MakeEmitter= AIsFunction( 1 , "?MakeEmitter@@YAXHH@Z" ) ; 335 MAKE EMITTER Object Number, Size
    DB_Basic3D\GetEffectExist= AIsFunction( 1 , "?GetEffectExist@@YAHH@Z" ) ; 336 EFFECT EXIST Effect Number
    DB_Basic3D\PerformChecklistForEffectErrors= AIsFunction( 1 , "?PerformChecklistForEffectErrors@@YAXXZ" ) ; 341 PERFORM CHECKLIST FOR EFFECT ERRORS 
    DB_Basic3D\SetEffectTranspose= AIsFunction( 1 , "?SetEffectTranspose@@YAXHH@Z" ) ; 342 SET EFFECT TRANSPOSE Effect Number, Transpose Flag
    DB_Basic3D\SetEffectConstantB= AIsFunction( 1 , "?SetEffectConstantB@@YAXHKH@Z" ) ; 343 SET EFFECT CONSTANT BOOLEAN Effect Number, Constant String, Constant Value
    DB_Basic3D\SetEffectConstantI= AIsFunction( 1 , "?SetEffectConstantI@@YAXHKH@Z" ) ; 344 SET EFFECT CONSTANT INTEGER Effect Number, Constant String, Constant Value
    DB_Basic3D\SetEffectConstantV= AIsFunction( 1 , "?SetEffectConstantV@@YAXHKH@Z" ) ; 345 SET EFFECT CONSTANT VECTOR Effect Number, Constant String, Vector Number
    DB_Basic3D\SetEffectConstantM= AIsFunction( 1 , "?SetEffectConstantM@@YAXHKH@Z" ) ; 346 SET EFFECT CONSTANT MATRIX Effect Number, Constant String, Matrix Number
    DB_Basic3D\PickScreenObject= AIsFunction( 1 , "?PickScreenObject@@YAHHHHH@Z" ) ; 347 PICK OBJECT Screen X, Screen Y, Object Start, Object End
    DB_Basic3D\GetPickVectorX= AIsFunction( 1 , "?GetPickVectorX@@YAKXZ" ) ; 348 GET PICK VECTOR X 
    DB_Basic3D\GetPickVectorY= AIsFunction( 1 , "?GetPickVectorY@@YAKXZ" ) ; 349 GET PICK VECTOR Y 
    DB_Basic3D\GetPickVectorZ= AIsFunction( 1 , "?GetPickVectorZ@@YAKXZ" ) ; 350 GET PICK VECTOR Z 
    DB_Basic3D\PickScreen2D23D= AIsFunction( 1 , "?PickScreen2D23D@@YAXHHM@Z" ) ; 351 PICK SCREEN Screen X, Screen Y, Distance
    DB_Basic3D\GetPickDistance= AIsFunction( 1 , "?GetPickDistance@@YAKXZ" ) ; 352 GET PICK DISTANCE 
    DB_Basic3D\SetShadingOff= AIsFunction( 1 , "?SetShadingOff@@YAXH@Z" ) ; 353 SET SHADING OFF Object Number
    DB_Basic3D\ShowBoundsEx= AIsFunction( 1 , "?ShowBoundsEx@@YAXHH@Z" ) ; 354 SHOW OBJECT BOUNDS Object Number, Box Only Flag
    DB_Basic3D\SetEffectTechnique= AIsFunction( 1 , "?SetEffectTechnique@@YAXHK@Z" ) ; 355 SET EFFECT TECHNIQUE Effect Number, Technique Name
    DB_Basic3D\SetVertexDataUV1= AIsFunction( 1 , "?SetVertexDataUV@@YAXHHMM@Z" ) ; 357 SET VERTEXDATA UV Vertex Index, Index,U, V
    DB_Basic3D\PerformChecklistForEffectErrors1= AIsFunction( 1 , "?PerformChecklistForEffectErrors@@YAXH@Z" ) ; 358 PERFORM CHECKLIST FOR EFFECT ERRORS Effect Number
    DB_Basic3D\GetLimbCollision= AIsFunction( 1 , "?GetLimbCollision@@YAHHHHH@Z" ) ; 361 LIMB COLLISION ObjectA Number, LimbA Number, ObjectB Number, LimbB Number
    DB_Basic3D\GetLimbHit= AIsFunction( 1 , "?GetLimbHit@@YAHHHHH@Z" ) ; 362 LIMB HIT ObjectA Number, LimbA Number, ObjectB Number, LimbB Number
    DB_Basic3D\Load1= AIsFunction( 1 , "?Load@@YAXKHH@Z" ) ; 366 LOAD OBJECT Filename, Object Number, DBPro Mode
    DB_Basic3D\ExcludeOn= AIsFunction( 1 , "?ExcludeOn@@YAXH@Z" ) ; 367 EXCLUDE OBJECT ON Object ID
    DB_Basic3D\ExcludeOff= AIsFunction( 1 , "?ExcludeOff@@YAXH@Z" ) ; 368 EXCLUDE OBJECT OFF Object ID
    DB_Basic3D\SetNormals= AIsFunction( 1 , "?SetNormals@@YAXH@Z" ) ; 369 SET OBJECT NORMALS Object Number
    DB_Basic3D\SetLimbNormals= AIsFunction( 1 , "?SetLimbNormals@@YAXHH@Z" ) ; 370 SET LIMB NORMALS Object Number, Limb Number
    DB_Basic3D\SetTextureModeStage= AIsFunction( 1 , "?SetTextureModeStage@@YAXHHHH@Z" ) ; 371 SET OBJECT TEXTURE Object Number, Stage Number, Texturing Mode, Mipmap Flag
    DB_Basic3D\SetFilterStage= AIsFunction( 1 , "?SetFilterStage@@YAXHHH@Z" ) ; 372 SET OBJECT FILTER Object Number, Stage Number, Flag
    DB_Basic3D\LockVertexDataForLimbCore= AIsFunction( 1 , "?LockVertexDataForLimbCore@@YAXHHH@Z" ) ; 373 LOCK VERTEXDATA FOR LIMB Object Number, Limb Number, Lock Mode
    DB_Basic3D\SetObjectFOV= AIsFunction( 1 , "?SetObjectFOV@@YAXHM@Z" ) ; 375 SET OBJECT FOV Object Number, FOV Angle
    DB_Basic3D\Deletes= AIsFunction( 1 , "?Deletes@@YAXHH@Z" ) ; 383 DELETE OBJECTS From, To
    DB_Basic3D\ForceAutomaticEnd= AIsFunction( 1 , "?ForceAutomaticEnd@@YAXXZ" ) ; 384 CALCULATE AUTOMATIC COLLISION 
    DB_Basic3D\EnableZBias= AIsFunction( 1 , "?EnableZBias@@YAXHMM@Z" ) ; 385 ENABLE OBJECT ZBIAS Object Number, Slope Scale, Depth
    DB_Basic3D\DisableZBias= AIsFunction( 1 , "?DisableZBias@@YAXH@Z" ) ; 386 DISABLE OBJECT ZBIAS Object Number
    DB_Basic3D\OffsetLimb1= AIsFunction( 1 , "?OffsetLimb@@YAXHHMMMH@Z" ) ; 387 OFFSET LIMB Object Number, Limb Number, X, Y, Z, Bounds Flag
    DB_Basic3D\ScaleLimb1= AIsFunction( 1 , "?ScaleLimb@@YAXHHMMMH@Z" ) ; 388 SCALE LIMB Object Number, Limb Number, XSize, YSize, ZSize, Bounds Flag
    DB_Basic3D\RotateLimb1= AIsFunction( 1 , "?RotateLimb@@YAXHHMMMH@Z" ) ; 389 ROTATE LIMB Object Number, Limb Number, XAngle, YAngle, ZAngle, Bounds Flag
    DB_Basic3D\CloneShared= AIsFunction( 1 , "?CloneShared@@YAXHHH@Z" ) ; 392 CLONE OBJECT Object Number, Source Object, Share Original Data
    DB_Basic3D\SetFrameEx1= AIsFunction( 1 , "?SetFrameEx@@YAXHMH@Z" ) ; 393 SET OBJECT FRAME Object Number, Frame, Recalculate Bounds
    DB_Basic3D\SetShadowOnEx= AIsFunction( 1 , "?SetShadowOnEx@@YAXHHHH@Z" ) ; 394 SET SHADOW SHADING ON Object Number, Mesh Number, Shadow Range, Use Shader
    DB_Basic3D\SetShadowOff= AIsFunction( 1 , "?SetShadowOff@@YAXH@Z" ) ; 395 SET SHADOW SHADING OFF Object Number
    DB_Basic3D\SetBlendMap1= AIsFunction( 1 , "?SetBlendMap@@YAXHHHHH@Z" ) ; 397 SET BLEND MAPPING ON Object Number, Stage Index, Image Number, TexCoordMode, Blend Mode
    DB_Basic3D\SetIndexData= AIsFunction( 1 , "?SetIndexData@@YAXHH@Z" ) ; 398 SET INDEXDATA Indice Index, Vertex Index
    DB_Basic3D\GetIndexData= AIsFunction( 1 , "?GetIndexData@@YAHH@Z" ) ; 399 GET INDEXDATA Index Number
    DB_Basic3D\GetVertexDataU1= AIsFunction( 1 , "?GetVertexDataU@@YAKHH@Z" ) ; 400 GET VERTEXDATA U Vertex Index, Stage Number
    DB_Basic3D\GetVertexDataV1= AIsFunction( 1 , "?GetVertexDataV@@YAKHH@Z" ) ; 401 GET VERTEXDATA V Vertex Index, Stage Number
    DB_Basic3D\GetYSizeEx= AIsFunction( 1 , "?GetYSizeEx@@YAKHH@Z" ) ; 403 OBJECT SIZE Y Object Number, Actual Size
    DB_Basic3D\SetGlobalObjectCreationMode= AIsFunction( 1 , "?SetGlobalObjectCreationMode@@YAXH@Z" ) ; 404 SET GLOBAL OBJECT CREATION Creation Mode
    DB_Basic3D\GetZSizeEx= AIsFunction( 1 , "?GetZSizeEx@@YAKHH@Z" ) ; 405 OBJECT SIZE Z Object Number, Actual Size
    DB_Basic3D\ScrollTexture1= AIsFunction( 1 , "?ScrollTexture@@YAXHHMM@Z" ) ; 406 SCROLL OBJECT TEXTURE Object Number, Stage, X, Y
    DB_Basic3D\ScaleLimbTexture1= AIsFunction( 1 , "?ScaleLimbTexture@@YAXHHHMM@Z" ) ; 407 SCALE LIMB TEXTURE Object Number, Limb Number, Stage, UScale, VScale
    DB_Basic3D\ScrollLimbTexture1= AIsFunction( 1 , "?ScrollLimbTexture@@YAXHHHMM@Z" ) ; 408 SCROLL LIMB TEXTURE Object Number, Limb Number, Stage, X, Y
    DB_Basic3D\SetTextureStageEx= AIsFunction( 1 , "?SetTextureStageEx@@YAXHHHH@Z" ) ; 409 TEXTURE OBJECT Object Number, Stage Number, Image Number, Ignore Sorting
    DB_Basic3D\SetDiffuseMaterialEx= AIsFunction( 1 , "?SetDiffuseMaterialEx@@YAXHKH@Z" ) ; 410 SET OBJECT DIFFUSE Object Number, Color Value, VertexDiffuseMode
    DB_Basic3D\Load2= AIsFunction( 1 , "?Load@@YAXKHHH@Z" ) ; 411 LOAD OBJECT Filename, Object Number, DBPro Mode, Divide Texture
    DB_Basic3D\GetLimbTextureNameEx= AIsFunction( 1 , "?GetLimbTextureNameEx@@YAKKHHH@Z" ) ; 412 LIMB TEXTURE NAME Object Number, Limb Number, Texture Stage
    DB_Basic3D\GetLimbTextureEx= AIsFunction( 1 , "?GetLimbTextureEx@@YAHHHH@Z" ) ; 413 LIMB TEXTURE Object Number, Limb Number, Texture Stage
    DB_Basic3D\PickScreenObjectEx= AIsFunction( 1 , "?PickScreenObjectEx@@YAHHHHHH@Z" ) ; 414 PICK OBJECT Screen X, Screen Y, Object Start, Object End, Ignore Camera Flag
    DB_Basic3D\GlueToLimbEx= AIsFunction( 1 , "?GlueToLimbEx@@YAXHHHH@Z" ) ; 415 GLUE OBJECT TO LIMB Object Number, Second Object, Limb Number, Glue Mode
    DB_Basic3D\ConvertMeshToVertexData= AIsFunction( 1 , "?ConvertMeshToVertexData@@YAXH@Z" ) ; 416 CONVERT MESH TO VERTEXDATA Mesh Number
    DB_Basic3D\MakeObjectFromLimbEx= AIsFunction( 1 , "?MakeObjectFromLimbEx@@YAXHHHH@Z" ) ; 417 MAKE OBJECT FROM LIMB Object Number, Second Object, Limb Number, All Limbs Flag
    DB_Basic3D\AutomaticCameraCollision1= AIsFunction( 1 , "?AutomaticCameraCollision@@YAXHMHH@Z" ) ; 418 AUTOMATIC CAMERA COLLISION Camera Number, Radius, Response, Stand Ground Mode
    CloseLibrary( 1 )
   Else
    SUCCESS.l = 0
   Endif
  ProcedureReturn SUCCESS
 EndProcedure
