;
; PurePLUGIN 1.5 changes :
; Extracted DarkBASIC Professional & Plugins Commands list from main project .PB file for easier includes.
;

  IncludeFile "..\DBPro_Commands\DBProAnimationDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProBasic2DDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProBasic3DDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProBitmapDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBproCameraDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProCore.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProCSGDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProFileDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProFTPDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProImageDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProInputDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProLightDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProLODTerrainDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProMatrixDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProMemblocksDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProMultiPlayerDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProMusicDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProParticlesDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProSetupDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProSoundDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProSpritesDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProSystemDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProTextDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProVectorsDebug.dll_Commands.pb"
  IncludeFile "..\DBPro_Commands\DBProWorld3DDebug.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\AdvancedTerrain.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProGameFX.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\EnhancementsOV.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DBProMultiplayerPlusDebug.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DBProODEDebug.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\ShaderData.dll_Commands.pb"
; PurePLUGIN Ver 1.1 Upgrades support :
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DarkPHYSICS.dll_Commands.pb"
; Ver 1.1 Addons: eXtends 1.3 version needed.
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProBasic2DExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProBasic3DExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProBitmapExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProCameraExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProEffects3DExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProFileExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProImageExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProLight3DExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProMatrixExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProMemblocksExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProMesh3DExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProMusicExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProParticles3DExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProRTSkyboxExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProSoundExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProSpriteExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProTextExtends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProVector2Extends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProVector3Extends.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-LICENSED_Commands\DBProVector4Extends.dll_Commands.pb"
; Ver 1.1 Addons: DKSHop plugin:
  IncludeFile "..\DBProPLUGIN-USER_Commands\DKSHOP.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DKAVM.dll_Commands.pb"
; Ver 1.2 Addons: Sparky's Collision DLL:
  IncludeFile "..\DBProPLUGIN-USER_Commands\SC_Collision.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\AdvancedSPRITES.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideColourRequester.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideDeskTop.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideDisplay.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideFileRequester.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideFontRequester.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideInput.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideInputRequester.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideMessageBox.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideProgressBar.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSidePsychoCircle.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideSpeedMenu.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideStarBurst.dll_Commands.pb"
  IncludeFile "..\DBProPLUGIN-USER_Commands\DarkSideWhiteRabbit.dll_Commands.pb"

; IDE Options = PureBasic 4.20 Beta 2 (Windows - x86)
; CursorPosition = 5
; FirstLine = 3
; Folding = -