; DarkBasic Professional RC2PBIncludes Ver 1.0 File - STRUCTURES SETUP
; By Frederic Cordier - 07.02.13
;
Structure DB_DarkPhysicsStruct
  dbPhyAttachClothToShape.l : dbPhyAttachClothToAllShapes.l : dbPhyDetachClothFromShape.l : dbPhyAttachClothVertex.l
  dbPhyAttachClothVertexToShape.l : dbPhyFreeClothVertex.l : dbPhyMakeCloth.l : dbPhyMakeClothFromObject.l
  dbPhyMakeClothFromLimb.l : dbPhyBuildCloth.l : dbPhySetClothDimensions.l : dbPhySetClothPosition.l
  dbPhySetClothRotation.l : dbPhySetClothStatic.l : dbPhySetClothCollision.l : dbPhySetClothGravity.l
  dbPhySetClothBending.l : dbPhySetClothDamping.l : dbPhySetClothTwoWayCollision.l : dbPhySetClothTearing.l
  dbPhySetClothThickness.l : dbPhySetClothDensity.l : dbPhySetClothBendingStiffness.l : dbPhySetClothStretchingStiffness.l
  dbPhySetClothFriction.l : dbPhySetClothPressure.l : dbPhySetClothTearFactor.l : dbPhySetClothCollisionResponseCoefficient.l
  dbPhySetClothAttachmentResponseCoefficient.l : dbPhySetClothSolverIterations.l : dbPhySetClothExternalAcceleration.l : dbPhySetClothCollisionGroup.l
  dbPhyAddForceAtClothVertex.l : dbPhyGetClothExist.l : dbPhyGetClothBuilt.l : dbPhyGetClothWidthEx.l
  dbPhyGetClothHeightEx.l : dbPhyGetClothDepthEx.l : dbPhyGetClothPositionXEx.l : dbPhyGetClothPositionYEx.l
  dbPhyGetClothPositionZEx.l : dbPhyGetClothRotationXEx.l : dbPhyGetClothRotationYEx.l : dbPhyGetClothRotationZEx.l
  dbPhyGetClothStatic.l : dbPhyGetClothCollision.l : dbPhyGetClothGravity.l : dbPhyGetClothBending.l
  dbPhyGetClothDamping.l : dbPhyGetClothTwoWayCollision.l : dbPhyGetClothTearing.l : dbPhyGetClothThicknessEx.l
  dbPhyGetClothDensityEx.l : dbPhyGetClothBendingStiffnessEx.l : dbPhyGetClothStretchingStiffnessEx.l : dbPhyGetClothFrictionEx.l
  dbPhyGetClothPressureEx.l : dbPhyGetClothTearFactorEx.l : dbPhyGetClothCollisionResponseCoefficientEx.l : dbPhyGetClothAttachmentResponseCoefficientEx.l
  dbPhyGetClothSolverIterations.l : dbPhyGetClothExternalAccelerationXEx.l : dbPhyGetClothExternalAccelerationYEx.l : dbPhyGetClothExternalAccelerationZEx.l
  dbPhyGetClothCollisionGroup.l : dbPhyGetClothMinSizeXEx.l : dbPhyGetClothMinSizeYEx.l : dbPhyGetClothMinSizeZEx.l
  dbPhyGetClothMaxSizeXEx.l : dbPhyGetClothMaxSizeYEx.l : dbPhyGetClothMaxSizeZEx.l : dbPhyClothRayCast.l
  dbPhyClothRayCastHitX.l : dbPhyClothRayCastHitY.l : dbPhyClothRayCastHitZ.l : dbPhyClothRayCastHitVertex.l
  dbPhySetGravity.l : dbPhySetTiming.l : dbPhySetFixedTiming.l : dbPhySetAutoFixedTiming.l
  dbPhySetSkinWidth.l : dbPhySetDefaultSleepLinearVelocitySquared.l : dbPhySetDefaultSleepAngularVelocitySquared.l : dbPhySetBounceThreshold.l
  dbPhySetDynamicFriction.l : dbPhySetStaticFriction.l : dbPhySetMaxAngularVelocity.l : dbPhySetContinuousCD.l
  dbPhySetAdaptiveForce.l : dbPhySetControlledFiltering.l : dbPhySetTriggerCallback.l : dbPhyEnableDebug.l
  dbPhyStart.l : dbPhyStart1.l : dbPhyEnd.l : dbPhyClear.l
  dbPhysX.l : dbPhyUpdate.l : dbPhyMakeFluid.l : dbPhyMakeFluidEmitter.l
  dbPhyBuildFluid.l : dbPhyDeleteFluid.l : dbPhyGetFluidExist.l : dbPhyMakeBoxDrain.l
  dbPhyMakeSphereDrain.l : dbPhyDeleteDrain.l : dbPhyGetDrainExist.l : dbPhySetFluidParticleBufferCap.l
  dbPhySetFluidRestPerMetre.l : dbPhySetFluidRadius.l : dbPhySetFluidMotionLimit.l : dbPhySetFluidPacketSize.l
  dbPhySetFluidPosition.l : dbPhySetFluidRotation.l : dbPhySetFluidStiffness.l : dbPhySetFluidViscosity.l
  dbPhySetFluidRestDensity.l : dbPhySetFluidDamping.l : dbPhySetFluidMethod.l : dbPhySetFluidAcceleration.l
  dbPhySetFluidEmitterType.l : dbPhySetFluidEmitterMaxParticles.l : dbPhySetFluidEmitterShape.l : dbPhySetFluidEmitterDimensions.l
  dbPhySetFluidEmitterRandomPosition.l : dbPhySetFluidEmitterRandomAngle.l : dbPhySetFluidEmitterVelocity.l : dbPhySetFluidEmitterRate.l
  dbPhySetFluidEmitterLifetime.l : dbPhySetFluidEmitterFlags.l : dbPhyMakeParticleEmitter.l : dbPhyMakeFireEmitter.l
  dbPhyMakeSmokeEmitter.l : dbPhyMakeSnowEmitter.l : dbPhyDeleteEmitter.l : dbPhySetEmitterLinearVelocity.l
  dbPhySetEmitterLinearVelocityRange.l : dbPhySetEmitterGravity.l : dbPhySetEmitterLifeSpan.l : dbPhySetEmitterFade.l
  dbPhySetEmitterSize.l : dbPhySetEmitterMaxSize.l : dbPhySetEmitterGrowthRate.l : dbPhySetEmitterRange.l
  dbPhySetEmitterStartColor.l : dbPhySetEmitterEndColor.l : dbPhySetEmitterPosition.l : dbPhyGetEmitterExist.l
  dbPhyMakeBoxCharacterController.l : dbPhyMakeCapsuleCharacterController.l : dbPhyMoveCharacterController.l : dbPhyGetCharacterControllerExist.l
  dbPhyDeleteCharacterController.l : dbPhyGetCollisionData.l : dbPhyGetCollisionObjectA.l : dbPhyGetCollisionObjectB.l
  dbPhyMakeRigidBodyStaticBox.l : dbPhyMakeRigidBodyStaticBoxes.l : dbPhyMakeRigidBodyStaticBox1.l : dbPhyMakeRigidBodyStaticBoxes1.l
  dbPhyMakeRigidBodyDynamicBox.l : dbPhyMakeRigidBodyDynamicBoxes.l : dbPhyMakeRigidBodyDynamicBox1.l : dbPhyMakeRigidBodyDynamicBoxes1.l
  dbPhyMakeRigidBodyStaticCapsule.l : dbPhyMakeRigidBodyStaticCapsules.l : dbPhyMakeRigidBodyStaticCapsule1.l : dbPhyMakeRigidBodyStaticCapsules1.l
  dbPhyMakeRigidBodyDynamicCapsule.l : dbPhyMakeRigidBodyDynamicCapsules.l : dbPhyMakeRigidBodyDynamicCapsule1.l : dbPhyMakeRigidBodyDynamicCapsules1.l
  dbPhyMakeRigidBodyStaticConvex.l : dbPhyMakeRigidBodyStaticConvexes.l : dbPhyMakeRigidBodyStaticConvex1.l : dbPhyMakeRigidBodyStaticConvexes1.l
  dbPhyMakeRigidBodyDynamicConvex.l : dbPhyMakeRigidBodyDynamicConvexes.l : dbPhyMakeRigidBodyDynamicConvex1.l : dbPhyMakeRigidBodyDynamicConvexes1.l
  dbPhyLoadRigidBodyStaticConvex.l : dbPhyLoadRigidBodyStaticConvexes.l : dbPhyLoadRigidBodyStaticConvex1.l : dbPhyLoadRigidBodyStaticConvexes1.l
  dbPhyLoadRigidBodyDynamicConvex.l : dbPhyLoadRigidBodyDynamicConvexes.l : dbPhyLoadRigidBodyDynamicConvex1.l : dbPhyLoadRigidBodyDynamicConvexes1.l
  dbPhyMakeRigidBodyStaticMesh.l : dbPhyMakeRigidBodyStaticMeshes.l : dbPhyMakeRigidBodyStaticMesh1.l : dbPhyMakeRigidBodyStaticMeshes1.l
  dbPhyMakeRigidBodyDynamicMesh.l : dbPhyMakeRigidBodyDynamicMeshes.l : dbPhyMakeRigidBodyDynamicMesh1.l : dbPhyMakeRigidBodyDynamicMeshes1.l
  dbPhyMakeRigidBodyStaticMesh2.l : dbPhyMakeRigidBodyStaticMeshes2.l : dbPhyMakeRigidBodyStaticMesh3.l : dbPhyMakeRigidBodyStaticMeshes3.l
  dbPhyMakeRigidBodyDynamicMesh2.l : dbPhyMakeRigidBodyDynamicMeshes2.l : dbPhyMakeRigidBodyDynamicMesh3.l : dbPhyMakeRigidBodyDynamicMeshes3.l
  dbPhyLoadRigidBodyStaticMesh.l : dbPhyLoadRigidBodyStaticMeshes.l : dbPhyLoadRigidBodyStaticMesh1.l : dbPhyLoadRigidBodyStaticMeshes1.l
  dbPhyLoadRigidBodyDynamicMesh.l : dbPhyLoadRigidBodyDynamicMeshes.l : dbPhyLoadRigidBodyDynamicMesh1.l : dbPhyLoadRigidBodyDynamicMeshes1.l
  dbPhyMakeRagdoll.l : dbPhyAssignRagdollPart.l : dbPhyMakeRigidBodyStaticSphere.l : dbPhyMakeRigidBodyStaticSpheres.l
  dbPhyMakeRigidBodyStaticSphere1.l : dbPhyMakeRigidBodyStaticSpheres1.l : dbPhyMakeRigidBodyDynamicSphere.l : dbPhyMakeRigidBodyDynamicSpheres.l
  dbPhyMakeRigidBodyDynamicSphere1.l : dbPhyMakeRigidBodyDynamicSpheres1.l : dbPhySetVehicleBrakeTorque.l : dbPhySetRigidBodyTerrainExtent.l
  dbPhySetRigidBodyCCD.l : dbPhyGetRigidBodyDynamic.l : dbPhyDeleteRigidBody.l : dbPhyGetRigidBodyExist.l
  dbPhyGetRigidBodyType.l : dbPhyMake6DOFJoint.l : dbPhySet6DOFJointLocalAnchor.l : dbPhySet6DOFJointLocalAxis.l
  dbPhySet6DOFJointLocalNormal.l : dbPhySet6DOFJointGlobalAnchor.l : dbPhySet6DOFJointGlobalAxis.l : dbPhySet6DOFJointTwistMotion.l
  dbPhySet6DOFJointSwing1Motion.l : dbPhySet6DOFJointSwing2Motion.l : dbPhySet6DOFJointMotionX.l : dbPhySet6DOFJointMotionY.l
  dbPhySet6DOFJointMotionZ.l : dbPhySet6DOFJointLinearLimit.l : dbPhySet6DOFJointSwing1Limit.l : dbPhySet6DOFJointSwing2Limit.l
  dbPhySet6DOFJointTwistLimit.l : dbPhySet6DOFJointDriveX.l : dbPhySet6DOFJointDriveY.l : dbPhySet6DOFJointDriveZ.l
  dbPhySet6DOFJointTwistDrive.l : dbPhySet6DOFJointSwingDrive.l : dbPhySet6DOFJointSlerpDrive.l : dbPhySet6DOFJointDrivePosition.l
  dbPhySet6DOFJointDriveRotation.l : dbPhySet6DOFJointDriveLinearVelocity.l : dbPhySet6DOFJointDriveAngularVelocity.l : dbPhySet6DOFJointProjection.l
  dbPhySet6DOFJointSlerpDrive1.l : dbPhySet6DOFJointGear.l : dbPhyBuild6DOFJoint.l : dbPhyMakeCylindricalJoint.l
  dbPhyMakeCylindricalJoint1.l : dbPhySetCylindricalJointLocalAnchor.l : dbPhySetCylindricalJointLocalAxis.l : dbPhySetCylindricalJointGlobalAnchor.l
  dbPhySetCylindricalJointGlobalAxis.l : dbPhyBuildCylindricalJoint.l : dbPhyMakeDistanceJoint.l : dbPhyMakeDistanceJoint1.l
  dbPhySetDistanceJointLocalAnchor.l : dbPhySetDistanceJointGlobalAnchor.l : dbPhySetDistanceJointLocalAxis.l : dbPhySetDistanceJointGlobalAxis.l
  dbPhySetDistanceJointMax.l : dbPhySetDistanceJointMin.l : dbPhySetDistanceJointSpring.l : dbPhyBuildDistanceJoint.l
  dbPhyMakeFixedJoint.l : dbPhyMakeFixedJoint1.l : dbPhyBuildFixedJoint.l : dbPhyMakePointInPlaneJoint.l
  dbPhyMakePointInPlaneJoint1.l : dbPhySetPointInPlaneJointLocalAnchor.l : dbPhySetPointInPlaneJointLocalAxis.l : dbPhySetPointInPlaneJointGlobalAnchor.l
  dbPhySetPointInPlaneJointGlobalAxis.l : dbPhyBuildPointInPlaneJoint.l : dbPhyMakePointOnLineJoint.l : dbPhyMakePointOnLineJoint1.l
  dbPhySetPointOnLineJointLocalAnchor.l : dbPhySetPointOnLineJointLocalAxis.l : dbPhySetPointOnLineJointGlobalAnchor.l : dbPhySetPointOnLineJointGlobalAxis.l
  dbPhyBuildPointOnLineJoint.l : dbPhyMakePrismaticJoint.l : dbPhyMakePrismaticJoint1.l : dbPhySetPrismaticJointLocalAnchor.l
  dbPhySetPrismaticJointLocalAxis.l : dbPhySetPrismaticJointGlobalAnchor.l : dbPhySetPrismaticJointGlobalAxis.l : dbPhyBuildPrismaticJoint.l
  dbPhyMakePulleyJoint.l : dbPhyMakePulleyJoint1.l : dbPhySetPulleyJointLocalAnchor.l : dbPhySetPulleyJointGlobalAnchor.l
  dbPhySetPulleyJointLocalAxis.l : dbPhySetPulleyJointGlobalAxis.l : dbPhySetPulleyJointSuspension.l : dbPhySetPulleyJointDistance.l
  dbPhySetPulleyJointStiffness.l : dbPhySetPulleyJointRatio.l : dbPhySetPulleyJointRigid.l : dbPhySetPulleyJointMotor.l
  dbPhyBuildPulleyJoint.l : dbPhyMakeScene.l : dbPhySetCurrentScene.l : dbPhySetRevoluteJointLocalAnchor.l
  dbPhySetRevoluteJointLocalAxis.l : dbPhySetRevoluteJointGlobalAnchor.l : dbPhySetRevoluteJointGlobalAxis.l : dbPhySetRevoluteJointSpring.l
  dbPhySetRevoluteJointLimit.l : dbPhySetRevoluteJointMotor.l : dbPhySetRevoluteJointProjection.l : dbPhyBuildRevoluteJoint.l
  dbPhyMakeSphereJoint.l : dbPhyMakeSphereJoint1.l : dbPhySetSphereJointLocalAnchor.l : dbPhySetSphereJointLocalAxis.l
  dbPhySetSphereJointGlobalAnchor.l : dbPhySetSphereJointGlobalAxis.l : dbPhySetSphereJointSwingAxis.l : dbPhySetSphereJointSwingLimit.l
  dbPhySetSphereJointTwistLimit.l : dbPhySetSphereJointTwistSpring.l : dbPhySetSphereJointSwingSpring.l : dbPhySetSphereJointSpring.l
  dbPhySetSphereJointProjection.l : dbPhyBuildSphereJoint.l : dbPhyDeleteJoint.l : dbPhyGetJointExist.l
  dbPhyGetJointType.l : dbPhyMakeMaterial.l : dbPhyDeleteMaterial.l : dbPhySetMaterialDynamicFriction.l
  dbPhySetMaterialStaticFriction.l : dbPhySetMaterialRestitution.l : dbPhySetMaterialDynamicFrictionV.l : dbPhySetMaterialStaticFrictionV.l
  dbPhySetMaterialDirOfAnisotropy.l : dbPhySetMaterialFrictionCombine.l : dbPhySetMaterialRestitutionCombine.l : dbPhyBuildMaterial.l
  dbPhyGetMaterialExist.l : dbPhyGetMaterialDynamicFrictionEx.l : dbPhyGetMaterialStaticFrictionEx.l : dbPhyGetMaterialRestitutionEx.l
  dbPhyGetMaterialDynamicFrictionVEx.l : dbPhyGetMaterialStaticFrictionVEx.l : dbPhyGetMaterialDirOfAnisotropyXEx.l : dbPhyGetMaterialDirOfAnisotropyYEx.l
  dbPhyGetMaterialDirOfAnisotropyZEx.l : dbPhyGetMaterialFrictionCombine.l : dbPhyGetMaterialRestitutionCombine.l : dbPhySetRigidBodyPosition.l
  dbPhySetRigidBodyRotation.l : dbPhySetRigidBodyMass.l : dbPhyGetRigidBodyMassEx.l : dbPhySetRigidBodyMassOffsetLocal.l
  dbPhySetRigidBodyMassOffsetGlobal.l : dbPhyUpdateRigidBodyMass.l : dbPhySetRigidBodyLinearDamping.l : dbPhySetRigidBodyAngularDamping.l
  dbPhyGetRigidBodyLinearDampingEx.l : dbPhyGetRigidBodyAngularDampingEx.l : dbPhySetRigidBodyLinearVelocity.l : dbPhySetRigidBodyAngularVelocity.l
  dbPhySetRigidBodyMaxAngularVelocity.l : dbPhyGetRigidBodyLinearVelocityXEx.l : dbPhyGetRigidBodyLinearVelocityYEx.l : dbPhyGetRigidBodyLinearVelocityZEx.l
  dbPhyGetRigidBodyAngularVelocityXEx.l : dbPhyGetRigidBodyAngularVelocityYEx.l : dbPhyGetRigidBodyAngularVelocityZEx.l : dbPhyGetRigidBodyMaxAngularVelocityEx.l
  dbPhySetRigidBodyCCDMotionThreshold.l : dbPhyGetRigidBodyCCDMotionThresholdEx.l : dbPhySetRigidBodyLinearMomentum.l : dbPhySetRigidBodyAngularMomentum.l
  dbPhyGetRigidBodyLinearMomentumXEx.l : dbPhyGetRigidBodyLinearMomentumYEx.l : dbPhyGetRigidBodyLinearMomentumZEx.l : dbPhyGetRigidBodyAngularMomentumXEx.l
  dbPhyGetRigidBodyAngularMomentumYEx.l : dbPhyGetRigidBodyAngularMomentumZEx.l : dbPhyAddRigidBodyForce.l : dbPhyAddRigidBodyForceAtLocal.l
  dbPhyAddRigidBodyLocalForce.l : dbPhyAddRigidBodyLocalForceAtLocal.l : dbPhyAddRigidBodyForce1.l : dbPhyAddRigidBodyLocalForce1.l
  dbPhyAddRigidBodyTorque.l : dbPhyAddRigidBodyLocalTorque.l : dbPhyGetRigidBodyPointVelocityXEx.l : dbPhyGetRigidBodyPointVelocityYEx.l
  dbPhyGetRigidBodyPointVelocityZEx.l : dbPhyGetRigidBodyLocalPointVelocityXEx.l : dbPhyGetRigidBodyLocalPointVelocityYEx.l : dbPhyGetRigidBodyLocalPointVelocityZEx.l
  dbPhySetRigidBodySleepLinearVelocity.l : dbPhySetRigidBodySleepAngularVelocity.l : dbPhyWakeUpRigidBody.l : dbPhyGetRigidBodySleeping.l
  dbPhyGetRigidBodySleepLinearVelocityEx.l : dbPhyGetRigidBodySleepAngularVelocityEx.l : dbPhySetRigidBodyKinematic.l : dbPhySetRigidBodyKinematicPosition.l
  dbPhySetRigidBodyKinematicRotation.l : dbPhyRayCastAllShapes.l : dbPhyGetRayCastHit.l : dbPhyGetRayCastHitPointXEx.l
  dbPhyGetRayCastHitPointYEx.l : dbPhyGetRayCastHitPointZEx.l : dbPhyGetRayCastHitNormalXEx.l : dbPhyGetRayCastHitNormalYEx.l
  dbPhyGetRayCastHitNormalZEx.l : dbPhyGetRayCastDistanceEx.l : dbPhyGetRayCastTU.l : dbPhyGetRayCastTV.l
  dbPhyGetRayCastObject.l : dbPhyMakeTriggerBox.l : dbPhyMakeTriggerSphere.l : dbPhyDeleteTrigger.l
  dbPhyTriggerExist.l : dbPhyTriggerType.l : dbPhyGetTriggerData.l : dbPhyGetTriggerObjectA.l
  dbPhyGetTriggerObjectB.l : dbPhyGetTriggerAction.l : dbPhyCreateVehicle.l : dbPhyAddVehicleBody.l
  dbPhyAddVehicleWheel.l : dbPhyBuildVehicle.l : dbPhySetVehicleMass.l : dbPhySetVehicleAuto.l
  dbPhySetVehicleMaxMotor.l : dbPhySetVehicleMotorForce.l : dbPhySetVehicleWheelPower.l : dbPhySetVehicleSteeringDelta.l
  dbPhySetVehicleMaxSteeringAngle.l : dbPhySetVehicleWheelRotation.l : dbPhySetVehicleSuspensionSpring.l : dbPhySetVehicleSuspensionDamping.l
  dbPhySetVehicleSuspensionBias.l : dbPhySetVehicleRestitution.l : dbPhySetVehicleStaticFriction.l : dbPhySetVehicleStaticFrictionV.l
  dbPhySetVehicleDynamicFriction.l : dbPhySetVehicleDynamicFrictionV.l : dbPhySetVehicleWheelMultiplier.l : dbPhySetVehicleSteeringAngle.l
  dbPhySetVehicleSteeringValue.l : dbPhyGetVehicleSteeringAngleEx.l : dbPhyGetVehicleSteeringDeltaEx.l : dbPhyGetVehicleMotorForceEx.l
  dbPhyMakeRevoluteJoint.l : dbPhyMakeRevoluteJoint1.l : dbPhyMakeRigidBodyStaticConvex2.l : dbPhyMakeRigidBodyStaticConvexes2.l
  dbPhyMakeRigidBodyStaticConvex3.l : dbPhyMakeRigidBodyStaticConvexes3.l : dbPhyMakeRigidBodyDynamicConvex2.l : dbPhyMakeRigidBodyDynamicConvexes2.l
  dbPhyMakeRigidBodyDynamicConvex3.l : dbPhyMakeRigidBodyDynamicConvexes3.l : dbPhySetJointBreakLimits.l : dbPhySetEmitterCollision.l
  dbPhySetEmitterCollisionScale.l : dbPhyUpdate1.l : dbPhySetGroundPlane.l : dbPhySetRigidBodyGravity.l
  dbPhySetRigidBodyGroup.l : dbPhySleepRigidBody.l : dbPhySetGroupCollision.l : dbPhySetEmitterRate.l
  dbPhySetEmitterUpdate.l : dbPhySetFluidScreenSpacing.l : dbPhySetFluidTriangleWinding.l : dbPhySetFluidThreshold.l
  dbPhySetFluidParticleRadius.l : dbPhySetFluidDepthSmoothing.l : dbPhySetFluidSilhouetteSmoothing.l : dbPhyMakeRigidBodyStaticTerrain.l
  dbPhyMakeRigidBodyStaticTerrain1.l : dbPhyMakeRigidBodyStaticTerrain2.l : dbPhyMakeRigidBodyStaticTerrain3.l : dbPhyLoadRigidBodyStaticTerrain.l
  dbPhyLoadRigidBodyStaticTerrain1.l : dbPhySetCharacterControllerDisplacement.l : dbPhySetCharacterControllerDisplacement1.l : dbPhySetCharacterControllerDisplacement2.l
  dbPhySetCharacterControllerSharpness.l : dbPhySetCharacterControllerExtents.l : dbPhySetCharacterControllerExtents1.l : dbPhySetCharacterControllerMinDistance.l
  dbPhySetVehicleBrakeTorque1.l : dbPhySetVehicleMotorTorque.l : dbPhySetVehicleSteeringAngle1.l : dbPhySetVehicleWheelRadius.l
  dbPhySetVehicleSuspensionTravel.l : dbPhySetVehicleLongitudalTireForceFunction.l : dbPhySetVehicleLateralTireForceFunction.l : dbPhySetVehicleWheelFlags.l
  SpaceSPARE01.l : SpaceSPARE02.l : SpaceSPARE03.l : SpaceSPARE04.l
  SpaceSPARE05.l : SpaceSPARE06.l : SpaceSPARE07.l : SpaceSPARE08.l
  SpaceSPARE09.l : SpaceSPARE10.l : SpaceSPARE11.l : SpaceSPARE12.l
  SpaceSPARE13.l : SpaceSPARE14.l : SpaceSPARE15.l : SpaceSPARE16.l
 EndStructure

; IDE Options = PureBasic 4.10 Beta 2 (Windows - x86)
; CursorPosition = 135
; FirstLine = 95
; Folding = -