; DarkBasic Professional RC2PBIncludes Ver 1.0 File - COMMANDS INITIALIZING
; By Frederic Cordier - 07.02.13
;
Procedure.l CheckDarkPhysics()
  SUCCESS.l = 1
  If OpenLibrary( 1, "DarkPhysics.dll")
    DB_DarkPhysics\dbPhyAttachClothToShape= AIsFunction( 1 , "?dbPhyAttachClothToShape@@YAXHHH@Z" ) ; 105 PHY ATTACH CLOTH TO SHAPE 
    DB_DarkPhysics\dbPhyAttachClothToAllShapes= AIsFunction( 1 , "?dbPhyAttachClothToAllShapes@@YAXHH@Z" ) ; 2 PHY ATTACH CLOTH TO ALL SHAPES 
    DB_DarkPhysics\dbPhyDetachClothFromShape= AIsFunction( 1 , "?dbPhyDetachClothFromShape@@YAXHH@Z" ) ; 3 PHY DETACH CLOTH FROM SHAPE 
    DB_DarkPhysics\dbPhyAttachClothVertex= AIsFunction( 1 , "?dbPhyAttachClothVertex@@YAXHHMMM@Z" ) ; 4 PHY ATTACH CLOTH VERTEX 
    DB_DarkPhysics\dbPhyAttachClothVertexToShape= AIsFunction( 1 , "?dbPhyAttachClothVertexToShape@@YAXHHHMMMH@Z" ) ; 5 PHY ATTACH CLOTH VERTEX TO SHAPE 
    DB_DarkPhysics\dbPhyFreeClothVertex= AIsFunction( 1 , "?dbPhyFreeClothVertex@@YAXHH@Z" ) ; 6 PHY FREE CLOTH VERTEX 
    DB_DarkPhysics\dbPhyMakeCloth= AIsFunction( 1 , "?dbPhyMakeCloth@@YAXH@Z" ) ; 7 PHY MAKE CLOTH 
    DB_DarkPhysics\dbPhyMakeClothFromObject= AIsFunction( 1 , "?dbPhyMakeClothFromObject@@YAXHH@Z" ) ; 8 PHY MAKE CLOTH FROM OBJECT 
    DB_DarkPhysics\dbPhyMakeClothFromLimb= AIsFunction( 1 , "?dbPhyMakeClothFromLimb@@YAXHHH@Z" ) ; 9 PHY MAKE CLOTH FROM LIMB 
    DB_DarkPhysics\dbPhyBuildCloth= AIsFunction( 1 , "?dbPhyBuildCloth@@YAXH@Z" ) ; 10 PHY BUILD CLOTH 
    DB_DarkPhysics\dbPhySetClothDimensions= AIsFunction( 1 , "?dbPhySetClothDimensions@@YAXHMMM@Z" ) ; 11 PHY SET CLOTH DIMENSIONS 
    DB_DarkPhysics\dbPhySetClothPosition= AIsFunction( 1 , "?dbPhySetClothPosition@@YAXHMMM@Z" ) ; 12 PHY SET CLOTH POSITION 
    DB_DarkPhysics\dbPhySetClothRotation= AIsFunction( 1 , "?dbPhySetClothRotation@@YAXHMMM@Z" ) ; 13 PHY SET CLOTH ROTATION 
    DB_DarkPhysics\dbPhySetClothStatic= AIsFunction( 1 , "?dbPhySetClothStatic@@YAXHH@Z" ) ; 14 PHY SET CLOTH STATIC 
    DB_DarkPhysics\dbPhySetClothCollision= AIsFunction( 1 , "?dbPhySetClothCollision@@YAXHH@Z" ) ; 15 PHY SET CLOTH COLLISION 
    DB_DarkPhysics\dbPhySetClothGravity= AIsFunction( 1 , "?dbPhySetClothGravity@@YAXHH@Z" ) ; 16 PHY SET CLOTH GRAVITY 
    DB_DarkPhysics\dbPhySetClothBending= AIsFunction( 1 , "?dbPhySetClothBending@@YAXHH@Z" ) ; 17 PHY SET CLOTH BENDING 
    DB_DarkPhysics\dbPhySetClothDamping= AIsFunction( 1 , "?dbPhySetClothDamping@@YAXHH@Z" ) ; 18 PHY SET CLOTH DAMPING 
    DB_DarkPhysics\dbPhySetClothTwoWayCollision= AIsFunction( 1 , "?dbPhySetClothTwoWayCollision@@YAXHH@Z" ) ; 20 PHY SET CLOTH TWO WAY COLLISION 
    DB_DarkPhysics\dbPhySetClothTearing= AIsFunction( 1 , "?dbPhySetClothTearing@@YAXHH@Z" ) ; 21 PHY SET CLOTH TEARING 
    DB_DarkPhysics\dbPhySetClothThickness= AIsFunction( 1 , "?dbPhySetClothThickness@@YAXHM@Z" ) ; 22 PHY SET CLOTH THICKNESS 
    DB_DarkPhysics\dbPhySetClothDensity= AIsFunction( 1 , "?dbPhySetClothDensity@@YAXHM@Z" ) ; 23 PHY SET CLOTH DENSITY 
    DB_DarkPhysics\dbPhySetClothBendingStiffness= AIsFunction( 1 , "?dbPhySetClothBendingStiffness@@YAXHM@Z" ) ; 24 PHY SET CLOTH BENDING STIFFNESS 
    DB_DarkPhysics\dbPhySetClothStretchingStiffness= AIsFunction( 1 , "?dbPhySetClothStretchingStiffness@@YAXHM@Z" ) ; 25 PHY SET CLOTH STRETCHING STIFFNESS 
    DB_DarkPhysics\dbPhySetClothFriction= AIsFunction( 1 , "?dbPhySetClothFriction@@YAXHM@Z" ) ; 26 PHY SET CLOTH FRICTION 
    DB_DarkPhysics\dbPhySetClothPressure= AIsFunction( 1 , "?dbPhySetClothPressure@@YAXHM@Z" ) ; 27 PHY SET CLOTH PRESSURE 
    DB_DarkPhysics\dbPhySetClothTearFactor= AIsFunction( 1 , "?dbPhySetClothTearFactor@@YAXHM@Z" ) ; 28 PHY SET CLOTH TEAR FACTOR 
    DB_DarkPhysics\dbPhySetClothCollisionResponseCoefficient= AIsFunction( 1 , "?dbPhySetClothCollisionResponseCoefficient@@YAXHM@Z" ) ; 29 PHY SET CLOTH COLLISION RESPONSE COEFFICIENT 
    DB_DarkPhysics\dbPhySetClothAttachmentResponseCoefficient= AIsFunction( 1 , "?dbPhySetClothAttachmentResponseCoefficient@@YAXHM@Z" ) ; 30 PHY SET CLOTH ATTACHMENT RESPONSE COEFFICIENT 
    DB_DarkPhysics\dbPhySetClothSolverIterations= AIsFunction( 1 , "?dbPhySetClothSolverIterations@@YAXHH@Z" ) ; 31 PHY SET CLOTH SOLVER ITERATIONS 
    DB_DarkPhysics\dbPhySetClothExternalAcceleration= AIsFunction( 1 , "?dbPhySetClothExternalAcceleration@@YAXHMMM@Z" ) ; 32 PHY SET CLOTH EXTERNAL ACCELERATION 
    DB_DarkPhysics\dbPhySetClothCollisionGroup= AIsFunction( 1 , "?dbPhySetClothCollisionGroup@@YAXHH@Z" ) ; 33 PHY SET CLOTH COLLISION GROUP 
    DB_DarkPhysics\dbPhyAddForceAtClothVertex= AIsFunction( 1 , "?dbPhyAddForceAtClothVertex@@YAXHHMMMH@Z" ) ; 34 PHY ADD FORCE AT CLOTH VERTEX 
    DB_DarkPhysics\dbPhyGetClothExist= AIsFunction( 1 , "?dbPhyGetClothExist@@YAHH@Z" ) ; 35 PHY GET CLOTH EXIST 
    DB_DarkPhysics\dbPhyGetClothBuilt= AIsFunction( 1 , "?dbPhyGetClothBuilt@@YAHH@Z" ) ; 36 PHY GET CLOTH BUILT 
    DB_DarkPhysics\dbPhyGetClothWidthEx= AIsFunction( 1 , "?dbPhyGetClothWidthEx@@YAKH@Z" ) ; 37 PHY GET CLOTH WIDTH 
    DB_DarkPhysics\dbPhyGetClothHeightEx= AIsFunction( 1 , "?dbPhyGetClothHeightEx@@YAKH@Z" ) ; 38 PHY GET CLOTH HEIGHT 
    DB_DarkPhysics\dbPhyGetClothDepthEx= AIsFunction( 1 , "?dbPhyGetClothDepthEx@@YAKH@Z" ) ; 39 PHY GET CLOTH DEPTH 
    DB_DarkPhysics\dbPhyGetClothPositionXEx= AIsFunction( 1 , "?dbPhyGetClothPositionXEx@@YAKH@Z" ) ; 40 PHY GET CLOTH POSITION X 
    DB_DarkPhysics\dbPhyGetClothPositionYEx= AIsFunction( 1 , "?dbPhyGetClothPositionYEx@@YAKH@Z" ) ; 41 PHY GET CLOTH POSITION Y 
    DB_DarkPhysics\dbPhyGetClothPositionZEx= AIsFunction( 1 , "?dbPhyGetClothPositionZEx@@YAKH@Z" ) ; 42 PHY GET CLOTH POSITION Z 
    DB_DarkPhysics\dbPhyGetClothRotationXEx= AIsFunction( 1 , "?dbPhyGetClothRotationXEx@@YAKH@Z" ) ; 43 PHY GET CLOTH ROTATION X 
    DB_DarkPhysics\dbPhyGetClothRotationYEx= AIsFunction( 1 , "?dbPhyGetClothRotationYEx@@YAKH@Z" ) ; 44 PHY GET CLOTH ROTATION Y 
    DB_DarkPhysics\dbPhyGetClothRotationZEx= AIsFunction( 1 , "?dbPhyGetClothRotationZEx@@YAKH@Z" ) ; 45 PHY GET CLOTH ROTATION Z 
    DB_DarkPhysics\dbPhyGetClothStatic= AIsFunction( 1 , "?dbPhyGetClothStatic@@YAHH@Z" ) ; 46 PHY GET CLOTH STATIC 
    DB_DarkPhysics\dbPhyGetClothCollision= AIsFunction( 1 , "?dbPhyGetClothCollision@@YAHH@Z" ) ; 47 PHY GET CLOTH COLLISION 
    DB_DarkPhysics\dbPhyGetClothGravity= AIsFunction( 1 , "?dbPhyGetClothGravity@@YAHH@Z" ) ; 48 PHY GET CLOTH GRAVITY 
    DB_DarkPhysics\dbPhyGetClothBending= AIsFunction( 1 , "?dbPhyGetClothBending@@YAHH@Z" ) ; 49 PHY GET CLOTH BENDING 
    DB_DarkPhysics\dbPhyGetClothDamping= AIsFunction( 1 , "?dbPhyGetClothDamping@@YAHH@Z" ) ; 50 PHY GET CLOTH DAMPING 
    DB_DarkPhysics\dbPhyGetClothTwoWayCollision= AIsFunction( 1 , "?dbPhyGetClothTwoWayCollision@@YAHH@Z" ) ; 51 PHY GET CLOTH TWO WAY COLLISION 
    DB_DarkPhysics\dbPhyGetClothTearing= AIsFunction( 1 , "?dbPhyGetClothTearing@@YAHH@Z" ) ; 52 PHY GET CLOTH TEARING 
    DB_DarkPhysics\dbPhyGetClothThicknessEx= AIsFunction( 1 , "?dbPhyGetClothThicknessEx@@YAKH@Z" ) ; 53 PHY GET CLOTH THICKNESS 
    DB_DarkPhysics\dbPhyGetClothDensityEx= AIsFunction( 1 , "?dbPhyGetClothDensityEx@@YAKH@Z" ) ; 54 PHY GET CLOTH DENSITY 
    DB_DarkPhysics\dbPhyGetClothBendingStiffnessEx= AIsFunction( 1 , "?dbPhyGetClothBendingStiffnessEx@@YAKH@Z" ) ; 55 PHY GET CLOTH BENDING STIFFNESS 
    DB_DarkPhysics\dbPhyGetClothStretchingStiffnessEx= AIsFunction( 1 , "?dbPhyGetClothStretchingStiffnessEx@@YAKH@Z" ) ; 56 PHY GET CLOTH STRETCHING STIFFNESS 
    DB_DarkPhysics\dbPhyGetClothFrictionEx= AIsFunction( 1 , "?dbPhyGetClothFrictionEx@@YAKH@Z" ) ; 57 PHY GET CLOTH FRICTION 
    DB_DarkPhysics\dbPhyGetClothPressureEx= AIsFunction( 1 , "?dbPhyGetClothPressureEx@@YAKH@Z" ) ; 58 PHY GET CLOTH PRESSURE 
    DB_DarkPhysics\dbPhyGetClothTearFactorEx= AIsFunction( 1 , "?dbPhyGetClothTearFactorEx@@YAKH@Z" ) ; 59 PHY GET CLOTH TEAR FACTOR 
    DB_DarkPhysics\dbPhyGetClothCollisionResponseCoefficientEx= AIsFunction( 1 , "?dbPhyGetClothCollisionResponseCoefficientEx@@YAKH@Z" ) ; 60 PHY GET CLOTH COLLISION RESPONSE COEFFICIENT 
    DB_DarkPhysics\dbPhyGetClothAttachmentResponseCoefficientEx= AIsFunction( 1 , "?dbPhyGetClothAttachmentResponseCoefficientEx@@YAKH@Z" ) ; 61 PHY GET CLOTH ATTACHMENT RESPONSE COEFFICIENT 
    DB_DarkPhysics\dbPhyGetClothSolverIterations= AIsFunction( 1 , "?dbPhyGetClothSolverIterations@@YAHH@Z" ) ; 62 PHY GET CLOTH SOLVER ITERATIONS 
    DB_DarkPhysics\dbPhyGetClothExternalAccelerationXEx= AIsFunction( 1 , "?dbPhyGetClothExternalAccelerationXEx@@YAKH@Z" ) ; 63 PHY GET CLOTH EXTERNAL ACCLERATION X 
    DB_DarkPhysics\dbPhyGetClothExternalAccelerationYEx= AIsFunction( 1 , "?dbPhyGetClothExternalAccelerationYEx@@YAKH@Z" ) ; 64 PHY GET CLOTH EXTERNAL ACCLERATION Y 
    DB_DarkPhysics\dbPhyGetClothExternalAccelerationZEx= AIsFunction( 1 , "?dbPhyGetClothExternalAccelerationZEx@@YAKH@Z" ) ; 65 PHY GET CLOTH EXTERNAL ACCLERATION Z 
    DB_DarkPhysics\dbPhyGetClothCollisionGroup= AIsFunction( 1 , "?dbPhyGetClothCollisionGroup@@YAHH@Z" ) ; 66 PHY GET CLOTH COLLISION GROUP 
    DB_DarkPhysics\dbPhyGetClothMinSizeXEx= AIsFunction( 1 , "?dbPhyGetClothMinSizeXEx@@YAKH@Z" ) ; 67 PHY GET CLOTH MIN SIZE X 
    DB_DarkPhysics\dbPhyGetClothMinSizeYEx= AIsFunction( 1 , "?dbPhyGetClothMinSizeYEx@@YAKH@Z" ) ; 68 PHY GET CLOTH MIN SIZE Y 
    DB_DarkPhysics\dbPhyGetClothMinSizeZEx= AIsFunction( 1 , "?dbPhyGetClothMinSizeZEx@@YAKH@Z" ) ; 69 PHY GET CLOTH MIN SIZE Z 
    DB_DarkPhysics\dbPhyGetClothMaxSizeXEx= AIsFunction( 1 , "?dbPhyGetClothMaxSizeXEx@@YAKH@Z" ) ; 70 PHY GET CLOTH MAX SIZE X 
    DB_DarkPhysics\dbPhyGetClothMaxSizeYEx= AIsFunction( 1 , "?dbPhyGetClothMaxSizeYEx@@YAKH@Z" ) ; 71 PHY GET CLOTH MAX SIZE Y 
    DB_DarkPhysics\dbPhyGetClothMaxSizeZEx= AIsFunction( 1 , "?dbPhyGetClothMaxSizeZEx@@YAKH@Z" ) ; 72 PHY GET CLOTH MAX SIZE Z 
    DB_DarkPhysics\dbPhyClothRayCast= AIsFunction( 1 , "?dbPhyClothRayCast@@YAHHMMMMMM@Z" ) ; 73 PHY CLOTH RAY CAST 
    DB_DarkPhysics\dbPhyClothRayCastHitX= AIsFunction( 1 , "?dbPhyClothRayCastHitX@@YAMH@Z" ) ; 74 PHY CLOTH RAY CAST HIT X 
    DB_DarkPhysics\dbPhyClothRayCastHitY= AIsFunction( 1 , "?dbPhyClothRayCastHitY@@YAMH@Z" ) ; 75 PHY CLOTH RAY CAST HIT Y 
    DB_DarkPhysics\dbPhyClothRayCastHitZ= AIsFunction( 1 , "?dbPhyClothRayCastHitZ@@YAMH@Z" ) ; 76 PHY CLOTH RAY CAST HIT Z 
    DB_DarkPhysics\dbPhyClothRayCastHitVertex= AIsFunction( 1 , "?dbPhyClothRayCastHitVertex@@YAHH@Z" ) ; 77 PHY CLOTH RAY CAST HIT VERTEX 
    DB_DarkPhysics\dbPhySetGravity= AIsFunction( 1 , "?dbPhySetGravity@@YAXMMM@Z" ) ; 78 PHY SET GRAVITY 
    DB_DarkPhysics\dbPhySetTiming= AIsFunction( 1 , "?dbPhySetTiming@@YAXMHH@Z" ) ; 79 PHY SET TIMING 
    DB_DarkPhysics\dbPhySetFixedTiming= AIsFunction( 1 , "?dbPhySetFixedTiming@@YAXM@Z" ) ; 80 PHY SET FIXED TIMING 
    DB_DarkPhysics\dbPhySetAutoFixedTiming= AIsFunction( 1 , "?dbPhySetAutoFixedTiming@@YAXXZ" ) ; 81 PHY SET AUTO FIXED TIMING 
    DB_DarkPhysics\dbPhySetSkinWidth= AIsFunction( 1 , "?dbPhySetSkinWidth@@YAXM@Z" ) ; 82 PHY SET SKIN WIDTH 
    DB_DarkPhysics\dbPhySetDefaultSleepLinearVelocitySquared= AIsFunction( 1 , "?dbPhySetDefaultSleepLinearVelocitySquared@@YAXM@Z" ) ; 83 PHY SET DEFAULT SLEEP LINEAR VELOCITY SQUARED 
    DB_DarkPhysics\dbPhySetDefaultSleepAngularVelocitySquared= AIsFunction( 1 , "?dbPhySetDefaultSleepAngularVelocitySquared@@YAXM@Z" ) ; 84 PHY SET DEFAULT SLEEP ANGULAR VELOCITY SQUARED 
    DB_DarkPhysics\dbPhySetBounceThreshold= AIsFunction( 1 , "?dbPhySetBounceThreshold@@YAXM@Z" ) ; 85 PHY SET BOUNCE THRESHOLD 
    DB_DarkPhysics\dbPhySetDynamicFriction= AIsFunction( 1 , "?dbPhySetDynamicFriction@@YAXM@Z" ) ; 86 PHY SET DYNAMIC FRICTION 
    DB_DarkPhysics\dbPhySetStaticFriction= AIsFunction( 1 , "?dbPhySetStaticFriction@@YAXM@Z" ) ; 87 PHY SET STATIC FRICTION 
    DB_DarkPhysics\dbPhySetMaxAngularVelocity= AIsFunction( 1 , "?dbPhySetMaxAngularVelocity@@YAXM@Z" ) ; 88 PHY SET MAX ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhySetContinuousCD= AIsFunction( 1 , "?dbPhySetContinuousCD@@YAXM@Z" ) ; 89 PHY SET CONTINUOUS CD 
    DB_DarkPhysics\dbPhySetAdaptiveForce= AIsFunction( 1 , "?dbPhySetAdaptiveForce@@YAXM@Z" ) ; 90 PHY SET ADAPTIVE FORCE 
    DB_DarkPhysics\dbPhySetControlledFiltering= AIsFunction( 1 , "?dbPhySetControlledFiltering@@YAXM@Z" ) ; 91 PHY SET CONTROLLED FILTERING 
    DB_DarkPhysics\dbPhySetTriggerCallback= AIsFunction( 1 , "?dbPhySetTriggerCallback@@YAXM@Z" ) ; 92 PHY SET TRIGGER CALLBACK 
    DB_DarkPhysics\dbPhyEnableDebug= AIsFunction( 1 , "?dbPhyEnableDebug@@YAXXZ" ) ; 93 PHY ENABLE DEBUG 
    DB_DarkPhysics\dbPhyStart= AIsFunction( 1 , "?dbPhyStart@@YAXXZ" ) ; 94 PHY START 
    DB_DarkPhysics\dbPhyStart1= AIsFunction( 1 , "?dbPhyStart@@YAXHHH@Z" ) ; 95 PHY START 
    DB_DarkPhysics\dbPhyEnd= AIsFunction( 1 , "?dbPhyEnd@@YAXXZ" ) ; 96 PHY END 
    DB_DarkPhysics\dbPhyClear= AIsFunction( 1 , "?dbPhyClear@@YAXXZ" ) ; 97 PHY CLEAR 
    DB_DarkPhysics\dbPhysX= AIsFunction( 1 , "?dbPhysX@@YAHXZ" ) ; 98 PHYSX 
    DB_DarkPhysics\dbPhyUpdate= AIsFunction( 1 , "?dbPhyUpdate@@YAXXZ" ) ; 99 PHY UPDATE 
    DB_DarkPhysics\dbPhyMakeFluid= AIsFunction( 1 , "?dbPhyMakeFluid@@YAXH@Z" ) ; 100 PHY MAKE FLUID 
    DB_DarkPhysics\dbPhyMakeFluidEmitter= AIsFunction( 1 , "?dbPhyMakeFluidEmitter@@YAXH@Z" ) ; 101 PHY MAKE FLUID EMITTER 
    DB_DarkPhysics\dbPhyBuildFluid= AIsFunction( 1 , "?dbPhyBuildFluid@@YAXH@Z" ) ; 102 PHY BUILD FLUID 
    DB_DarkPhysics\dbPhyDeleteFluid= AIsFunction( 1 , "?dbPhyDeleteFluid@@YAXH@Z" ) ; 103 PHY DELETE FLUID 
    DB_DarkPhysics\dbPhyGetFluidExist= AIsFunction( 1 , "?dbPhyGetFluidExist@@YAHH@Z" ) ; 104 PHY GET FLUID EXIST 
    DB_DarkPhysics\dbPhyMakeBoxDrain= AIsFunction( 1 , "?dbPhyMakeBoxDrain@@YAXHMMMMMMMMM@Z" ) ; 106 PHY MAKE BOX DRAIN 
    DB_DarkPhysics\dbPhyMakeSphereDrain= AIsFunction( 1 , "?dbPhyMakeSphereDrain@@YAXHMMMM@Z" ) ; 107 PHY MAKE SPHERE DRAIN 
    DB_DarkPhysics\dbPhyDeleteDrain= AIsFunction( 1 , "?dbPhyDeleteDrain@@YAXH@Z" ) ; 108 PHY DELETE DRAIN 
    DB_DarkPhysics\dbPhyGetDrainExist= AIsFunction( 1 , "?dbPhyGetDrainExist@@YAHH@Z" ) ; 109 PHY GET DRAIN EXIST 
    DB_DarkPhysics\dbPhySetFluidParticleBufferCap= AIsFunction( 1 , "?dbPhySetFluidParticleBufferCap@@YAXHH@Z" ) ; 110 PHY SET FLUID PARTICLE BUFFER CAP 
    DB_DarkPhysics\dbPhySetFluidRestPerMetre= AIsFunction( 1 , "?dbPhySetFluidRestPerMetre@@YAXHM@Z" ) ; 111 PHY SET FLUID REST PER METERE 
    DB_DarkPhysics\dbPhySetFluidRadius= AIsFunction( 1 , "?dbPhySetFluidRadius@@YAXHM@Z" ) ; 112 PHY SET FLUID RADIUS 
    DB_DarkPhysics\dbPhySetFluidMotionLimit= AIsFunction( 1 , "?dbPhySetFluidMotionLimit@@YAXHM@Z" ) ; 113 PHY SET FLUID MOTION LIMIT 
    DB_DarkPhysics\dbPhySetFluidPacketSize= AIsFunction( 1 , "?dbPhySetFluidPacketSize@@YAXHH@Z" ) ; 114 PHY SET FLUID PACKET SIZE 
    DB_DarkPhysics\dbPhySetFluidPosition= AIsFunction( 1 , "?dbPhySetFluidPosition@@YAXHMMM@Z" ) ; 115 PHY SET FLUID POSITION 
    DB_DarkPhysics\dbPhySetFluidRotation= AIsFunction( 1 , "?dbPhySetFluidRotation@@YAXHMMM@Z" ) ; 116 PHY SET FLUID ROTATION 
    DB_DarkPhysics\dbPhySetFluidStiffness= AIsFunction( 1 , "?dbPhySetFluidStiffness@@YAXHM@Z" ) ; 117 PHY SET FLUID STIFFNESS 
    DB_DarkPhysics\dbPhySetFluidViscosity= AIsFunction( 1 , "?dbPhySetFluidViscosity@@YAXHM@Z" ) ; 118 PHY SET FLUID VISCOSITY 
    DB_DarkPhysics\dbPhySetFluidRestDensity= AIsFunction( 1 , "?dbPhySetFluidRestDensity@@YAXHM@Z" ) ; 119 PHY SET FLUID REST DENSITY 
    DB_DarkPhysics\dbPhySetFluidDamping= AIsFunction( 1 , "?dbPhySetFluidDamping@@YAXHM@Z" ) ; 120 PHY SET FLUID DAMPING 
    DB_DarkPhysics\dbPhySetFluidMethod= AIsFunction( 1 , "?dbPhySetFluidMethod@@YAXHH@Z" ) ; 121 PHY SET FLUID METHOD 
    DB_DarkPhysics\dbPhySetFluidAcceleration= AIsFunction( 1 , "?dbPhySetFluidAcceleration@@YAXHMMM@Z" ) ; 122 PHY SET FLUID ACCELERATION 
    DB_DarkPhysics\dbPhySetFluidEmitterType= AIsFunction( 1 , "?dbPhySetFluidEmitterType@@YAXHH@Z" ) ; 123 PHY SET FLUID EMITTER TYPE 
    DB_DarkPhysics\dbPhySetFluidEmitterMaxParticles= AIsFunction( 1 , "?dbPhySetFluidEmitterMaxParticles@@YAXHH@Z" ) ; 124 PHY SET FLUID EMITTER MAX PARTICLES 
    DB_DarkPhysics\dbPhySetFluidEmitterShape= AIsFunction( 1 , "?dbPhySetFluidEmitterShape@@YAXHH@Z" ) ; 125 PHY SET FLUID EMITTER SHAPE 
    DB_DarkPhysics\dbPhySetFluidEmitterDimensions= AIsFunction( 1 , "?dbPhySetFluidEmitterDimensions@@YAXHMM@Z" ) ; 126 PHY SET FLUID EMITTER DIMENSIONS 
    DB_DarkPhysics\dbPhySetFluidEmitterRandomPosition= AIsFunction( 1 , "?dbPhySetFluidEmitterRandomPosition@@YAXHMMM@Z" ) ; 127 PHY SET FLUID EMITTER RANDOM POSITION 
    DB_DarkPhysics\dbPhySetFluidEmitterRandomAngle= AIsFunction( 1 , "?dbPhySetFluidEmitterRandomAngle@@YAXHM@Z" ) ; 128 PHY SET FLUID EMITTER RANDOM ANGLE 
    DB_DarkPhysics\dbPhySetFluidEmitterVelocity= AIsFunction( 1 , "?dbPhySetFluidEmitterVelocity@@YAXHM@Z" ) ; 129 PHY SET FLUID EMITTER VELOCITY 
    DB_DarkPhysics\dbPhySetFluidEmitterRate= AIsFunction( 1 , "?dbPhySetFluidEmitterRate@@YAXHM@Z" ) ; 130 PHY SET FLUID EMITTER RATE 
    DB_DarkPhysics\dbPhySetFluidEmitterLifetime= AIsFunction( 1 , "?dbPhySetFluidEmitterLifetime@@YAXHM@Z" ) ; 131 PHY SET FLUID EMITTER LIFETIME 
    DB_DarkPhysics\dbPhySetFluidEmitterFlags= AIsFunction( 1 , "?dbPhySetFluidEmitterFlags@@YAXHH@Z" ) ; 132 PHY SET FLUID EMITTER FLAGS 
    DB_DarkPhysics\dbPhyMakeParticleEmitter= AIsFunction( 1 , "?dbPhyMakeParticleEmitter@@YAXHHMMMMMMMM@Z" ) ; 133 PHY MAKE PARTICLE EMITTER 
    DB_DarkPhysics\dbPhyMakeFireEmitter= AIsFunction( 1 , "?dbPhyMakeFireEmitter@@YAXHHMMM@Z" ) ; 134 PHY MAKE FIRE EMITTER 
    DB_DarkPhysics\dbPhyMakeSmokeEmitter= AIsFunction( 1 , "?dbPhyMakeSmokeEmitter@@YAXHHMMM@Z" ) ; 135 PHY MAKE SMOKE EMITTER 
    DB_DarkPhysics\dbPhyMakeSnowEmitter= AIsFunction( 1 , "?dbPhyMakeSnowEmitter@@YAXHHMMM@Z" ) ; 136 PHY MAKE SNOW EMITTER 
    DB_DarkPhysics\dbPhyDeleteEmitter= AIsFunction( 1 , "?dbPhyDeleteEmitter@@YAXH@Z" ) ; 137 PHY DELETE EMITTER 
    DB_DarkPhysics\dbPhySetEmitterLinearVelocity= AIsFunction( 1 , "?dbPhySetEmitterLinearVelocity@@YAXHMMM@Z" ) ; 138 PHY SET EMITTER LINEAR VELOCITY 
    DB_DarkPhysics\dbPhySetEmitterLinearVelocityRange= AIsFunction( 1 , "?dbPhySetEmitterLinearVelocityRange@@YAXHMMMMMM@Z" ) ; 139 PHY SET EMITTER LINEAR VELOCITY RANGE 
    DB_DarkPhysics\dbPhySetEmitterGravity= AIsFunction( 1 , "?dbPhySetEmitterGravity@@YAXHH@Z" ) ; 140 PHY SET EMITTER GRAVITY 
    DB_DarkPhysics\dbPhySetEmitterLifeSpan= AIsFunction( 1 , "?dbPhySetEmitterLifeSpan@@YAXHM@Z" ) ; 141 PHY SET EMITTER LIFE SPAN 
    DB_DarkPhysics\dbPhySetEmitterFade= AIsFunction( 1 , "?dbPhySetEmitterFade@@YAXHH@Z" ) ; 142 PHY SET EMITTER FADE 
    DB_DarkPhysics\dbPhySetEmitterSize= AIsFunction( 1 , "?dbPhySetEmitterSize@@YAXHM@Z" ) ; 143 PHY SET EMITTER SIZE 
    DB_DarkPhysics\dbPhySetEmitterMaxSize= AIsFunction( 1 , "?dbPhySetEmitterMaxSize@@YAXHM@Z" ) ; 144 PHY SET EMITTER MAX SIZE 
    DB_DarkPhysics\dbPhySetEmitterGrowthRate= AIsFunction( 1 , "?dbPhySetEmitterGrowthRate@@YAXHM@Z" ) ; 145 PHY SET EMITTER GROWTH RATE 
    DB_DarkPhysics\dbPhySetEmitterRange= AIsFunction( 1 , "?dbPhySetEmitterRange@@YAXHMMMMMM@Z" ) ; 146 PHY SET EMITTER RANGE 
    DB_DarkPhysics\dbPhySetEmitterStartColor= AIsFunction( 1 , "?dbPhySetEmitterStartColor@@YAXHKKK@Z" ) ; 147 PHY SET EMITTER START COLOR 
    DB_DarkPhysics\dbPhySetEmitterEndColor= AIsFunction( 1 , "?dbPhySetEmitterEndColor@@YAXHKKK@Z" ) ; 148 PHY SET EMITTER END COLOR 
    DB_DarkPhysics\dbPhySetEmitterPosition= AIsFunction( 1 , "?dbPhySetEmitterPosition@@YAXHMMM@Z" ) ; 149 PHY SET EMITTER POSITION 
    DB_DarkPhysics\dbPhyGetEmitterExist= AIsFunction( 1 , "?dbPhyGetEmitterExist@@YAHH@Z" ) ; 150 PHY GET EMITTER EXIST 
    DB_DarkPhysics\dbPhyMakeBoxCharacterController= AIsFunction( 1 , "?dbPhyMakeBoxCharacterController@@YAXHMMMMMMHMM@Z" ) ; 151 PHY MAKE BOX CHARACTER CONTROLLER 
    DB_DarkPhysics\dbPhyMakeCapsuleCharacterController= AIsFunction( 1 , "?dbPhyMakeCapsuleCharacterController@@YAXHMMMMMHMM@Z" ) ; 152 PHY MAKE CAPSULE CHARACTER CONTROLLER 
    DB_DarkPhysics\dbPhyMoveCharacterController= AIsFunction( 1 , "?dbPhyMoveCharacterController@@YAXHM@Z" ) ; 153 PHY MOVE CHARACTER CONTROLLER 
    DB_DarkPhysics\dbPhyGetCharacterControllerExist= AIsFunction( 1 , "?dbPhyGetCharacterControllerExist@@YAHH@Z" ) ; 154 PHY GET CHARACTER CONTROLLER EXIST 
    DB_DarkPhysics\dbPhyDeleteCharacterController= AIsFunction( 1 , "?dbPhyDeleteCharacterController@@YAXH@Z" ) ; 155 PHY DELETE CHARACTER CONTROLLER 
    DB_DarkPhysics\dbPhyGetCollisionData= AIsFunction( 1 , "?dbPhyGetCollisionData@@YAHXZ" ) ; 156 PHY GET COLLISION DATA 
    DB_DarkPhysics\dbPhyGetCollisionObjectA= AIsFunction( 1 , "?dbPhyGetCollisionObjectA@@YAHXZ" ) ; 157 PHY GET COLLISION OBJECT A 
    DB_DarkPhysics\dbPhyGetCollisionObjectB= AIsFunction( 1 , "?dbPhyGetCollisionObjectB@@YAHXZ" ) ; 158 PHY GET COLLISION OBJECT B 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticBox= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticBox@@YAXH@Z" ) ; 159 PHY MAKE RIGID BODY STATIC BOX 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticBoxes= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticBoxes@@YAXH@Z" ) ; 160 PHY MAKE RIGID BODY STATIC BOXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticBox1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticBox@@YAXHH@Z" ) ; 161 PHY MAKE RIGID BODY STATIC BOX 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticBoxes1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticBoxes@@YAXHH@Z" ) ; 162 PHY MAKE RIGID BODY STATIC BOXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicBox= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicBox@@YAXH@Z" ) ; 163 PHY MAKE RIGID BODY DYNAMIC BOX 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicBoxes= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicBoxes@@YAXH@Z" ) ; 164 PHY MAKE RIGID BODY DYNAMIC BOXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicBox1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicBox@@YAXHH@Z" ) ; 165 PHY MAKE RIGID BODY DYNAMIC BOX 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicBoxes1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicBoxes@@YAXHH@Z" ) ; 166 PHY MAKE RIGID BODY DYNAMIC BOXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticCapsule= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticCapsule@@YAXH@Z" ) ; 167 PHY MAKE RIGID BODY STATIC CAPSULE 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticCapsules= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticCapsules@@YAXH@Z" ) ; 168 PHY MAKE RIGID BODY STATIC CAPSULES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticCapsule1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticCapsule@@YAXHH@Z" ) ; 169 PHY MAKE RIGID BODY STATIC CAPSULE 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticCapsules1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticCapsules@@YAXHH@Z" ) ; 170 PHY MAKE RIGID BODY STATIC CAPSULES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicCapsule= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicCapsule@@YAXH@Z" ) ; 171 PHY MAKE RIGID BODY DYNAMIC CAPSULE 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicCapsules= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicCapsules@@YAXH@Z" ) ; 172 PHY MAKE RIGID BODY DYNAMIC CAPSULES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicCapsule1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicCapsule@@YAXHH@Z" ) ; 173 PHY MAKE RIGID BODY DYNAMIC CAPSULE 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicCapsules1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicCapsules@@YAXHH@Z" ) ; 174 PHY MAKE RIGID BODY DYNAMIC CAPSULES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvex= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvex@@YAXHPAD@Z" ) ; 175 PHY MAKE RIGID BODY STATIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvexes= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvexes@@YAXHPAD@Z" ) ; 176 PHY MAKE RIGID BODY STATIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvex1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvex@@YAXHPADH@Z" ) ; 177 PHY MAKE RIGID BODY STATIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvexes1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvexes@@YAXHPADH@Z" ) ; 178 PHY MAKE RIGID BODY STATIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvex= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvex@@YAXHPAD@Z" ) ; 179 PHY MAKE RIGID BODY DYNAMIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvexes= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvexes@@YAXHPAD@Z" ) ; 180 PHY MAKE RIGID BODY DYNAMIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvex1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvex@@YAXHPADH@Z" ) ; 181 PHY MAKE RIGID BODY DYNAMIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvexes1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvexes@@YAXHPADH@Z" ) ; 182 PHY MAKE RIGID BODY DYNAMIC CONVEXES 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticConvex= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticConvex@@YAXHPAD@Z" ) ; 183 PHY LOAD RIGID BODY STATIC CONVEX 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticConvexes= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticConvexes@@YAXHPAD@Z" ) ; 184 PHY LOAD RIGID BODY STATIC CONVEXES 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticConvex1= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticConvex@@YAXHPADH@Z" ) ; 185 PHY LOAD RIGID BODY STATIC CONVEX 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticConvexes1= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticConvexes@@YAXHPADH@Z" ) ; 186 PHY LOAD RIGID BODY STATIC CONVEXES 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicConvex= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicConvex@@YAXHPAD@Z" ) ; 187 PHY LOAD RIGID BODY DYNAMIC CONVEX 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicConvexes= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicConvexes@@YAXHPAD@Z" ) ; 188 PHY LOAD RIGID BODY DYNAMIC CONVEXES 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicConvex1= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicConvex@@YAXHPADH@Z" ) ; 189 PHY LOAD RIGID BODY DYNAMIC CONVEX 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicConvexes1= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicConvexes@@YAXHPADH@Z" ) ; 190 PHY LOAD RIGID BODY DYNAMIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMesh= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMesh@@YAXH@Z" ) ; 191 PHY MAKE RIGID BODY STATIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMeshes= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMeshes@@YAXH@Z" ) ; 192 PHY MAKE RIGID BODY STATIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMesh1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMesh@@YAXHH@Z" ) ; 193 PHY MAKE RIGID BODY STATIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMeshes1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMeshes@@YAXHH@Z" ) ; 194 PHY MAKE RIGID BODY STATIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMesh= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMesh@@YAXH@Z" ) ; 195 PHY MAKE RIGID BODY DYNAMIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMeshes= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMeshes@@YAXH@Z" ) ; 196 PHY MAKE RIGID BODY DYNAMIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMesh1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMesh@@YAXHH@Z" ) ; 197 PHY MAKE RIGID BODY DYNAMIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMeshes1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMeshes@@YAXHH@Z" ) ; 198 PHY MAKE RIGID BODY DYNAMIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMesh2= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMesh@@YAXHPAD@Z" ) ; 199 PHY MAKE RIGID BODY STATIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMeshes2= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMeshes@@YAXHPAD@Z" ) ; 200 PHY MAKE RIGID BODY STATIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMesh3= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMesh@@YAXHPADH@Z" ) ; 201 PHY MAKE RIGID BODY STATIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticMeshes3= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticMeshes@@YAXHPADH@Z" ) ; 202 PHY MAKE RIGID BODY STATIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMesh2= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMesh@@YAXHPAD@Z" ) ; 203 PHY MAKE RIGID BODY DYNAMIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMeshes2= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMeshes@@YAXHPAD@Z" ) ; 204 PHY MAKE RIGID BODY DYNAMIC MESHES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMesh3= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMesh@@YAXHPADH@Z" ) ; 205 PHY MAKE RIGID BODY DYNAMIC MESH 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicMeshes3= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicMeshes@@YAXHPADH@Z" ) ; 206 PHY MAKE RIGID BODY DYNAMIC MESHES 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticMesh= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticMesh@@YAXHPAD@Z" ) ; 207 PHY LOAD RIGID BODY STATIC MESH 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticMeshes= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticMeshes@@YAXHPAD@Z" ) ; 208 PHY LOAD RIGID BODY STATIC MESHES 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticMesh1= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticMesh@@YAXHPADH@Z" ) ; 209 PHY LOAD RIGID BODY STATIC MESH 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticMeshes1= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticMeshes@@YAXHPADH@Z" ) ; 210 PHY LOAD RIGID BODY STATIC MESHES 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicMesh= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicMesh@@YAXHPAD@Z" ) ; 211 PHY LOAD RIGID BODY DYNAMIC MESH 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicMeshes= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicMeshes@@YAXHPAD@Z" ) ; 212 PHY LOAD RIGID BODY DYNAMIC MESHES 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicMesh1= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicMesh@@YAXHPADH@Z" ) ; 213 PHY LOAD RIGID BODY DYNAMIC MESH 
    DB_DarkPhysics\dbPhyLoadRigidBodyDynamicMeshes1= AIsFunction( 1 , "?dbPhyLoadRigidBodyDynamicMeshes@@YAXHPADH@Z" ) ; 214 PHY LOAD RIGID BODY DYNAMIC MESHES 
    DB_DarkPhysics\dbPhyMakeRagdoll= AIsFunction( 1 , "?dbPhyMakeRagdoll@@YAXHHH@Z" ) ; 215 PHY MAKE RAG DOLL 
    DB_DarkPhysics\dbPhyAssignRagdollPart= AIsFunction( 1 , "?dbPhyAssignRagdollPart@@YAXHHHH@Z" ) ; 216 PHY ASSIGN RAG DOLL PART 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticSphere= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticSphere@@YAXH@Z" ) ; 217 PHY MAKE RIGID BODY STATIC SPHERE 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticSpheres= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticSpheres@@YAXH@Z" ) ; 218 PHY MAKE RIGID BODY STATIC SPHERES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticSphere1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticSphere@@YAXHH@Z" ) ; 219 PHY MAKE RIGID BODY STATIC SPHERE 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticSpheres1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticSpheres@@YAXHH@Z" ) ; 220 PHY MAKE RIGID BODY STATIC SPHERES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicSphere= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicSphere@@YAXH@Z" ) ; 221 PHY MAKE RIGID BODY DYNAMIC SPHERE 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicSpheres= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicSpheres@@YAXH@Z" ) ; 222 PHY MAKE RIGID BODY DYNAMIC SPHERES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicSphere1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicSphere@@YAXHH@Z" ) ; 223 PHY MAKE RIGID BODY DYNAMIC SPHERE 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicSpheres1= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicSpheres@@YAXHH@Z" ) ; 224 PHY MAKE RIGID BODY DYNAMIC SPHERES 
    DB_DarkPhysics\dbPhySetVehicleBrakeTorque= AIsFunction( 1 , "?dbPhySetVehicleBrakeTorque@@YAXHM@Z" ) ; 225 PHY SET VEHICLE BRAKE TORQUE 
    DB_DarkPhysics\dbPhySetRigidBodyTerrainExtent= AIsFunction( 1 , "?dbPhySetRigidBodyTerrainExtent@@YAXM@Z" ) ; 226 PHY SET RIGID BODY TERRAIN EXTENT 
    DB_DarkPhysics\dbPhySetRigidBodyCCD= AIsFunction( 1 , "?dbPhySetRigidBodyCCD@@YAXHH@Z" ) ; 227 PHY SET RIGID BODY CCD 
    DB_DarkPhysics\dbPhyGetRigidBodyDynamic= AIsFunction( 1 , "?dbPhyGetRigidBodyDynamic@@YAHH@Z" ) ; 228 PHY GET RIGID BODY DYNAMIC 
    DB_DarkPhysics\dbPhyDeleteRigidBody= AIsFunction( 1 , "?dbPhyDeleteRigidBody@@YAXH@Z" ) ; 229 PHY DELETE RIGID BODY 
    DB_DarkPhysics\dbPhyGetRigidBodyExist= AIsFunction( 1 , "?dbPhyGetRigidBodyExist@@YAHH@Z" ) ; 230 PHY GET RIGID BODY EXIST 
    DB_DarkPhysics\dbPhyGetRigidBodyType= AIsFunction( 1 , "?dbPhyGetRigidBodyType@@YAHH@Z" ) ; 231 PHY GET RIGID BODY TYPE 
    DB_DarkPhysics\dbPhyMake6DOFJoint= AIsFunction( 1 , "?dbPhyMake6DOFJoint@@YAXHHH@Z" ) ; 232 PHY MAKE 6DOF JOINT 
    DB_DarkPhysics\dbPhySet6DOFJointLocalAnchor= AIsFunction( 1 , "?dbPhySet6DOFJointLocalAnchor@@YAXHHMMM@Z" ) ; 233 PHY SET 6DOF JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySet6DOFJointLocalAxis= AIsFunction( 1 , "?dbPhySet6DOFJointLocalAxis@@YAXHHMMM@Z" ) ; 234 PHY SET 6DOF JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySet6DOFJointLocalNormal= AIsFunction( 1 , "?dbPhySet6DOFJointLocalNormal@@YAXHHMMM@Z" ) ; 235 PHY SET 6DOF JOINT LOCAL NORMAL 
    DB_DarkPhysics\dbPhySet6DOFJointGlobalAnchor= AIsFunction( 1 , "?dbPhySet6DOFJointGlobalAnchor@@YAXHHMMM@Z" ) ; 236 PHY SET 6DOF JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySet6DOFJointGlobalAxis= AIsFunction( 1 , "?dbPhySet6DOFJointGlobalAxis@@YAXHHMMM@Z" ) ; 237 PHY SET 6DOF JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhySet6DOFJointTwistMotion= AIsFunction( 1 , "?dbPhySet6DOFJointTwistMotion@@YAXHH@Z" ) ; 238 PHY SET 6DOF JOINT TWIST MOTION 
    DB_DarkPhysics\dbPhySet6DOFJointSwing1Motion= AIsFunction( 1 , "?dbPhySet6DOFJointSwing1Motion@@YAXHH@Z" ) ; 239 PHY SET 6DOF JOINT SWING1 MOTION 
    DB_DarkPhysics\dbPhySet6DOFJointSwing2Motion= AIsFunction( 1 , "?dbPhySet6DOFJointSwing2Motion@@YAXHH@Z" ) ; 240 PHY SET 6DOF JOINT SWING2 MOTION 
    DB_DarkPhysics\dbPhySet6DOFJointMotionX= AIsFunction( 1 , "?dbPhySet6DOFJointMotionX@@YAXHH@Z" ) ; 241 PHY SET 6DOF JOINT MOTION X 
    DB_DarkPhysics\dbPhySet6DOFJointMotionY= AIsFunction( 1 , "?dbPhySet6DOFJointMotionY@@YAXHH@Z" ) ; 242 PHY SET 6DOF JOINT MOTION Y 
    DB_DarkPhysics\dbPhySet6DOFJointMotionZ= AIsFunction( 1 , "?dbPhySet6DOFJointMotionZ@@YAXHH@Z" ) ; 243 PHY SET 6DOF JOINT MOTION Z 
    DB_DarkPhysics\dbPhySet6DOFJointLinearLimit= AIsFunction( 1 , "?dbPhySet6DOFJointLinearLimit@@YAXHMMMM@Z" ) ; 244 PHY SET 6DOF JOINT LINEAR LIMIT 
    DB_DarkPhysics\dbPhySet6DOFJointSwing1Limit= AIsFunction( 1 , "?dbPhySet6DOFJointSwing1Limit@@YAXHMMMM@Z" ) ; 245 PHY SET 6DOF JOINT SWING1 LIMIT 
    DB_DarkPhysics\dbPhySet6DOFJointSwing2Limit= AIsFunction( 1 , "?dbPhySet6DOFJointSwing2Limit@@YAXHMMMM@Z" ) ; 246 PHY SET 6DOF JOINT SWING2 LIMIT 
    DB_DarkPhysics\dbPhySet6DOFJointTwistLimit= AIsFunction( 1 , "?dbPhySet6DOFJointTwistLimit@@YAXHMMMMMMMM@Z" ) ; 247 PHY SET 6DOF JOINT TWIST LIMIT 
    DB_DarkPhysics\dbPhySet6DOFJointDriveX= AIsFunction( 1 , "?dbPhySet6DOFJointDriveX@@YAXHHMMM@Z" ) ; 248 PHY SET 6DOF JOINT DRIVE X 
    DB_DarkPhysics\dbPhySet6DOFJointDriveY= AIsFunction( 1 , "?dbPhySet6DOFJointDriveY@@YAXHHMMM@Z" ) ; 249 PHY SET 6DOF JOINT DRIVE Y 
    DB_DarkPhysics\dbPhySet6DOFJointDriveZ= AIsFunction( 1 , "?dbPhySet6DOFJointDriveZ@@YAXHHMMM@Z" ) ; 250 PHY SET 6DOF JOINT DRIVE Z 
    DB_DarkPhysics\dbPhySet6DOFJointTwistDrive= AIsFunction( 1 , "?dbPhySet6DOFJointTwistDrive@@YAXHHMMM@Z" ) ; 251 PHY SET 6DOF JOINT TWIST DRIVE 
    DB_DarkPhysics\dbPhySet6DOFJointSwingDrive= AIsFunction( 1 , "?dbPhySet6DOFJointSwingDrive@@YAXHHMMM@Z" ) ; 252 PHY SET 6DOF JOINT SWING DRIVE 
    DB_DarkPhysics\dbPhySet6DOFJointSlerpDrive= AIsFunction( 1 , "?dbPhySet6DOFJointSlerpDrive@@YAXHH@Z" ) ; 253 PHY SET 6DOF JOINT SLERP DRIVE 
    DB_DarkPhysics\dbPhySet6DOFJointDrivePosition= AIsFunction( 1 , "?dbPhySet6DOFJointDrivePosition@@YAXHMMM@Z" ) ; 254 PHY SET 6DOF JOINT DRIVE POSITION 
    DB_DarkPhysics\dbPhySet6DOFJointDriveRotation= AIsFunction( 1 , "?dbPhySet6DOFJointDriveRotation@@YAXHMMM@Z" ) ; 255 PHY SET 6DOF JOINT DRIVE ROTATION 
    DB_DarkPhysics\dbPhySet6DOFJointDriveLinearVelocity= AIsFunction( 1 , "?dbPhySet6DOFJointDriveLinearVelocity@@YAXHMMM@Z" ) ; 256 PHY SET 6DOF JOINT DRIVE LINEAR VELOCITY 
    DB_DarkPhysics\dbPhySet6DOFJointDriveAngularVelocity= AIsFunction( 1 , "?dbPhySet6DOFJointDriveAngularVelocity@@YAXHMMM@Z" ) ; 257 PHY SET 6DOF JOINT DRIVE ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhySet6DOFJointProjection= AIsFunction( 1 , "?dbPhySet6DOFJointProjection@@YAXHHM@Z" ) ; 258 PHY SET 6DOF JOINT PROJECTION 
    DB_DarkPhysics\dbPhySet6DOFJointSlerpDrive1= AIsFunction( 1 , "?dbPhySet6DOFJointSlerpDrive@@YAXHH@Z" ) ; 259 PHY SET 6DOF JOINT SLERP DRIVE 
    DB_DarkPhysics\dbPhySet6DOFJointGear= AIsFunction( 1 , "?dbPhySet6DOFJointGear@@YAXHH@Z" ) ; 260 PHY SET 6DOF JOINT JOINT GEAR 
    DB_DarkPhysics\dbPhyBuild6DOFJoint= AIsFunction( 1 , "?dbPhyBuild6DOFJoint@@YAXH@Z" ) ; 261 PHY BUILD 6DOF JOINT 
    DB_DarkPhysics\dbPhyMakeCylindricalJoint= AIsFunction( 1 , "?dbPhyMakeCylindricalJoint@@YAXHHHMMMMMM@Z" ) ; 262 PHY MAKE CYLINDRICAL JOINT 
    DB_DarkPhysics\dbPhyMakeCylindricalJoint1= AIsFunction( 1 , "?dbPhyMakeCylindricalJoint@@YAXHHH@Z" ) ; 263 PHY MAKE CYLINDRICAL JOINT 
    DB_DarkPhysics\dbPhySetCylindricalJointLocalAnchor= AIsFunction( 1 , "?dbPhySetCylindricalJointLocalAnchor@@YAXHHMMM@Z" ) ; 264 PHY SET CYLINDRICAL JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetCylindricalJointLocalAxis= AIsFunction( 1 , "?dbPhySetCylindricalJointLocalAxis@@YAXHHMMM@Z" ) ; 265 PHY SET CYLINDRICAL JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetCylindricalJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetCylindricalJointGlobalAnchor@@YAXHHMMM@Z" ) ; 266 PHY SET CYLINDRICAL JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetCylindricalJointGlobalAxis= AIsFunction( 1 , "?dbPhySetCylindricalJointGlobalAxis@@YAXHHMMM@Z" ) ; 267 PHY SET CYLINDRICAL JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhyBuildCylindricalJoint= AIsFunction( 1 , "?dbPhyBuildCylindricalJoint@@YAXH@Z" ) ; 268 PHY BUILD CYLINDRICAL JOINT 
    DB_DarkPhysics\dbPhyMakeDistanceJoint= AIsFunction( 1 , "?dbPhyMakeDistanceJoint@@YAXHHHMMMMM@Z" ) ; 269 PHY MAKE DISTANCE JOINT 
    DB_DarkPhysics\dbPhyMakeDistanceJoint1= AIsFunction( 1 , "?dbPhyMakeDistanceJoint@@YAXHHH@Z" ) ; 270 PHY MAKE DISTANCE JOINT 
    DB_DarkPhysics\dbPhySetDistanceJointLocalAnchor= AIsFunction( 1 , "?dbPhySetDistanceJointLocalAnchor@@YAXHHMMM@Z" ) ; 271 PHY SET DISTANCE JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetDistanceJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetDistanceJointGlobalAnchor@@YAXHHMMM@Z" ) ; 272 PHY SET DISTANCE JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetDistanceJointLocalAxis= AIsFunction( 1 , "?dbPhySetDistanceJointLocalAxis@@YAXHHMMM@Z" ) ; 273 PHY SET DISTANCE JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetDistanceJointGlobalAxis= AIsFunction( 1 , "?dbPhySetDistanceJointGlobalAxis@@YAXHHMMM@Z" ) ; 274 PHY SET DISTANCE JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhySetDistanceJointMax= AIsFunction( 1 , "?dbPhySetDistanceJointMax@@YAXHM@Z" ) ; 275 PHY SET DISTANCE JOINT MAX 
    DB_DarkPhysics\dbPhySetDistanceJointMin= AIsFunction( 1 , "?dbPhySetDistanceJointMin@@YAXHM@Z" ) ; 276 PHY SET DISTANCE JOINT MIN 
    DB_DarkPhysics\dbPhySetDistanceJointSpring= AIsFunction( 1 , "?dbPhySetDistanceJointSpring@@YAXHMMM@Z" ) ; 277 PHY SET DISTANCE JOINT SPRING 
    DB_DarkPhysics\dbPhyBuildDistanceJoint= AIsFunction( 1 , "?dbPhyBuildDistanceJoint@@YAXH@Z" ) ; 278 PHY BUILD DISTANCE JOINT 
    DB_DarkPhysics\dbPhyMakeFixedJoint= AIsFunction( 1 , "?dbPhyMakeFixedJoint@@YAXHHH@Z" ) ; 279 PHY MAKE FIXED JOINT 
    DB_DarkPhysics\dbPhyMakeFixedJoint1= AIsFunction( 1 , "?dbPhyMakeFixedJoint@@YAXHHHH@Z" ) ; 280 PHY MAKE FIXED JOINT 
    DB_DarkPhysics\dbPhyBuildFixedJoint= AIsFunction( 1 , "?dbPhyBuildFixedJoint@@YAXH@Z" ) ; 281 PHY BUILD FIXED JOINT 
    DB_DarkPhysics\dbPhyMakePointInPlaneJoint= AIsFunction( 1 , "?dbPhyMakePointInPlaneJoint@@YAXHHHMMMMMM@Z" ) ; 282 PHY MAKE POINT IN PLANE JOINT 
    DB_DarkPhysics\dbPhyMakePointInPlaneJoint1= AIsFunction( 1 , "?dbPhyMakePointInPlaneJoint@@YAXHHH@Z" ) ; 283 PHY MAKE POINT IN PLANE JOINT 
    DB_DarkPhysics\dbPhySetPointInPlaneJointLocalAnchor= AIsFunction( 1 , "?dbPhySetPointInPlaneJointLocalAnchor@@YAXHHMMM@Z" ) ; 284 PHY SET POINT IN PLANE LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetPointInPlaneJointLocalAxis= AIsFunction( 1 , "?dbPhySetPointInPlaneJointLocalAxis@@YAXHHMMM@Z" ) ; 285 PHY SET POINT IN PLANE LOCAL AXIS 
    DB_DarkPhysics\dbPhySetPointInPlaneJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetPointInPlaneJointGlobalAnchor@@YAXHHMMM@Z" ) ; 286 PHY SET POINT IN PLANE GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetPointInPlaneJointGlobalAxis= AIsFunction( 1 , "?dbPhySetPointInPlaneJointGlobalAxis@@YAXHHMMM@Z" ) ; 287 PHY SET POINT IN PLANE GLOBAL AXIS 
    DB_DarkPhysics\dbPhyBuildPointInPlaneJoint= AIsFunction( 1 , "?dbPhyBuildPointInPlaneJoint@@YAXH@Z" ) ; 288 PHY BUILD POINT IN PLANE JOINT 
    DB_DarkPhysics\dbPhyMakePointOnLineJoint= AIsFunction( 1 , "?dbPhyMakePointOnLineJoint@@YAXHHHMMMMMM@Z" ) ; 289 PHY MAKE POINT ON LINE JOINT 
    DB_DarkPhysics\dbPhyMakePointOnLineJoint1= AIsFunction( 1 , "?dbPhyMakePointOnLineJoint@@YAXHHH@Z" ) ; 290 PHY MAKE POINT ON LINE JOINT 
    DB_DarkPhysics\dbPhySetPointOnLineJointLocalAnchor= AIsFunction( 1 , "?dbPhySetPointOnLineJointLocalAnchor@@YAXHHMMM@Z" ) ; 291 PHY SET POINT ON LINE JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetPointOnLineJointLocalAxis= AIsFunction( 1 , "?dbPhySetPointOnLineJointLocalAxis@@YAXHHMMM@Z" ) ; 292 PHY SET POINT ON LINE JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetPointOnLineJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetPointOnLineJointGlobalAnchor@@YAXHHMMM@Z" ) ; 293 PHY SET POINT ON LINE JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetPointOnLineJointGlobalAxis= AIsFunction( 1 , "?dbPhySetPointOnLineJointGlobalAxis@@YAXHHMMM@Z" ) ; 294 PHY SET POINT ON LINE JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhyBuildPointOnLineJoint= AIsFunction( 1 , "?dbPhyBuildPointOnLineJoint@@YAXH@Z" ) ; 295 PHY BUILD POINT ON LINE JOINT 
    DB_DarkPhysics\dbPhyMakePrismaticJoint= AIsFunction( 1 , "?dbPhyMakePrismaticJoint@@YAXHHH@Z" ) ; 296 PHY MAKE PRISMATIC JOINT 
    DB_DarkPhysics\dbPhyMakePrismaticJoint1= AIsFunction( 1 , "?dbPhyMakePrismaticJoint@@YAXHHH@Z" ) ; 297 PHY MAKE PRISMATIC JOINT 
    DB_DarkPhysics\dbPhySetPrismaticJointLocalAnchor= AIsFunction( 1 , "?dbPhySetPrismaticJointLocalAnchor@@YAXHHMMM@Z" ) ; 298 PHY SET PRIMSATIC JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetPrismaticJointLocalAxis= AIsFunction( 1 , "?dbPhySetPrismaticJointLocalAxis@@YAXHHMMM@Z" ) ; 299 PHY SET PRIMSATIC JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetPrismaticJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetPrismaticJointGlobalAnchor@@YAXHHMMM@Z" ) ; 300 PHY SET PRIMSATIC JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetPrismaticJointGlobalAxis= AIsFunction( 1 , "?dbPhySetPrismaticJointGlobalAxis@@YAXHHMMM@Z" ) ; 301 PHY SET PRIMSATIC JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhyBuildPrismaticJoint= AIsFunction( 1 , "?dbPhyBuildPrismaticJoint@@YAXH@Z" ) ; 302 PHY BUILD PRIMSATIC JOINT 
    DB_DarkPhysics\dbPhyMakePulleyJoint= AIsFunction( 1 , "?dbPhyMakePulleyJoint@@YAXHHHMMMMMMMMMMMMMMM@Z" ) ; 303 PHY MAKE PULLEY JOINT 
    DB_DarkPhysics\dbPhyMakePulleyJoint1= AIsFunction( 1 , "?dbPhyMakePulleyJoint@@YAXHHH@Z" ) ; 304 PHY MAKE PULLEY JOINT 
    DB_DarkPhysics\dbPhySetPulleyJointLocalAnchor= AIsFunction( 1 , "?dbPhySetPulleyJointLocalAnchor@@YAXHHMMM@Z" ) ; 305 PHY SET PULLEY JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetPulleyJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetPulleyJointGlobalAnchor@@YAXHHMMM@Z" ) ; 306 PHY SET PULLEY JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetPulleyJointLocalAxis= AIsFunction( 1 , "?dbPhySetPulleyJointLocalAxis@@YAXHHMMM@Z" ) ; 307 PHY SET PULLEY JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetPulleyJointGlobalAxis= AIsFunction( 1 , "?dbPhySetPulleyJointGlobalAxis@@YAXHHMMM@Z" ) ; 308 PHY SET PULLEY JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhySetPulleyJointSuspension= AIsFunction( 1 , "?dbPhySetPulleyJointSuspension@@YAXHHMMM@Z" ) ; 309 PHY SET PULLEY JOINT SUSPENSION 
    DB_DarkPhysics\dbPhySetPulleyJointDistance= AIsFunction( 1 , "?dbPhySetPulleyJointDistance@@YAXHM@Z" ) ; 310 PHY SET PULLEY JOINT DISTANCE 
    DB_DarkPhysics\dbPhySetPulleyJointStiffness= AIsFunction( 1 , "?dbPhySetPulleyJointStiffness@@YAXHM@Z" ) ; 311 PHY SET PULLEY JOINT STIFFNESS 
    DB_DarkPhysics\dbPhySetPulleyJointRatio= AIsFunction( 1 , "?dbPhySetPulleyJointRatio@@YAXHM@Z" ) ; 312 PHY SET PULLEY JOINT RATIO 
    DB_DarkPhysics\dbPhySetPulleyJointRigid= AIsFunction( 1 , "?dbPhySetPulleyJointRigid@@YAXHH@Z" ) ; 313 PHY SET PULLEY JOINT RIGID 
    DB_DarkPhysics\dbPhySetPulleyJointMotor= AIsFunction( 1 , "?dbPhySetPulleyJointMotor@@YAXHH@Z" ) ; 314 PHY SET PULLEY JOINT MOTOR 
    DB_DarkPhysics\dbPhyBuildPulleyJoint= AIsFunction( 1 , "?dbPhyBuildPulleyJoint@@YAXH@Z" ) ; 315 PHY BUILD PULLEY JOINT 
    DB_DarkPhysics\dbPhyMakeScene= AIsFunction( 1 , "?dbPhyMakeScene@@YAXHHHH@Z" ) ; 316 PHY MAKE SCENE %
    DB_DarkPhysics\dbPhySetCurrentScene= AIsFunction( 1 , "?dbPhySetCurrentScene@@YAXH@Z" ) ; 317 PHY SET CURRENT SCENE 
    DB_DarkPhysics\dbPhySetRevoluteJointLocalAnchor= AIsFunction( 1 , "?dbPhySetRevoluteJointLocalAnchor@@YAXHHMMM@Z" ) ; 318 PHY SET REVOLUTE JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetRevoluteJointLocalAxis= AIsFunction( 1 , "?dbPhySetRevoluteJointLocalAxis@@YAXHHMMM@Z" ) ; 319 PHY SET REVOLUTE JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetRevoluteJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetRevoluteJointGlobalAnchor@@YAXHHMMM@Z" ) ; 320 PHY SET REVOLUTE JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetRevoluteJointGlobalAxis= AIsFunction( 1 , "?dbPhySetRevoluteJointGlobalAxis@@YAXHHMMM@Z" ) ; 321 PHY SET REVOLUTE JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhySetRevoluteJointSpring= AIsFunction( 1 , "?dbPhySetRevoluteJointSpring@@YAXHMM@Z" ) ; 322 PHY SET REVOLUTE JOINT SPRING 
    DB_DarkPhysics\dbPhySetRevoluteJointLimit= AIsFunction( 1 , "?dbPhySetRevoluteJointLimit@@YAXHMM@Z" ) ; 323 PHY SET REVOLUTE JOINT LIMIT 
    DB_DarkPhysics\dbPhySetRevoluteJointMotor= AIsFunction( 1 , "?dbPhySetRevoluteJointMotor@@YAXHMMH@Z" ) ; 324 PHY SET REVOLUTE JOINT MOTOR 
    DB_DarkPhysics\dbPhySetRevoluteJointProjection= AIsFunction( 1 , "?dbPhySetRevoluteJointProjection@@YAXHHMM@Z" ) ; 325 PHY SET REVOLUTE JOINT PROJECTION 
    DB_DarkPhysics\dbPhyBuildRevoluteJoint= AIsFunction( 1 , "?dbPhyBuildRevoluteJoint@@YAXH@Z" ) ; 326 PHY BUILD REVOLUTE JOINT 
    DB_DarkPhysics\dbPhyMakeSphereJoint= AIsFunction( 1 , "?dbPhyMakeSphereJoint@@YAXHHHMMM@Z" ) ; 327 PHY MAKE SPHERE JOINT 
    DB_DarkPhysics\dbPhyMakeSphereJoint1= AIsFunction( 1 , "?dbPhyMakeSphereJoint@@YAXHHH@Z" ) ; 328 PHY MAKE SPHERE JOINT 
    DB_DarkPhysics\dbPhySetSphereJointLocalAnchor= AIsFunction( 1 , "?dbPhySetSphereJointLocalAnchor@@YAXHHMMM@Z" ) ; 329 PHY SET SPHERE JOINT LOCAL ANCHOR 
    DB_DarkPhysics\dbPhySetSphereJointLocalAxis= AIsFunction( 1 , "?dbPhySetSphereJointLocalAxis@@YAXHHMMM@Z" ) ; 330 PHY SET SPHERE JOINT LOCAL AXIS 
    DB_DarkPhysics\dbPhySetSphereJointGlobalAnchor= AIsFunction( 1 , "?dbPhySetSphereJointGlobalAnchor@@YAXHHMMM@Z" ) ; 331 PHY SET SPHERE JOINT GLOBAL ANCHOR 
    DB_DarkPhysics\dbPhySetSphereJointGlobalAxis= AIsFunction( 1 , "?dbPhySetSphereJointGlobalAxis@@YAXHHMMM@Z" ) ; 332 PHY SET SPHERE JOINT GLOBAL AXIS 
    DB_DarkPhysics\dbPhySetSphereJointSwingAxis= AIsFunction( 1 , "?dbPhySetSphereJointSwingAxis@@YAXHMMM@Z" ) ; 333 PHY SET SPHERE JOINT SWING AXIS 
    DB_DarkPhysics\dbPhySetSphereJointSwingLimit= AIsFunction( 1 , "?dbPhySetSphereJointSwingLimit@@YAXHMMM@Z" ) ; 334 PHY SET SPHERE JOINT SWING LIMIT 
    DB_DarkPhysics\dbPhySetSphereJointTwistLimit= AIsFunction( 1 , "?dbPhySetSphereJointTwistLimit@@YAXHMM@Z" ) ; 335 PHY SET SPHERE JOINT TWIST LIMIT 
    DB_DarkPhysics\dbPhySetSphereJointTwistSpring= AIsFunction( 1 , "?dbPhySetSphereJointTwistSpring@@YAXHMM@Z" ) ; 336 PHY SET SPHERE JOINT TWIST SPRING 
    DB_DarkPhysics\dbPhySetSphereJointSwingSpring= AIsFunction( 1 , "?dbPhySetSphereJointSwingSpring@@YAXHMM@Z" ) ; 337 PHY SET SPHERE JOINT SWING SPRING 
    DB_DarkPhysics\dbPhySetSphereJointSpring= AIsFunction( 1 , "?dbPhySetSphereJointSpring@@YAXHMM@Z" ) ; 338 PHY SET SPHERE JOINT SPRING 
    DB_DarkPhysics\dbPhySetSphereJointProjection= AIsFunction( 1 , "?dbPhySetSphereJointProjection@@YAXHHM@Z" ) ; 339 PHY SET SPHERE JOINT PROJECTION 
    DB_DarkPhysics\dbPhyBuildSphereJoint= AIsFunction( 1 , "?dbPhyBuildSphereJoint@@YAXH@Z" ) ; 340 PHY BUILD SPHERE JOINT 
    DB_DarkPhysics\dbPhyDeleteJoint= AIsFunction( 1 , "?dbPhyDeleteJoint@@YAXH@Z" ) ; 341 PHY DELETE JOINT 
    DB_DarkPhysics\dbPhyGetJointExist= AIsFunction( 1 , "?dbPhyGetJointExist@@YAHH@Z" ) ; 342 PHY GET JOINT EXIST 
    DB_DarkPhysics\dbPhyGetJointType= AIsFunction( 1 , "?dbPhyGetJointType@@YAHH@Z" ) ; 343 PHY GET JOINT TYPE 
    DB_DarkPhysics\dbPhyMakeMaterial= AIsFunction( 1 , "?dbPhyMakeMaterial@@YAXHPAD@Z" ) ; 344 PHY MAKE MATERIAL 
    DB_DarkPhysics\dbPhyDeleteMaterial= AIsFunction( 1 , "?dbPhyDeleteMaterial@@YAXH@Z" ) ; 345 PHY DELETE MATERIAL 
    DB_DarkPhysics\dbPhySetMaterialDynamicFriction= AIsFunction( 1 , "?dbPhySetMaterialDynamicFriction@@YAXHM@Z" ) ; 346 PHY SET MATERIAL DYNAMIC FRICTION 
    DB_DarkPhysics\dbPhySetMaterialStaticFriction= AIsFunction( 1 , "?dbPhySetMaterialStaticFriction@@YAXHM@Z" ) ; 347 PHY SET MATERIAL STATIC FRICTION 
    DB_DarkPhysics\dbPhySetMaterialRestitution= AIsFunction( 1 , "?dbPhySetMaterialRestitution@@YAXHM@Z" ) ; 348 PHY SET MATERIAL RESTITUTION 
    DB_DarkPhysics\dbPhySetMaterialDynamicFrictionV= AIsFunction( 1 , "?dbPhySetMaterialDynamicFrictionV@@YAXHM@Z" ) ; 349 PHY SET MATERIAL DYNAMIC FRICTION V 
    DB_DarkPhysics\dbPhySetMaterialStaticFrictionV= AIsFunction( 1 , "?dbPhySetMaterialStaticFrictionV@@YAXHM@Z" ) ; 350 PHY SET MATERIAL STATIC FRICTION V 
    DB_DarkPhysics\dbPhySetMaterialDirOfAnisotropy= AIsFunction( 1 , "?dbPhySetMaterialDirOfAnisotropy@@YAXHMMM@Z" ) ; 351 PHY SET MATERIAL DIR OF ANISOTROPY 
    DB_DarkPhysics\dbPhySetMaterialFrictionCombine= AIsFunction( 1 , "?dbPhySetMaterialFrictionCombine@@YAXHH@Z" ) ; 352 PHY SET MATERIAL FRICTION COMBINE 
    DB_DarkPhysics\dbPhySetMaterialRestitutionCombine= AIsFunction( 1 , "?dbPhySetMaterialRestitutionCombine@@YAXHH@Z" ) ; 353 PHY SET MATERIAL RESTITUTION COMBINE 
    DB_DarkPhysics\dbPhyBuildMaterial= AIsFunction( 1 , "?dbPhyBuildMaterial@@YAXH@Z" ) ; 354 PHY BUILD MATERIAL 
    DB_DarkPhysics\dbPhyGetMaterialExist= AIsFunction( 1 , "?dbPhyGetMaterialExist@@YAHH@Z" ) ; 355 PHY GET MATERIAL EXIST 
    DB_DarkPhysics\dbPhyGetMaterialDynamicFrictionEx= AIsFunction( 1 , "?dbPhyGetMaterialDynamicFrictionEx@@YAKH@Z" ) ; 356 PHY GET MATERIAL DYNAMIC FRICTION 
    DB_DarkPhysics\dbPhyGetMaterialStaticFrictionEx= AIsFunction( 1 , "?dbPhyGetMaterialStaticFrictionEx@@YAKH@Z" ) ; 357 PHY GET MATERIAL STATIC FRICTION 
    DB_DarkPhysics\dbPhyGetMaterialRestitutionEx= AIsFunction( 1 , "?dbPhyGetMaterialRestitutionEx@@YAKH@Z" ) ; 358 PHY GET MATERIAL RESTITUTION 
    DB_DarkPhysics\dbPhyGetMaterialDynamicFrictionVEx= AIsFunction( 1 , "?dbPhyGetMaterialDynamicFrictionVEx@@YAKH@Z" ) ; 359 PHY GET MATERIAL DYNAMIC FRICTION V 
    DB_DarkPhysics\dbPhyGetMaterialStaticFrictionVEx= AIsFunction( 1 , "?dbPhyGetMaterialStaticFrictionVEx@@YAKH@Z" ) ; 360 PHY GET MATERIAL STATIC FRICTION V 
    DB_DarkPhysics\dbPhyGetMaterialDirOfAnisotropyXEx= AIsFunction( 1 , "?dbPhyGetMaterialDirOfAnisotropyXEx@@YAKH@Z" ) ; 361 PHY GET MATERIAL DIR OF ANISOTROPY X 
    DB_DarkPhysics\dbPhyGetMaterialDirOfAnisotropyYEx= AIsFunction( 1 , "?dbPhyGetMaterialDirOfAnisotropyYEx@@YAKH@Z" ) ; 362 PHY GET MATERIAL DIR OF ANISOTROPY Y 
    DB_DarkPhysics\dbPhyGetMaterialDirOfAnisotropyZEx= AIsFunction( 1 , "?dbPhyGetMaterialDirOfAnisotropyZEx@@YAKH@Z" ) ; 363 PHY GET MATERIAL DIR OF ANISOTROPY Z 
    DB_DarkPhysics\dbPhyGetMaterialFrictionCombine= AIsFunction( 1 , "?dbPhyGetMaterialFrictionCombine@@YAHH@Z" ) ; 364 PHY GET MATERIAL FRICTION COMBINE 
    DB_DarkPhysics\dbPhyGetMaterialRestitutionCombine= AIsFunction( 1 , "?dbPhyGetMaterialRestitutionCombine@@YAHH@Z" ) ; 365 PHY GET MATERIAL RESTITUTION COMBINE 
    DB_DarkPhysics\dbPhySetRigidBodyPosition= AIsFunction( 1 , "?dbPhySetRigidBodyPosition@@YAXHMMM@Z" ) ; 366 PHY SET RIGID BODY POSITION 
    DB_DarkPhysics\dbPhySetRigidBodyRotation= AIsFunction( 1 , "?dbPhySetRigidBodyRotation@@YAXHMMM@Z" ) ; 367 PHY SET RIGID BODY ROTATION 
    DB_DarkPhysics\dbPhySetRigidBodyMass= AIsFunction( 1 , "?dbPhySetRigidBodyMass@@YAXHM@Z" ) ; 368 PHY SET RIGID BODY MASS 
    DB_DarkPhysics\dbPhyGetRigidBodyMassEx= AIsFunction( 1 , "?dbPhyGetRigidBodyMassEx@@YAKH@Z" ) ; 369 PHY GET RIGID BODY MASS 
    DB_DarkPhysics\dbPhySetRigidBodyMassOffsetLocal= AIsFunction( 1 , "?dbPhySetRigidBodyMassOffsetLocal@@YAXHMMM@Z" ) ; 370 PHY SET RIGID BODY MASS OFFSET LOCAL 
    DB_DarkPhysics\dbPhySetRigidBodyMassOffsetGlobal= AIsFunction( 1 , "?dbPhySetRigidBodyMassOffsetGlobal@@YAXHMMM@Z" ) ; 371 PHY SET RIGID BODY MASS OFFSET GLOBAL 
    DB_DarkPhysics\dbPhyUpdateRigidBodyMass= AIsFunction( 1 , "?dbPhyUpdateRigidBodyMass@@YAXHMM@Z" ) ; 372 PHY UPDATE RIGID BODY MASS 
    DB_DarkPhysics\dbPhySetRigidBodyLinearDamping= AIsFunction( 1 , "?dbPhySetRigidBodyLinearDamping@@YAXHM@Z" ) ; 373 PHY SET RIGID BODY LINEAR DAMPING 
    DB_DarkPhysics\dbPhySetRigidBodyAngularDamping= AIsFunction( 1 , "?dbPhySetRigidBodyAngularDamping@@YAXHM@Z" ) ; 374 PHY SET RIGID BODY ANGULAR DAMPING 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearDampingEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearDampingEx@@YAKH@Z" ) ; 375 PHY GET RIGID BODY LINEAR DAMPING 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularDampingEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularDampingEx@@YAKH@Z" ) ; 376 PHY GET RIGID BODY ANGULAR DAMPING 
    DB_DarkPhysics\dbPhySetRigidBodyLinearVelocity= AIsFunction( 1 , "?dbPhySetRigidBodyLinearVelocity@@YAXHMMM@Z" ) ; 377 PHY SET RIGID BODY LINEAR VELOCITY 
    DB_DarkPhysics\dbPhySetRigidBodyAngularVelocity= AIsFunction( 1 , "?dbPhySetRigidBodyAngularVelocity@@YAXHMMM@Z" ) ; 378 PHY SET RIGID BODY ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhySetRigidBodyMaxAngularVelocity= AIsFunction( 1 , "?dbPhySetRigidBodyMaxAngularVelocity@@YAXHM@Z" ) ; 379 PHY SET RIGID BODY MAX ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearVelocityXEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearVelocityXEx@@YAKH@Z" ) ; 380 PHY GET RIGID BODY LINEAR VELOCITY X 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearVelocityYEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearVelocityYEx@@YAKH@Z" ) ; 381 PHY GET RIGID BODY LINEAR VELOCITY Y 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearVelocityZEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearVelocityZEx@@YAKH@Z" ) ; 382 PHY GET RIGID BODY LINEAR VELOCITY Z 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularVelocityXEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularVelocityXEx@@YAKH@Z" ) ; 383 PHY GET RIGID BODY ANGULAR VELOCITY X 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularVelocityYEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularVelocityYEx@@YAKH@Z" ) ; 384 PHY GET RIGID BODY ANGULAR VELOCITY Y 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularVelocityZEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularVelocityZEx@@YAKH@Z" ) ; 385 PHY GET RIGID BODY ANGULAR VELOCITY Z 
    DB_DarkPhysics\dbPhyGetRigidBodyMaxAngularVelocityEx= AIsFunction( 1 , "?dbPhyGetRigidBodyMaxAngularVelocityEx@@YAKH@Z" ) ; 386 PHY GET RIGID BODY MAX ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhySetRigidBodyCCDMotionThreshold= AIsFunction( 1 , "?dbPhySetRigidBodyCCDMotionThreshold@@YAXHM@Z" ) ; 387 PHY SET RIGID BODY CCD MOTION THRESHOLD 
    DB_DarkPhysics\dbPhyGetRigidBodyCCDMotionThresholdEx= AIsFunction( 1 , "?dbPhyGetRigidBodyCCDMotionThresholdEx@@YAKH@Z" ) ; 388 PHY GET RIGID BODY CCD MOTION THRESHOLD 
    DB_DarkPhysics\dbPhySetRigidBodyLinearMomentum= AIsFunction( 1 , "?dbPhySetRigidBodyLinearMomentum@@YAXHMMM@Z" ) ; 389 PHY SET RIGID BODY LINEAR MOMENTUM 
    DB_DarkPhysics\dbPhySetRigidBodyAngularMomentum= AIsFunction( 1 , "?dbPhySetRigidBodyAngularMomentum@@YAXHMMM@Z" ) ; 390 PHY SET RIGID BODY ANGULAR MOMENTUM 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearMomentumXEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearMomentumXEx@@YAKH@Z" ) ; 391 PHY GET RIGID BODY LINEAR MOMENTUM X 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearMomentumYEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearMomentumYEx@@YAKH@Z" ) ; 392 PHY GET RIGID BODY LINEAR MOMENTUM Y 
    DB_DarkPhysics\dbPhyGetRigidBodyLinearMomentumZEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLinearMomentumZEx@@YAKH@Z" ) ; 393 PHY GET RIGID BODY LINEAR MOMENTUM Z 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularMomentumXEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularMomentumXEx@@YAKH@Z" ) ; 394 PHY GET RIGID BODY ANGULAR MOMENTUM X 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularMomentumYEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularMomentumYEx@@YAKH@Z" ) ; 395 PHY GET RIGID BODY ANGULAR MOMENTUM Y 
    DB_DarkPhysics\dbPhyGetRigidBodyAngularMomentumZEx= AIsFunction( 1 , "?dbPhyGetRigidBodyAngularMomentumZEx@@YAKH@Z" ) ; 396 PHY GET RIGID BODY ANGULAR MOMENTUM Z 
    DB_DarkPhysics\dbPhyAddRigidBodyForce= AIsFunction( 1 , "?dbPhyAddRigidBodyForce@@YAXHMMMMMMH@Z" ) ; 397 PHY ADD RIGID BODY FORCE 
    DB_DarkPhysics\dbPhyAddRigidBodyForceAtLocal= AIsFunction( 1 , "?dbPhyAddRigidBodyForceAtLocal@@YAXHMMMMMMH@Z" ) ; 398 PHY ADD RIGID BODY FORCE AT LOCAL 
    DB_DarkPhysics\dbPhyAddRigidBodyLocalForce= AIsFunction( 1 , "?dbPhyAddRigidBodyLocalForce@@YAXHMMMMMMH@Z" ) ; 399 PHY ADD RIGID BODY LOCAL FORCE 
    DB_DarkPhysics\dbPhyAddRigidBodyLocalForceAtLocal= AIsFunction( 1 , "?dbPhyAddRigidBodyLocalForceAtLocal@@YAXHMMMMMMH@Z" ) ; 400 PHY ADD RIGID BODY LOCAL FORCE AT LOCAL 
    DB_DarkPhysics\dbPhyAddRigidBodyForce1= AIsFunction( 1 , "?dbPhyAddRigidBodyForce@@YAXHMMMH@Z" ) ; 401 PHY ADD RIGID BODY FORCE 
    DB_DarkPhysics\dbPhyAddRigidBodyLocalForce1= AIsFunction( 1 , "?dbPhyAddRigidBodyLocalForce@@YAXHMMMH@Z" ) ; 402 PHY ADD RIGID BODY LOCAL FORCE 
    DB_DarkPhysics\dbPhyAddRigidBodyTorque= AIsFunction( 1 , "?dbPhyAddRigidBodyTorque@@YAXHMMMH@Z" ) ; 403 PHY ADD RIGID BODY TORQUE 
    DB_DarkPhysics\dbPhyAddRigidBodyLocalTorque= AIsFunction( 1 , "?dbPhyAddRigidBodyLocalTorque@@YAXHMMMH@Z" ) ; 404 PHY ADD RIGID BODY LOCAL TORQUE 
    DB_DarkPhysics\dbPhyGetRigidBodyPointVelocityXEx= AIsFunction( 1 , "?dbPhyGetRigidBodyPointVelocityXEx@@YAKHMMM@Z" ) ; 405 PHY GET RIGID BODY POINT VELOCITY X 
    DB_DarkPhysics\dbPhyGetRigidBodyPointVelocityYEx= AIsFunction( 1 , "?dbPhyGetRigidBodyPointVelocityYEx@@YAKHMMM@Z" ) ; 406 PHY GET RIGID BODY POINT VELOCITY Y 
    DB_DarkPhysics\dbPhyGetRigidBodyPointVelocityZEx= AIsFunction( 1 , "?dbPhyGetRigidBodyPointVelocityZEx@@YAKHMMM@Z" ) ; 407 PHY GET RIGID BODY POINT VELOCITY Z 
    DB_DarkPhysics\dbPhyGetRigidBodyLocalPointVelocityXEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLocalPointVelocityXEx@@YAKHMMM@Z" ) ; 408 PHY GET RIGID BODY LOCAL POINT VELOCITY X 
    DB_DarkPhysics\dbPhyGetRigidBodyLocalPointVelocityYEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLocalPointVelocityYEx@@YAKHMMM@Z" ) ; 409 PHY GET RIGID BODY LOCAL POINT VELOCITY Y 
    DB_DarkPhysics\dbPhyGetRigidBodyLocalPointVelocityZEx= AIsFunction( 1 , "?dbPhyGetRigidBodyLocalPointVelocityZEx@@YAKHMMM@Z" ) ; 410 PHY GET RIGID BODY LOCAL POINT VELOCITY Z 
    DB_DarkPhysics\dbPhySetRigidBodySleepLinearVelocity= AIsFunction( 1 , "?dbPhySetRigidBodySleepLinearVelocity@@YAXHM@Z" ) ; 411 PHY SET RIGID BODY SLEEP LINEAR VELOCITY 
    DB_DarkPhysics\dbPhySetRigidBodySleepAngularVelocity= AIsFunction( 1 , "?dbPhySetRigidBodySleepAngularVelocity@@YAXHM@Z" ) ; 412 PHY SET RIGID BODY SLEEP ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhyWakeUpRigidBody= AIsFunction( 1 , "?dbPhyWakeUpRigidBody@@YAXHM@Z" ) ; 413 PHY WAKE UP RIGID BODY 
    DB_DarkPhysics\dbPhyGetRigidBodySleeping= AIsFunction( 1 , "?dbPhyGetRigidBodySleeping@@YAHH@Z" ) ; 414 PHY GET RIGID BODY SLEEPING 
    DB_DarkPhysics\dbPhyGetRigidBodySleepLinearVelocityEx= AIsFunction( 1 , "?dbPhyGetRigidBodySleepLinearVelocityEx@@YAKH@Z" ) ; 415 PHY GET RIGID BODY SLEEP LINEAR VELOCITY 
    DB_DarkPhysics\dbPhyGetRigidBodySleepAngularVelocityEx= AIsFunction( 1 , "?dbPhyGetRigidBodySleepAngularVelocityEx@@YAKH@Z" ) ; 416 PHY GET RIGID BODY SLEEP ANGULAR VELOCITY 
    DB_DarkPhysics\dbPhySetRigidBodyKinematic= AIsFunction( 1 , "?dbPhySetRigidBodyKinematic@@YAXHH@Z" ) ; 417 PHY SET RIGID BODY KINEMATIC 
    DB_DarkPhysics\dbPhySetRigidBodyKinematicPosition= AIsFunction( 1 , "?dbPhySetRigidBodyKinematicPosition@@YAXHMMM@Z" ) ; 418 PHY SET RIGID BODY KINEMATIC POSITION 
    DB_DarkPhysics\dbPhySetRigidBodyKinematicRotation= AIsFunction( 1 , "?dbPhySetRigidBodyKinematicRotation@@YAXHMMM@Z" ) ; 419 PHY SET RIGID BODY KINEMATIC ROTATION 
    DB_DarkPhysics\dbPhyRayCastAllShapes= AIsFunction( 1 , "?dbPhyRayCastAllShapes@@YAHMMMMMM@Z" ) ; 420 PHY RAY CAST ALL SHAPES 
    DB_DarkPhysics\dbPhyGetRayCastHit= AIsFunction( 1 , "?dbPhyGetRayCastHit@@YAHXZ" ) ; 421 PHY GET RAY CAST HIT 
    DB_DarkPhysics\dbPhyGetRayCastHitPointXEx= AIsFunction( 1 , "?dbPhyGetRayCastHitPointXEx@@YAKXZ" ) ; 422 PHY GET RAY CAST HIT POINT X 
    DB_DarkPhysics\dbPhyGetRayCastHitPointYEx= AIsFunction( 1 , "?dbPhyGetRayCastHitPointYEx@@YAKXZ" ) ; 423 PHY GET RAY CAST HIT POINT Y 
    DB_DarkPhysics\dbPhyGetRayCastHitPointZEx= AIsFunction( 1 , "?dbPhyGetRayCastHitPointZEx@@YAKXZ" ) ; 424 PHY GET RAY CAST HIT POINT Z 
    DB_DarkPhysics\dbPhyGetRayCastHitNormalXEx= AIsFunction( 1 , "?dbPhyGetRayCastHitNormalXEx@@YAKXZ" ) ; 425 PHY GET RAY CAST HIT NORMAL X 
    DB_DarkPhysics\dbPhyGetRayCastHitNormalYEx= AIsFunction( 1 , "?dbPhyGetRayCastHitNormalYEx@@YAKXZ" ) ; 426 PHY GET RAY CAST HIT NORMAL Y 
    DB_DarkPhysics\dbPhyGetRayCastHitNormalZEx= AIsFunction( 1 , "?dbPhyGetRayCastHitNormalZEx@@YAKXZ" ) ; 427 PHY GET RAY CAST HIT NORMAL Z 
    DB_DarkPhysics\dbPhyGetRayCastDistanceEx= AIsFunction( 1 , "?dbPhyGetRayCastDistanceEx@@YAKXZ" ) ; 428 PHY GET RAY CAST DISTANCE 
    DB_DarkPhysics\dbPhyGetRayCastTU= AIsFunction( 1 , "?dbPhyGetRayCastTU@@YAKXZ" ) ; 429 PHY GET RAY CAST TU 
    DB_DarkPhysics\dbPhyGetRayCastTV= AIsFunction( 1 , "?dbPhyGetRayCastTV@@YAKXZ" ) ; 430 PHY GET RAY CAST TV 
    DB_DarkPhysics\dbPhyGetRayCastObject= AIsFunction( 1 , "?dbPhyGetRayCastObject@@YAHXZ" ) ; 431 PHY GET RAY CAST OBJECT 
    DB_DarkPhysics\dbPhyMakeTriggerBox= AIsFunction( 1 , "?dbPhyMakeTriggerBox@@YAXHMMMMMMMMM@Z" ) ; 432 PHY MAKE TRIGGER BOX 
    DB_DarkPhysics\dbPhyMakeTriggerSphere= AIsFunction( 1 , "?dbPhyMakeTriggerSphere@@YAXHMMMM@Z" ) ; 433 PHY MAKE TRIGGER SPHERE 
    DB_DarkPhysics\dbPhyDeleteTrigger= AIsFunction( 1 , "?dbPhyDeleteTrigger@@YAXH@Z" ) ; 434 PHY DELETE TRIGGER 
    DB_DarkPhysics\dbPhyTriggerExist= AIsFunction( 1 , "?dbPhyTriggerExist@@YAHH@Z" ) ; 435 PHY TRIGGER EXIST 
    DB_DarkPhysics\dbPhyTriggerType= AIsFunction( 1 , "?dbPhyTriggerType@@YAHH@Z" ) ; 436 PHY TRIGGER TYPE 
    DB_DarkPhysics\dbPhyGetTriggerData= AIsFunction( 1 , "?dbPhyGetTriggerData@@YAHXZ" ) ; 437 PHY GET TRIGGER DATA 
    DB_DarkPhysics\dbPhyGetTriggerObjectA= AIsFunction( 1 , "?dbPhyGetTriggerObjectA@@YAHXZ" ) ; 438 PHY GET TRIGGER OBJECT A 
    DB_DarkPhysics\dbPhyGetTriggerObjectB= AIsFunction( 1 , "?dbPhyGetTriggerObjectB@@YAHXZ" ) ; 439 PHY GET TRIGGER OBJECT B 
    DB_DarkPhysics\dbPhyGetTriggerAction= AIsFunction( 1 , "?dbPhyGetTriggerAction@@YAHXZ" ) ; 440 PHY GET TRIGGER ACTION 
    DB_DarkPhysics\dbPhyCreateVehicle= AIsFunction( 1 , "?dbPhyCreateVehicle@@YAXH@Z" ) ; 441 PHY CREATE VEHICLE 
    DB_DarkPhysics\dbPhyAddVehicleBody= AIsFunction( 1 , "?dbPhyAddVehicleBody@@YAXHMMMMMM@Z" ) ; 442 PHY ADD VEHICLE BODY 
    DB_DarkPhysics\dbPhyAddVehicleWheel= AIsFunction( 1 , "?dbPhyAddVehicleWheel@@YAXHHMMMMMHH@Z" ) ; 443 PHY ADD VEHICLE WHEEL 
    DB_DarkPhysics\dbPhyBuildVehicle= AIsFunction( 1 , "?dbPhyBuildVehicle@@YAXH@Z" ) ; 444 PHY BUILD VEHICLE 
    DB_DarkPhysics\dbPhySetVehicleMass= AIsFunction( 1 , "?dbPhySetVehicleMass@@YAXHM@Z" ) ; 445 PHY SET VEHICLE MASS 
    DB_DarkPhysics\dbPhySetVehicleAuto= AIsFunction( 1 , "?dbPhySetVehicleAuto@@YAXHH@Z" ) ; 446 PHY SET VEHICLE AUTO 
    DB_DarkPhysics\dbPhySetVehicleMaxMotor= AIsFunction( 1 , "?dbPhySetVehicleMaxMotor@@YAXHM@Z" ) ; 447 PHY SET VEHICLE MAX MOTOR 
    DB_DarkPhysics\dbPhySetVehicleMotorForce= AIsFunction( 1 , "?dbPhySetVehicleMotorForce@@YAXHM@Z" ) ; 448 PHY SET VEHICLE MOTOR FORCE 
    DB_DarkPhysics\dbPhySetVehicleWheelPower= AIsFunction( 1 , "?dbPhySetVehicleWheelPower@@YAXHHH@Z" ) ; 449 PHY SET VEHICLE WHEEL POWER 
    DB_DarkPhysics\dbPhySetVehicleSteeringDelta= AIsFunction( 1 , "?dbPhySetVehicleSteeringDelta@@YAXHM@Z" ) ; 450 PHY SET VEHICLE STEERING DELTA 
    DB_DarkPhysics\dbPhySetVehicleMaxSteeringAngle= AIsFunction( 1 , "?dbPhySetVehicleMaxSteeringAngle@@YAXHM@Z" ) ; 451 PHY SET VEHICLE MAX STEERING ANGLE 
    DB_DarkPhysics\dbPhySetVehicleWheelRotation= AIsFunction( 1 , "?dbPhySetVehicleWheelRotation@@YAXHHH@Z" ) ; 452 PHY SET VEHICLE WHEEL ROTATION 
    DB_DarkPhysics\dbPhySetVehicleSuspensionSpring= AIsFunction( 1 , "?dbPhySetVehicleSuspensionSpring@@YAXHM@Z" ) ; 453 PHY SET VEHICLE SUSPENSION SPRING 
    DB_DarkPhysics\dbPhySetVehicleSuspensionDamping= AIsFunction( 1 , "?dbPhySetVehicleSuspensionDamping@@YAXHM@Z" ) ; 454 PHY SET VEHICLE SUSPENSION DAMPING 
    DB_DarkPhysics\dbPhySetVehicleSuspensionBias= AIsFunction( 1 , "?dbPhySetVehicleSuspensionBias@@YAXHM@Z" ) ; 455 PHY SET VEHICLE SUSPENSION BIAS 
    DB_DarkPhysics\dbPhySetVehicleRestitution= AIsFunction( 1 , "?dbPhySetVehicleRestitution@@YAXHM@Z" ) ; 456 PHY SET VEHICLE RESTITUTION 
    DB_DarkPhysics\dbPhySetVehicleStaticFriction= AIsFunction( 1 , "?dbPhySetVehicleStaticFriction@@YAXHM@Z" ) ; 457 PHY SET VEHICLE STATIC FRICTION 
    DB_DarkPhysics\dbPhySetVehicleStaticFrictionV= AIsFunction( 1 , "?dbPhySetVehicleStaticFrictionV@@YAXHM@Z" ) ; 458 PHY SET VEHICLE STATIC FRICTION V 
    DB_DarkPhysics\dbPhySetVehicleDynamicFriction= AIsFunction( 1 , "?dbPhySetVehicleDynamicFriction@@YAXHM@Z" ) ; 459 PHY SET VEHICLE DYNAMIC FRICTION 
    DB_DarkPhysics\dbPhySetVehicleDynamicFrictionV= AIsFunction( 1 , "?dbPhySetVehicleDynamicFrictionV@@YAXHM@Z" ) ; 460 PHY SET VEHICLE DYNAMIC FRICTION V 
    DB_DarkPhysics\dbPhySetVehicleWheelMultiplier= AIsFunction( 1 , "?dbPhySetVehicleWheelMultiplier@@YAXHM@Z" ) ; 461 PHY SET VEHICLE WHEEL MULTIPLIER 
    DB_DarkPhysics\dbPhySetVehicleSteeringAngle= AIsFunction( 1 , "?dbPhySetVehicleSteeringAngle@@YAXHM@Z" ) ; 462 PHY SET VEHICLE STEERING ANGLE 
    DB_DarkPhysics\dbPhySetVehicleSteeringValue= AIsFunction( 1 , "?dbPhySetVehicleSteeringValue@@YAXHM@Z" ) ; 463 PHY SET VEHICLE STEERING VALUE 
    DB_DarkPhysics\dbPhyGetVehicleSteeringAngleEx= AIsFunction( 1 , "?dbPhyGetVehicleSteeringAngleEx@@YAKH@Z" ) ; 464 PHY GET VEHICLE STEERING ANGLE 
    DB_DarkPhysics\dbPhyGetVehicleSteeringDeltaEx= AIsFunction( 1 , "?dbPhyGetVehicleSteeringDeltaEx@@YAKH@Z" ) ; 465 PHY GET VEHICLE STEERING DELTA 
    DB_DarkPhysics\dbPhyGetVehicleMotorForceEx= AIsFunction( 1 , "?dbPhyGetVehicleMotorForceEx@@YAKH@Z" ) ; 466 PHY GET VEHICLE MOTOR FORCE 
    DB_DarkPhysics\dbPhyMakeRevoluteJoint= AIsFunction( 1 , "?dbPhyMakeRevoluteJoint@@YAXHHHMMMMMM@Z" ) ; 467 PHY MAKE REVOLUTE JOINT 
    DB_DarkPhysics\dbPhyMakeRevoluteJoint1= AIsFunction( 1 , "?dbPhyMakeRevoluteJoint@@YAXHHH@Z" ) ; 468 PHY MAKE REVOLUTE JOINT 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvex2= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvex@@YAXH@Z" ) ; 469 PHY MAKE RIGID BODY STATIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvexes2= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvexes@@YAXH@Z" ) ; 470 PHY MAKE RIGID BODY STATIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvex3= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvex@@YAXHH@Z" ) ; 471 PHY MAKE RIGID BODY STATIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticConvexes3= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticConvexes@@YAXHH@Z" ) ; 472 PHY MAKE RIGID BODY STATIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvex2= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvex@@YAXH@Z" ) ; 473 PHY MAKE RIGID BODY DYNAMIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvexes2= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvexes@@YAXH@Z" ) ; 474 PHY MAKE RIGID BODY DYNAMIC CONVEXES 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvex3= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvex@@YAXHH@Z" ) ; 475 PHY MAKE RIGID BODY DYNAMIC CONVEX 
    DB_DarkPhysics\dbPhyMakeRigidBodyDynamicConvexes3= AIsFunction( 1 , "?dbPhyMakeRigidBodyDynamicConvexes@@YAXHH@Z" ) ; 476 PHY MAKE RIGID BODY DYNAMIC CONVEXES 
    DB_DarkPhysics\dbPhySetJointBreakLimits= AIsFunction( 1 , "?dbPhySetJointBreakLimits@@YAXHMM@Z" ) ; 477 PHY SET JOINT BREAK LIMITS 
    DB_DarkPhysics\dbPhySetEmitterCollision= AIsFunction( 1 , "?dbPhySetEmitterCollision@@YAXHH@Z" ) ; 478 PHY SET EMITTER COLLISION 
    DB_DarkPhysics\dbPhySetEmitterCollisionScale= AIsFunction( 1 , "?dbPhySetEmitterCollisionScale@@YAXHM@Z" ) ; 479 PHY SET EMITTER COLLISION SCALE 
    DB_DarkPhysics\dbPhyUpdate1= AIsFunction( 1 , "?dbPhyUpdate@@YAXH@Z" ) ; 480 PHY UPDATE 
    DB_DarkPhysics\dbPhySetGroundPlane= AIsFunction( 1 , "?dbPhySetGroundPlane@@YAXH@Z" ) ; 481 PHY SET GROUND PLANE 
    DB_DarkPhysics\dbPhySetRigidBodyGravity= AIsFunction( 1 , "?dbPhySetRigidBodyGravity@@YAXHH@Z" ) ; 482 PHY SET RIGID BODY GRAVITY 
    DB_DarkPhysics\dbPhySetRigidBodyGroup= AIsFunction( 1 , "?dbPhySetRigidBodyGroup@@YAXHH@Z" ) ; 483 PHY SET RIGID BODY GROUP 
    DB_DarkPhysics\dbPhySleepRigidBody= AIsFunction( 1 , "?dbPhySleepRigidBody@@YAXH@Z" ) ; 484 PHY SLEEP RIGID BODY 
    DB_DarkPhysics\dbPhySetGroupCollision= AIsFunction( 1 , "?dbPhySetGroupCollision@@YAXHHH@Z" ) ; 485 PHY SET GROUP COLLISION 
    DB_DarkPhysics\dbPhySetEmitterRate= AIsFunction( 1 , "?dbPhySetEmitterRate@@YAXHM@Z" ) ; 486 PHY SET EMITTER RATE 
    DB_DarkPhysics\dbPhySetEmitterUpdate= AIsFunction( 1 , "?dbPhySetEmitterUpdate@@YAXHM@Z" ) ; 487 PHY SET EMITTER UPDATE 
    DB_DarkPhysics\dbPhySetFluidScreenSpacing= AIsFunction( 1 , "?dbPhySetFluidScreenSpacing@@YAXHM@Z" ) ; 488 PHY SET FLUID SCREEN SPACING 
    DB_DarkPhysics\dbPhySetFluidTriangleWinding= AIsFunction( 1 , "?dbPhySetFluidTriangleWinding@@YAXHH@Z" ) ; 489 PHY SET FLUID TRIANGLE WINDING 
    DB_DarkPhysics\dbPhySetFluidThreshold= AIsFunction( 1 , "?dbPhySetFluidThreshold@@YAXHM@Z" ) ; 490 PHY SET FLUID THRESHOLD 
    DB_DarkPhysics\dbPhySetFluidParticleRadius= AIsFunction( 1 , "?dbPhySetFluidParticleRadius@@YAXHM@Z" ) ; 491 PHY SET FLUID PARTICLE RADIUS 
    DB_DarkPhysics\dbPhySetFluidDepthSmoothing= AIsFunction( 1 , "?dbPhySetFluidDepthSmoothing@@YAXHM@Z" ) ; 492 PHY SET FLUID DEPTH SMOOTHING 
    DB_DarkPhysics\dbPhySetFluidSilhouetteSmoothing= AIsFunction( 1 , "?dbPhySetFluidSilhouetteSmoothing@@YAXHM@Z" ) ; 493 PHY SET FLUID SILHOUETTE SMOOTHING 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticTerrain= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticTerrain@@YAXH@Z" ) ; 494 PHY MAKE RIGID BODY STATIC TERRAIN 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticTerrain1= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticTerrain@@YAXHH@Z" ) ; 495 PHY MAKE RIGID BODY STATIC TERRAIN 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticTerrain2= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticTerrain@@YAXHPAD@Z" ) ; 496 PHY MAKE RIGID BODY STATIC TERRAIN 
    DB_DarkPhysics\dbPhyMakeRigidBodyStaticTerrain3= AIsFunction( 1 , "?dbPhyMakeRigidBodyStaticTerrain@@YAXHPADH@Z" ) ; 497 PHY MAKE RIGID BODY STATIC TERRAIN 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticTerrain= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticTerrain@@YAXHPAD@Z" ) ; 498 PHY LOAD RIGID BODY STATIC TERRAIN 
    DB_DarkPhysics\dbPhyLoadRigidBodyStaticTerrain1= AIsFunction( 1 , "?dbPhyLoadRigidBodyStaticTerrain@@YAXHPADH@Z" ) ; 499 PHY LOAD RIGID BODY STATIC TERRAIN 
    DB_DarkPhysics\dbPhySetCharacterControllerDisplacement= AIsFunction( 1 , "?dbPhySetCharacterControllerDisplacement@@YAXHMM@Z" ) ; 500 PHY SET CHARACTER CONTROLLER DISPLACEMENT 
    DB_DarkPhysics\dbPhySetCharacterControllerDisplacement1= AIsFunction( 1 , "?dbPhySetCharacterControllerDisplacement@@YAXHMMM@Z" ) ; 501 PHY SET CHARACTER CONTROLLER DISPLACEMENT 
    DB_DarkPhysics\dbPhySetCharacterControllerDisplacement2= AIsFunction( 1 , "?dbPhySetCharacterControllerDisplacement@@YAXHH@Z" ) ; 502 PHY SET CHARACTER CONTROLLER DISPLACEMENT 
    DB_DarkPhysics\dbPhySetCharacterControllerSharpness= AIsFunction( 1 , "?dbPhySetCharacterControllerSharpness@@YAXHM@Z" ) ; 503 PHY SET CHARACTER CONTROLLER SHARPNESS 
    DB_DarkPhysics\dbPhySetCharacterControllerExtents= AIsFunction( 1 , "?dbPhySetCharacterControllerExtents@@YAXHMMM@Z" ) ; 504 PHY SET CHARACTER CONTROLLER EXTENTS 
    DB_DarkPhysics\dbPhySetCharacterControllerExtents1= AIsFunction( 1 , "?dbPhySetCharacterControllerExtents@@YAXHMM@Z" ) ; 505 PHY SET CHARACTER CONTROLLER EXTENTS 
    DB_DarkPhysics\dbPhySetCharacterControllerMinDistance= AIsFunction( 1 , "?dbPhySetCharacterControllerMinDistance@@YAXHM@Z" ) ; 506 PHY SET CHARACTER CONTROLLER MIN DISTANCE 
    DB_DarkPhysics\dbPhySetVehicleBrakeTorque1= AIsFunction( 1 , "?dbPhySetVehicleBrakeTorque@@YAXHHM@Z" ) ; 507 PHY SET VEHICLE BRAKE TORQUE 
    DB_DarkPhysics\dbPhySetVehicleMotorTorque= AIsFunction( 1 , "?dbPhySetVehicleMotorTorque@@YAXHHM@Z" ) ; 508 PHY SET VEHICLE MOTOR TORQUE 
    DB_DarkPhysics\dbPhySetVehicleSteeringAngle1= AIsFunction( 1 , "?dbPhySetVehicleSteeringAngle@@YAXHHM@Z" ) ; 509 PHY SET VEHICLE STEERING ANGLE 
    DB_DarkPhysics\dbPhySetVehicleWheelRadius= AIsFunction( 1 , "?dbPhySetVehicleWheelRadius@@YAXHHM@Z" ) ; 510 PHY SET VEHICLE WHEEL RADIUS 
    DB_DarkPhysics\dbPhySetVehicleSuspensionTravel= AIsFunction( 1 , "?dbPhySetVehicleSuspensionTravel@@YAXHHM@Z" ) ; 511 PHY SET VEHICLE SUSPENSION TRAVEL 
    DB_DarkPhysics\dbPhySetVehicleLongitudalTireForceFunction= AIsFunction( 1 , "?dbPhySetVehicleLongitudalTireForceFunction@@YAXHHMMMMM@Z" ) ; 512 PHY SET VEHICLE LONGITUDINAL TIRE FORCE FUNCTION 
    DB_DarkPhysics\dbPhySetVehicleLateralTireForceFunction= AIsFunction( 1 , "?dbPhySetVehicleLateralTireForceFunction@@YAXHHMMMMM@Z" ) ; 513 PHY SET VEHICLE LATERAL TIRE FORCE FUNCTION 
    DB_DarkPhysics\dbPhySetVehicleWheelFlags= AIsFunction( 1 , "?dbPhySetVehicleWheelFlags@@YAXHHH@Z" ) ; 514 PHY SET VEHICLE WHEEL FLAGS 
   Else
    SUCCESS.l = 0
   EndIf
  ProcedureReturn SUCCESS
 EndProcedure

; IDE Options = PureBasic v4.02 (Windows - x86)
; CursorPosition = 523
; FirstLine = 479
; Folding = -